### ISSUE TITLE
Did you encounter any intellectual hurdles to accepting Mormonism?

### ISSUE THREAD

**Issue by davidchang** [kentcdodds/ama#100]

**Comment by kentcdodds** [comment]
Hi @davidchang,
Thanks for the question!

To give some context, I was born into a Latter-Day Saint (LDS/Mormon) family, so I was raised as a member of the Church of Jesus Christ of Latter-Day Saints. But something very important to members of the church is that we each develop a testimony of the gospel on our own. So I studied the teachings of our church in [the scriptures](http://scripturestories.lds.org/) and the teachings of [our leaders](https://www.lds.org/church/leaders) as a young boy to determine whether the church was true. I had countless experiences which convinced me that the church is true, so I've stuck with it.

I continue to be active in the church. I served a [two year mission](https://www.mormon.org/values/missionary-work) in Missouri and Kansas. I was married and [sealed](https://www.lds.org/church/temples/why-we-build-temples/what-happens-in-temples) in [The Mount Timpanogos Temple](https://www.lds.org/church/temples/mount-timpanogos-utah) and fully expect that my wife and I and our children will be together forever all because of [Jesus Christ](https://www.mormon.org/beliefs/jesus-christ) and [His Atonement](https://www.lds.org/topics/atonement-of-jesus-christ). I also dedicate a great deal of time each week to worship and church service. It's something that I know to be true and I'm happy to work hard to ensure the blessings of the gospel for myself and my family.

So, with that context, here's an answer to your question: Yes. Absolutely. I wouldn't say "all the time" or "often," but once a year or so, something will come up that will really challenge me intellectually. It's definitely been challenging and the church teaches that it's important to resolve these concerns one way or another.

The most effective way that I've found to address these concerns is by following what [President Dieter F. Uchtdorf](https://www.lds.org/church/leader/dieter-f-uchtdorf) taught in his talk [Come, Join with Us](https://www.lds.org/general-conference/2013/10/come-join-with-us) when he said:

> It’s natural to have questions—the acorn of honest inquiry has often sprouted and matured into a great oak of understanding. There are few members of the Church who, at one time or another, have not wrestled with serious or sensitive questions. One of the purposes of the Church is to nurture and cultivate the seed of faith—even in the sometimes sandy soil of doubt and uncertainty. Faith is to hope for things which are not seen but which are true.
> 
> Therefore, my dear brothers and sisters—my dear friends—please, first doubt your doubts before you doubt your faith. We must never allow doubt to hold us prisoner and keep us from the divine love, peace, and gifts that come through faith in the Lord Jesus Christ.

My faith has given me so much. It would be foolish to throw it away every time I struggle to understand the grand scheme of things. So I generally resolve these strugglings by remembering that just because I don't understand something doesn't mean that it's not true. Honestly, sometimes, my ultimate answer is to just leave the question on the shelf and hope that one day it'll make sense to me. And I'm ok with that, just like I'm ok that I don't understand how every part of my cell phone works, and yet benefit from that piece of technology every day. To me, the eternal system that God has set up is much more complex and important than my cell phone, so I can't be expected to understand it all.

Often though, as I pray and study a subject with a real desire to know the truth, I'll receive an answer that satisfies the intellectual hurdle.

Everyone's experience with developing a testimony of the gospel is unique and personal. [Heavenly Father](https://www.lds.org/topics/god-the-father) wants us all to come to know Him, and He will guide us personally through [the Holy Ghost](https://www.lds.org/topics/holy-ghost). I feel incredibly privileged that I was born in a family where I learned this at a very young age. It has made such a positive impact on my life. Happy to answer sincere questions or talk about this subject. It's definitely something that's important to me :-)

I hope that answers your question! (In my usual, long-winded fashion).
