### ISSUE TITLE
Which Utah-based Developers do you admire most?

### ISSUE THREAD

**Issue by joeeames** [kentcdodds/ama#104]
Joe Eames is not a valid answer.

**Comment by kentcdodds** [comment]
Hey @joeeames! 
So many!

- @iammerrick because he's full of humility, ideas, and kindness. And he taught me what `this` means in JavaScript (among other valuable fundamental things). Also, he gave me a start to [my `.bash_profile`](https://github.com/kentcdodds/dotfiles/blob/2bc9a4c399256a6c8fc893f85300e148575c3d2c/.bash_profile#L3-L23) (the emojis there was my addition) when helping me get setup at Domo. He made a big impact on the beginning of my journey into JavaScript app development.
- @djsmith42 because he's incredibly talented, great to talk with, hilarious, and has good insights.
- @tylermcginnis because he's always looking out for the beginner and is working hard to make programming more approachable.
- @mzabriskie because he's great to bounce ideas off of and fun to hang out with
- @joeeames because even though I'm not allowed to answer Joe, he's instilled a love of testing in me.
- @jergason because he's smart, pragmatic, and doesn't have an ounce of arrogance in his body. He also accepted [my first ever talk proposal](https://github.com/kentcdodds/talks#geniejs) at [UtahJS Orem](http://www.meetup.com/UtahJS-Orem-Meetup/events/156148202/)
- @aaronfrost because of his love for the web and including me in lots of stuff he's done (like Google I/O extended, and Google Developer Group).
- @geddski because he's great to have conversations with and toss ideas around. He inspires me to keep working hard at developing my skills and building the things _I_ want to build. He also tipped me off on webpack right before I left Domo. His passing mention of webpack during a conversation lead me to investigate it in the first place.
- @jargv because he's an amazingly skilled and intelligent developer. I can't count the number of conversations that we've had that taught me so much. Our conversations are one of the biggest things I miss about no longer being at Domo.

There are more. I've met some incredibly amazing developers in my short time in the community (even just here in Utah).

Thanks for the question Joe!

**Comment by felipesudrj** [comment]
Hi @kentcdodds thanks for your answer,
I now have developers to follow on twitter.
I´m developer in Brazil - South America
