### ISSUE TITLE
The proper etiquette around submitting a PR to an open source project

### ISSUE THREAD

**Issue by moaazsidat** [kentcdodds/ama#110]
Hey Kent, was about to send this question over Twitter, but saw the AMA page, so going to put it up here instead. 😃 

My question is in regards to open source contribution. I often see people commenting on issues on an open source project on Github that they’d like to work on, but then someone else comes along, and submits a PR. 

What’s the appropriate etiquette in this case? Is it fine to submit a PR to an issue that someone else said that they were going to take on? Just wondering if there’s a generic approach to this or is it something that differs on a per-project basis.

Cheers!

**Comment by kentcdodds** [comment]
Hi @moaazsidat!

Thanks for the questions!

> I often see people commenting on issues on an open source project on Github that they’d like to work on, but then someone else comes along, and submits a PR.

This is a real bummer. I've never really seen it before, but it's unkind to do that IMO. Improper etiquette on the part of the PR submitter. Often people want to work on an issue because they want to learn and experience it. This is why I created [`first-timers-only`](http://kcd.im/first-timers-only), so beginners could get into open source without the fear of someone else taking the issue.

I should note that sometimes a fix needs to get in quickly because people are depending on something. In that scenario, I'd say this kind of thing is acceptable and everyone should be understanding of that. But those cases are definitely rare.

> Just wondering if there’s a generic approach to this or is it something that differs on a per-project basis.

This is just my opinion. I'm sure other project maintainers feel differently about this. ¯\\\_(ツ)_/¯

Thanks for the question!
