### ISSUE TITLE
How does your experience with React changed your view on javascript application development?

### ISSUE THREAD

**Issue by avivr** [kentcdodds/ama#111]
Now that you made the move into React, I'm curious to know how it affect your thinking about javascript applications.
And more specifically, how would it come into effect if you would have to write angular 1.x application today (for example, would you try to use redux or any flux implementation)?

**Comment by kentcdodds** [comment]
Hi @avivr!

Thanks for the questions!

> how it affects your thinking about javascript applications.

Honestly, when I [first played around with react](https://twitter.com/kentcdodds/status/493223570856620032). I instantly realized that [react brings a lot of awesome to the table](https://twitter.com/kentcdodds/status/493244951065419776). I pretty quickly got [really excited](https://twitter.com/kentcdodds/status/494766437357998080) about building stuff in React ([it](https://github.com/kentcdodds/react-components-library) never amounted to much 😅).

It wasn't long before I thought about using react with angular. I even gave [a talk](https://github.com/kentcdodds/talks/tree/7640c2657beb7cf7eec684f534bd0e6979d293c7#using-reactjs-with-existing-angularjs-codebase) on it and did [a proof of concept](https://twitter.com/kentcdodds/status/619168099204333568) on my work app. Ultimately I decided that the business couldn't afford to have me migrate and so I pulled it out. This is actually one of the contributing factors to me [changing jobs](https://github.com/kentcdodds/ama/issues/47) (not a big one, but still a factor).

What React did for me was help me realize the importance of learning and using JavaScript and relying less on abstractions to do stuff. One of my favorite parts of react is how it's mostly just JavaScript. With JSX and tools like [aphrodite](https://github.com/Khan/aphrodite), I can move all of my UI related stuff to JavaScript and that gives me much more power in my own hands than a DSL like Angular's template syntax ever could.

So when I was playing around with React on my spare time and working on Angular at the job, I tried to figure out a way that I could integrate some of my learnings from React into my Angular application. I can't really think of anything I did specifically to be totally honest with you. It's just mostly focusing more on normal JavaScript to do things rather than using Angular things. Actually, one example I can remember is after being exposed to React, I started writing more plain ES6 modules rather than relying on Angular's modules to create factories and such. I didn't have much trouble doing that and it was conceptually simpler and more explicit IMO.

> how would it come into effect if you would have to write angular 1.x application today (for example, would you try to use redux or any flux implementation)?

If I had to write an Angular 1.x application today, I probably wouldn't try to tack on `redux` or `flux` at all. I know there are libraries to combine these things in nice ways, but I just don't think that the concept really fits the Angular model very well. Also, I'm about to answer [a question](https://github.com/kentcdodds/ama/issues/109) about when that's even necessary, and the answer is basically: not often.

Thanks for the question! I hope it was helpful!
