### ISSUE TITLE
Tree Shaking with ES6 modules and TypeScript

### ISSUE THREAD

**Issue by con-ssc** [kentcdodds/ama#123]
I have a small library that is written in typescript with the usual es6 module syntax. So I have some files that are containers for some functions and I here and there import some of those functions. Now my problem is that TypeScript does not tree shake so the whole content of the file gets imported when I try to transpile to es5. Also when I use webpack or webpack2 that also occures. Only rollup seems to tree shake correctly but it obfuscates the original modules by simply putting them into the same function.
Is there any other way to tree shake javascript dependencies to make shorter files?

**Comment by kentcdodds** [comment]
If Rollup is tree-shaking properly and webpack 2 is not, then I recommend you submit a simple example repository to the webpack project because I'm sure they'd love to fix the issue. And you might even try your hand at contributing. I believe this is one of the files you might take a look at: https://github.com/webpack/webpack/blob/b0fffd50d35dd0eef734d189928c1ac4c5c9fb97/lib/dependencies/HarmonyExportExpressionDependency.js

Good luck!
