### ISSUE TITLE
How do you find time to do everything that you do?

### ISSUE THREAD

**Issue by kachhalimbu** [kentcdodds/ama#13]
I'm always in awe of people doing pretty much anything outside of their day job. How do you manage to run a weekly podcast, keep on top of your open source projects, social networking, full time job in addition to having a young family?

**Comment by kentcdodds** [comment]
Thanks for the question. First off, as I said in #12:

> ... Don't give up having meaningful relationships to become "the best." No success outside the walls of your home and family is worth failing at those relationships. Find a balance, and you'll be much happier.

That balance can be incredibly difficult. But it is critical. I feel like I'm more effective with the time that I have when I am living a balanced life (even if it means less time for all the extra stuff).

At times I'm not very good at giving everything the time that it deserves. Sometimes I'll give my open source stuff a lot of focus at the expense of getting the podcast website updated or spending time with my wife and developing that critical relationship. But the key is you keep trying and check yourself often.

---

Also, I multi-task quite often. Likely to a fault. I'm sure I could accomplish even more if I managed my time better. But even as I'm typing out this response to you, I just published the audio for [today's episode](http://audio.angular-air.com/e/22-ngair-angular-data/) and my wife and I are singing to my [Sara Bareilles](https://www.google.com/search?q=Sara%20Bareilles) [Pandora](http://pandora.com) radio station (while she works on something else.

---

Some of the things I [tweet](https://twitter.com/kentcdodds) are just [things that I learned](https://twitter.com/kentcdodds/status/613460022685663232) while working. Other times, it's [a question](https://twitter.com/kentcdodds/status/609602932804194304) because I'm too lazy to ask stack overflow or something (or it could be [that](https://twitter.com/kentcdodds/status/609322829469782018) too). So it ends up relating to the other things I'm involved with.

---

One other thing that I recommend that's sorta related is inbox 0. I [picked it in today's Angular Air episode](https://youtu.be/QAPK51nE3Cc?t=47m53s). It's fantastic and helps me make sure I don't miss or forget to do something.

---

A word on open source projects. Or when you're working on projects in general. Something I learned from @jinxidoru is a concept called "Pain Driven Development." This basically means that you code for your use-case and your use-case only. Don't consider what *might* need to be covered, because you can end up spending a ton of time working to cover a use case that may actually never be needed and then you have code in the project that is not useful but you can't get rid of it without making sure it's not actually being used.

Open source libraries are a little different, but you need to be careful that you're not wasting time on that. Also, you want to make sure that if you think a use case is likely, that you don't code yourself into a corner that makes it difficult to cover that likely use case.

---

I hope that's helpful. Just don't forget the things that really matter. Make sure you make time for that, and you'll be good :-) (and don't forget to sleep, that'll make you more productive as well).

**Comment by kentcdodds** [comment]
Also, one other thing of note is if you see my homescreen (#5) you'll notice that I have an alarm set for 5:30 AM. That way I get about an hour or so of time all to myself. Sometimes I'll wake up at 5 for a little extra time. But again, don't forget to sleep :-)

**Comment by kentcdodds** [comment]
Oh, and [I don't play video games](https://twitter.com/wbucksoft/status/616464460488777728). But I do play foosball :-) (but that's minutes, not hours).

**Comment by benoror** [comment]
Would you mind sharing some info regarding "zero inbox"?

**Comment by kentcdodds** [comment]
Here you go @benoror: http://whatis.techtarget.com/definition/inbox-zero :-)

**Comment by kentcdodds** [comment]
Although I don't use the `requires response` folder he talks about. My `requires response` folder is my inbox. I do actually sort-of use it as a todo list as well...

**Comment by kentcdodds** [comment]
I also leave my email open all day. I like to respond to people right away. I should probably move to an hourly login instead...

**Comment by benoror** [comment]
Cool, actually I've been using [Google Inbox](http://inbox.google.com/) for almost 9 months now, and basically what I always try to do is the following:

* Process e-mail for as long as 10min max, every 1-2 hours
* Delete/Archive as many unimportant messages as possible
* **Defer (snooze)** as many low-priority messages as possible
* Respond/Forward as many high-priority messages as possible

I don't know if that fits 100% with Inbox Zero philosophy, since I also:

* I keep the Inbox tab always open!
* Regarding messages that require longer to respond or are in my ToDo list, I leave them in the Inbox (properly categorized of course), and try to respond them at the end of the day

**Comment by leandroz** [comment]
Great insights, thanks for sharing!
I have an additional question, at what time do you go to bed?

**Comment by kentcdodds** [comment]
Depends on the night. Mostly before 11 though. If I go to bed that late, I
generally don't wake up at 5:30 AM though... I try to get at least 6.5
hours of sleep or more.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
