### ISSUE TITLE
What is the proper way of using multiple classes with aphrodite?

### ISSUE THREAD

**Issue by kitze** [kentcdodds/ama#130]
What do you think it's better/more performant?

```
<div className={css(styles.header, flex.horizontal)} />
```

or
```
<div className={`${css(styles.header)}, ${css(flex.horizontal)}`} />
```
When I combine more styles into one css() call i get one huge class name and I'm not sure if that's better. I would like my flex.horizontal to remain a separate and reusable class so other components should use it too.

**Comment by kentcdodds** [comment]
Hey @kitze!
Thanks for the question. I'll be totally honest with you and say I don't know. And honestly, I'm going to guess that you probably have bigger perf issues in your app than aphrodite. I would recommend just doing the thing that makes the most sense to you and seems like the easier way to do it (so the first one you have) and then benchmark it later if it becomes a problem. It's a good idea to avoid pre-optimizations because you normally end up wasting time optimizing something that makes a minimal impact to perf.

Sorry that's probably not what you were looking for, but I think that's the right way to go about it. Good luck!

**Comment by kitze** [comment]
Thanks for your answer.

**Comment by kentcdodds** [comment]
@kitze, noticed you responded with a 😕 emoji. Anything I can clear up?

**Comment by kitze** [comment]
Yeah I'm a bit confused about aphrodite and performance but that wasn't in scope of the question. 

I had to write this helper
```
export const cxs = (...args) => ({
  className: classnames(_.map(args, arg => css(arg)))
});
```
and use it like

```<div {...cxs(styles.header, flex.horizontal, sharedStyles.wrapper)} />```

Instead of writing ```<div className={`${css(styles.header)} ${css(flex.horizontal) ${css(sharedStyles.wrapper)}}`} />```

I think that aphrodite should have an additional function separateCss() (ofc with a proper name) and when you write ```<div className={separateCss(styles.header, flex.horizontal, sharedStyles.wrapper)}/>``` it will actually add 3 separate classnames, instead of combining those 3 styles into one class.

**Comment by kentcdodds** [comment]
Why do you care about the class name that's generated? Just let aphrodite manage that. I'd recommend just using `css(styles.header, flex.horizontal, sharedStyles.wrapper)` and letting aphrodite manage what happens with that. Who cares if it generates another class?

**Comment by xymostech** [comment]
Hey @kitze! There's a pretty good reason for using `css(styles.header, flex.horizontal)` that I'm now realizing we don't call out very prominently in the Readme:

If you have conflicting styles in `styles.header` and `flex.horizontal` it's not defined which one is going to overwrite the other one. Calling `css(styles.header) + " " + css(flex.horizontal)` will generate CSS that might look like

```
.header_xxxx { }
.horizontal_xxxx { }
```

OR it might also look like

```
.horizontal_xxxx { }
.header_xxxx { }
```

Since both of these are just plain class names their CSS specificity is the same, and in CSS that means that whichever one comes later in the stylesheet will win. In the first case `flex.horizontal` will win and in the second case `styles.header` will win!

The way Aphrodite solves this is by doing a deep merge of all the styles you pass into `css()` in the order that you pass them in and then generating one class for that. That way you are guaranteed that the later arguments will override the earlier ones, or in `css(styles.header, flex.horizontal)`, `flex.horizontal` values will override `styles.header` ones.

So you should always be using `css(styles.header, flex.horizontal)`. If you're experiencing performance problems because of this then please let us know, but it seems unlikely that this is going to be the bottleneck unless you have a huge page. Khan Academy has pages that generate ~350 unique class names and I haven't heard any complaints about performance there.

**Comment by kitze** [comment]
@xymostech I understand what you're saying, but multiple classes instead of one giant one makes more sense to me because of few reasons. 

1. I don't see the issue as "which class will win" because flex.horizontal is applying flex styles, and styles.header is applying local styles for the header
2. When I inspect the website in the dev tools I can clearly see which classes are applied to an element and what styles they apply, so I can easily toggle them on/off from the dev tools etc. 
3. It looks cleaner to look at separate class names instead of one giant class name
4. I think it's better if the "flex.horizontal" class is generated only once for the page, and it's applied to elements that need it. Instead of generating and mixing it with other classes and getting "header_1308413_flex-horizontal_913513" and "footer_139138413_flex-horizontal_103851308" you get "header_1308413 flex-horizontal_318413" and "footer_139138413 flex-horizontal_318413" so the flex-horizontal class stays the same.

I would love to take this discussion further.
