### ISSUE TITLE
Thoughts on Lasik

### ISSUE THREAD

**Issue by AimeeKnight** [kentcdodds/ama#144]
I've gone through the screening process for Lasik and have the surgery scheduled at Johns Hopkins next week, but I'm still a little indecisive. So far are you happy you had the procedure? Do you have any concerns about your eye site in the future? Thanks!

**Comment by kentcdodds** [comment]
Hi @AimeeKnight!

Lasik was one of the best things I ever spent money on. I totally loved it. The procedure was totally anti-climatic. Very routine. Definitely nothing to concern yourself over on that side of things.

It took me a while to totally heal. My eyes are still definitely more dry that they were before the surgery, but still totally not a problem (not bad enough that I use eye drops anyway).

I'm not worried about my eyesight in the future because my eyesight now is so much better. It's a trade off between bad eyesight forever or good eyesight now and bad eyesight later :-)

This is nothing short of a miracle. I totally love that I can see. It took me weeks before I stopped reaching to adjust my glasses or feeling like I'd forgotten something in the morning.

Good luck!
