### ISSUE TITLE
Why does console prints undefined

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#145]
Hello Kent,
I am little curious about the messages which are printed in the console, when we execute a code.

````javascript
var a = 1;
undefined

function foo(){var g=1}
undefined

a=1;
1
````

It will be helpful, if you can give some clues or help me on why the first two codes prints `undefined` in consoles, and the last prints 1.

I am little confused also, what does these `undefined` signifies?
Thanks,
Anirudh

**Comment by kentcdodds** [comment]
Hi @anirudh-modi!
Thanks for the question! So what is happening here is the DevTools console is going to print the result of what you type. So the result of an assignment is `undefined`. So `var a = 1` doesn't evaluate to anything, it simply assigns the variable `a` to the value of `1`, but it doesn't "return" anything.

However, `a = 1` will not only assign the value, but also evaluates to the value assigned (which is `1`). You can see an example of this by doing `var x = a = 1`. This will print out `undefined`, but because `a = 1` evaluates to `1`, the variable `x` will be assigned to `1` as well.

This is the same thing with the `foo` function you have there as well.

You'll also notice similar behavior with:

- `1 + 2` which evaluates to `3` (so you'll get that printed to the console)
- `[1.3, 2.1, 3.3].map(Math.floor)` evaluates to `[1, 2, 3]` (so you'll get that printed to the console)

But because an assignment doesn't evaluate to anything, you get `undefined`.

I hope this makes sense. Please let me know if you're still confused. Good luck!

**Comment by anirudh-modi** [comment]
Hi @kentcdodds 

Thanks for your time. Yep, it does makes sense, that assignment doesn't evaluate to anything, and hence I get `undefined`, however I bumped into another interesting thing, is when I write

````javascript
var a;
a=1;
function foo(){a=2;}
````
This returns `1`, should not it return `undefined` as the last code to be executed was `function` and it doesn't evaluate to anything?

And when I execute `foo` should not it have printed `2` ? It prints `undefined`.
As, `a = 1` will not only assign a value but evaluate?

**Comment by kentcdodds** [comment]
Great question! I'm assuming that this is because of what's called [function declaration hoisting](http://adripofjavascript.com/blog/drips/variable-and-function-hoisting). So when you provide code that looks like:

```javascript
var a;
a=1;
function foo(){a=2;}
```

Things actually happen in a different order:

```javascript
function foo(){a=2;}
var a;
a=1;
```

The reason you're not seeing `2` printed is because when you evaluate `foo()` the result of that evaluation is `undefined` because `foo` implicitly returns `undefined`. If you want it to print `2`, you'd have to do: `function foo(){return a=2}` 👍 

I hope this makes sense!

**Comment by anirudh-modi** [comment]
It totally makes sense, why `2` and `undefined` was returned.
Thanks for such a great explanation. 👍 👍

**Comment by anirudh-modi** [comment]
One last question, why do even the dev console, prints anything at the first place?
like why does it implicitly add a return?

**Comment by anirudh-modi** [comment]
And, also when I tried the code below

````javascript
var x ;
x = 1;
var b = 2;
````

should not it print `undefined`, because the last statement to evaluate was `var b = 1`, which should give `undefined`? but it gives `1`!

I hope I am not taking much of your time.

**Comment by kentcdodds** [comment]
> why do even the dev console, prints anything at the first place

My guess is so it can be useful. Simply typing `2 + 1` and getting `3` printed to the console automatically is much more helpful than having to type out: `console.log(2 + 1)`.

For your latest question, that's surprising to me! I guess I'm not certain what the implementation details are here. Still more to learn about!

**Comment by anirudh-modi** [comment]
OK makes sense, on why they are printing..
Thanks, a lot for your valuable time, and helping me understand, I will share link if I find an answer to my latest question 😊

**Comment by anirudh-modi** [comment]
http://stackoverflow.com/questions/22844840/why-does-javascript-variable-declaration-at-console-results-in-undefined-being?lq=1

Found a stackoverflow link, seems like the dev console uses `eval` and for multiple statements it tries to `return` some value.

**Comment by kentcdodds** [comment]
Very cool! Thanks for sharing!
