### ISSUE TITLE
Dilemma regarding 'npm publish' and semantic-release!

### ISSUE THREAD

**Issue by nirajpandkar** [kentcdodds/ama#146]
All my questions are linked to each other in some way. So you might understand my underlying **dilemma** :P 
### Questions 
1. I have a **JSON database** in my npm library ([thoughts](https://github.com/nirajpandkar/thought-of-the-day)) which I update frequently. What is the **type of commit** should I be making? (_commitizen installed_)
2. If I make a **patch-commit** for every time I update my JSON database, the patch number would be u**nusually large**. What is the solution for this?
3. If I don't make any release, I wouldn't be able to update my npm package using `npm publish`(which requires new version number to update the package). Or is there something I am missing here?

Thanks for your time in anticipation :+1:

**Comment by kentcdodds** [comment]
Hi @nirajpandkar!
Thanks for the question(s) :-)

1. Updates to the `json` file should be `minor` version bumps, so that would be a `feat`. If you think about it, it's not a breaking change (people don't have to change their code to account for your changes). It's not a `patch` change unless you consider the new thoughts to be fixing a "bug" in your software somehow, but that'd be odd to me. So yeah, `feat` is what you'd want to use.
2. As for numbers getting "unusually large" I would ask you: why do you care? It's just a number. It's not for humans, it's for computers. I recommend you check this out: [We fail to follow SemVer – and why it needn’t matter by @boennemann at JSConf Budapest 2015](https://youtu.be/tc2UgG5L7WM?list=PLFZ5NyC0xHDaaTy6tY9p0C0jd_rRRl5Zm) and [read this](https://github.com/semantic-release/semantic-release#is-it-really-a-good-idea-to-release-on-every-push)
3. The only way to push the updates to the json file is by publishing a new release.

Good luck!

**Comment by nirajpandkar** [comment]
Thanks for the prompt answer! I totally agree that updates to json should be a feat!

Just to clarify the answer regarding my third question - 
I should have a new release to update the npm package too - including the Readme on the npm package page.

**Comment by kentcdodds** [comment]
Yeah, unless something's changed, semantic-release doesn't consider `doc` commits to warrant a new release. You can see more about that [here](https://github.com/semantic-release/commit-analyzer/issues/3).

For now, I just deal with this and wait for the docs changes to get published with the next release. Or, if I really want a docs change to be released, I'll assign it a `fix` in the commit message.

**Comment by nirajpandkar** [comment]
Got it :+1: Thanks for the extra links and corresponding resources :)
