### ISSUE TITLE
What are your thoughts on Lessons Learned - Scipy 2014 Talk?

### ISSUE THREAD

**Issue by vramana** [kentcdodds/ama#148]
The presentation is given for researchers but there are general lessons for anyone who wants to teach or who teaches regularly. 

Video Link: https://www.youtube.com/watch?v=1e26rp6qPbA

[This talk](https://www.youtube.com/watch?v=FtKO619O5g0) also has same title but highlights a few other observations.

**Comment by kentcdodds** [comment]
Looks really interesting... I know when I was in school I had more than one time where I wrote papers with my classmates using GitHub because the version control was really nice to have. I agree with his assertions at the end about the benefits of mass collaboration and encouraging everyone to become an instructor. I think that we all have something valuable that we can teach others and you solidify your understanding when you teach others.

Thanks for sharing the video. I enjoyed it :-)
