### ISSUE TITLE
Google developer expert

### ISSUE THREAD

**Issue by vgvenkat** [kentcdodds/ama#153]
How did you get around being a GDE? what was the process like? Has it changed from how you were perceived before and now? What would you advice for some one wanting to reach such standards

**Comment by kentcdodds** [comment]
Hi @vgvenkat!

> How did you get around being a GDE?

So Igor Minar invited me to be a GDE because of my contributions to the web community (between [OSS](https://github.com/kentcdodds), [my](http://angularair.com/) [podcasts](https://javascriptair.com), [talks](http://kcd.im/talks), etc.).

> what was the process like?

Basically here's what happened for me:
1. I was asked to submit a [CV](https://en.wikipedia.org/wiki/Curriculum_vitae)
2. I was interviewed by a current web GDE. He knew who I was and of my contributions to the web community, so it was more of a fun conversation. I'm not sure what this would have been like otherwise.
3. I was interviewed by a Googler. I don't think he knew who I was before, but we pretty much just chatted about the future of the web too.
4. I was accepted into the program.

There was a lot of waiting and some emailing in between, but that's pretty much it.

> Has it changed from how you were perceived before and now?

I'm not sure. Maybe? I've put it on my Twitter and LinkedIn (just added).

> What would you advice for some one wanting to reach such standards

I think I answer that and more in my talk [Zero to 60 in Software Development: How to Jumpstart Your Career](https://youtu.be/-qPh6I2hfjw)

Thanks for the question :-)

**Comment by vgvenkat** [comment]
This is awesome! Thank you
