### ISSUE TITLE
Tree-Shaking with Webpack and TypeScript

### ISSUE THREAD

**Issue by d3lm** [kentcdodds/ama#154]
I was wondering how tree-shaking is possible when using TypeScript and Webpack. In your egghead series _Using Webpack for Production JavaScript Applications_ you are using Babel and ES6. I know there is something like Rollup.js which also has a TypeScript plugin, which I could use in a separate build step, but I am not sure if that also works for minified JavaScript as well. So I wanted to hear your opinion and advice on how to use tree-shaking with Webpack 2 and Typescript.

**Comment by kentcdodds** [comment]
Hi @d3lm!
I've gotten this question a LOT. So here's how things that are required for Tree-shaking to work:
1. The code must have ES6 modules
2. The modules must be analyzed
3. The exports which are not used anywhere are transformed in a way such that they are no longer exported. Because the transformed code doesn't have those things being exported, that code is now "dead code" or "code that will never be used/run"
4. A JS minifier (like [UglifyJS](https://github.com/mishoo/UglifyJS2)) eliminates dead code

To accomplish this, webpack takes care of 2 and 3. You write your code using ES6 modules, which is great. Where things stop working is when you pass your code through TypeScript instructing it to transform ES6 to ES5. When it does this, it transforms your ES6 modules to CommonJS. Therefore, you don't have # 1 on that list.

With Babel the solution is pretty simple. You exclude the ES6 modules transform (by using the `es2015-webpack` preset). With TypeScript, there's currently no way to tell it which transforms to use on your code. I believe that in version 2.0 of TypeScript, it will be possible to do this, but until then, it's not possible to get Tree Shaking with TypeScript by itself.

You could try the Rollup.js solution. But because I've never used TypeScript I can't really give you a solid recommendation of how to solve this problem today. Good luck!

**Comment by evandertino** [comment]
Hello @kentcdodds 

Typescript @next now [supports this.](https://github.com/Microsoft/TypeScript/issues/9161#issuecomment-226976800)

I configured a [small demo ](https://github.com/evandertino/webpack-learn)after watching your series, to check how tree shaking works with webpack2 and typescript, webpack2 is able to analyze the modules correctly and i saw this through the harmony exports, but the thing is, when compressed the dead code is not eliminated. Any ideas why this is not working?

**Comment by kentcdodds** [comment]
Hmmm, I would assume that's a bug in webpack's Uglify plugin. I recommend filing a good bug report on the webpack repo. Good luck! And thanks for sharing!

**Comment by d3lm** [comment]
@evandertino Maybe you are missing the es2015-webpack preset?
