### ISSUE TITLE
Decoding ES documentation

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#156]
Hello Kent,

The Ecmascript specification gets a little confusing, like what they try to say, can be hard to decode a little. So, is there anything sort of thumb rule to decode or is it I have improve reading skills 😆

Thanks,
Anirudh

**Comment by kentcdodds** [comment]
Hi again @anirudh-modi :wave:
Honestly, I don't peruse the spec all that often. Generally I'll learn from blogposts from @rauschma, @bevacqua, and others. Other than that, I'll read the spec and I guess it just kind of makes sense to me or it doesn't. I'm afraid I don't really have great tips on it.

One thing you might try is if there's support for it in Babel, you could put some code in babel and see what comes out. Mind you this isn't a great way to learn the spec, because it can definitely be misleading (read [tears](http://kcd.im/tears)), but it may point you in the right direction.

Another thing you could try is putting the code in [astexplorer.net](http://astexplorer.net) and exploring the AST tree. It's fascinating and you can see what each bit is called.

Good luck!

**Comment by anirudh-modi** [comment]
Thanks again @kentcdodds for your time 😊
By the way is there any limit on number of questions which can be asked by a person?

**Comment by kentcdodds** [comment]
> Thanks again @kentcdodds for your time 😊

Sure thing!

> By the way is there any limit on number of questions which can be asked by a person?

Of course not :-) Feel free to ask as many as you like.

**Comment by anirudh-modi** [comment]
Awesome!! 😊
