### ISSUE TITLE
Aphrodite and variable media queries?

### ISSUE THREAD

**Issue by jonandrewdavis** [kentcdodds/ama#166]
Hi there!

Quick code question about Aphrodite. I've been playing with the syntax for awhile and it's stumped me. I was searching through the closed Issues to see if there's a way I can do this, when I saw your name.

I'd like to have a variable for my media query.
```
export const someVar = '500px'
```

```
import { StyleSheet, css } from 'aphrodite';
import { someVar } from './sizes';

const styles = StyleSheet.create({
  foo: {
    width:'100%',
    '@media(min-width:500px)': {
      color : 'red',
    },
  },
});
```

How can I use `someVar` instead of `500px`? I'm not sure how to configure. I've tried using a immediately invoked function expression that returned a string, but it didn't go so well. Aphrodite didn't write a rule for the media query...

How could my approach be improved? 

Thanks for your time!

**Comment by kentcdodds** [comment]
Hey @jonandrewdavis!
I actually just recorded a lesson for PayPal yesterday about media queries with aphrodite. I think this'll help you:

https://youtu.be/YXGIl7ptyiI?list=PLo4Zh55ZzNSBP78pCD0dZJi9zf8CA72_M

Specifically for your problem, you could do:

```javascript
import { StyleSheet, css } from 'aphrodite';
import { someVar } from './sizes';

const styles = StyleSheet.create({
  foo: {
    width:'100%',
    [`@media(min-width:${someVar})`]: {
      color : 'red',
    },
  },
});
```

I'm guessing that you're using ES6 because of your `import` statements, but if, for some reason you cannot, you could do this in regular ol' ES5:


```javascript
import { StyleSheet, css } from 'aphrodite';
import { someVar } from './sizes';

const stylesObject = {
  foo: {
    width:'100%',
  },
}
stylesObject.foo[`@media(min-width:${someVar})`] = {color: 'red'}
const styles = StyleSheet.create(stylesObject);
```

Oh, and if you wanted to go the IIFE approach:

```javascript
import { StyleSheet, css } from 'aphrodite';
import { someVar } from './sizes';

const styles = StyleSheet.create((function() {
  const stylesObject = {
    foo: {
      width:'100%',
    },
  }
  stylesObject.foo[`@media(min-width:${someVar})`] = {color: 'red'}
  return stylesObject
})());
```

Though I'm not sure this is advisable ;-)

Good luck!
