### ISSUE TITLE
Breaking through to the community?

### ISSUE THREAD

**Issue by abhiaiyer91** [kentcdodds/ama#167]
Hey Kent, I was wondering how I could get the street cred to be on JavaScript air? Lately I've been contributing to open source but in more of an educational route. I think I have good opinions for beginners and more advanced people. I guess I don't know what to do to breakthrough to the wider community! Any suggestions?

**Comment by kentcdodds** [comment]
Hey @abhiaiyer91,
Thanks for the question. I actually talk about how I got involved in the community a bit in my talk [Zero to 60 in Software Development: How to Jumpstart your career](https://github.com/kentcdodds/talks/tree/afb5f9fb9c6dd8bcdc8dc14e454edc6e60aa4362#zero-to-60-in-software-development-how-to-jumpstart-your-career). I recommend that you check that out. TL;DR:

- Do OSS ([create](https://kcd.im/write-oss) and [contribute](https://kcd.im/pull-request))
- Write Blogposts
- [Create video screencasts](https://kcd.im/screencasting)
- Give workshops
- Give talks at meetups and conferences (if you're rejected, don't give up)

On the topic of getting on podcasts... Doing those things above is a good approach. For me, part of the reason I started [Angular Air](http://angularair.com/) was because I hadn't been invited to be on a podcast and anytime I listened to one I always had stuff I wanted to say. So I pushed myself into the conversation by creating my own podcast. Then I fearlessly invited people to come chat with me.

I hope this helps answer your question!
