### ISSUE TITLE
Reading habits

### ISSUE THREAD

**Issue by benoror** [kentcdodds/ama#17]
Considering our field (IT) is evolving exponentially, I am very curious on how other people have their daily doses of information (besides the work-related stuff) to stay relevant and updated.

* What kind of information sources do you consume on a regular basis (Books, Magazines, Twitter, HN, Blog Feeds, Podcasts, ...)?
* What off-topics are you interested in (IT-related, besides the work-related specifics)?
* What tools do you use regularly (E-Reader, Tweetdeck, Medium, Feedkly, Pocket Casts)?
* Do you allocate some time of your day for consuming information, or you just do it on the fly?
* Do you have an specific routine/process for information consumption?

**Comment by kentcdodds** [comment]
> What kind of information sources do you consume on a regular basis (Books, Magazines, Twitter, HN, Blog Feeds, Podcasts, ...)?

I rarely read Books, I prefer hands-on and video tutorials. I never read Magazines. [I use Twitter](https://twitter.com/kentcdodds) a lot. I hardly ever get on [HN](https://news.ycombinator.com/), I don't use a blog feed. I listen to [JavaScript Jabber](http://devchat.tv/js-jabber/), [Adventures in Angular](http://devchat.tv/adventures-in-angular), [Angular Air](http://angular-air.com/) (of course ;-)), [Parent Programming Podcast](https://twitter.com/parentprogpod), [React Podcast](http://reactpodcast.com/), [FiveJS](https://fivejs.codeschool.com/), and [Software Engineering Radio](http://www.se-radio.net/) (at the recommendation from @AimeeKnight). So yeah, I'm into podcasts and twitter :-) I also watch conference talks and go to conferences :-)

> What off-topics are you interested in (IT-related, besides the work-related specifics)?

I'm not certain I understand what you're asking here. Most of my personal IT-related stuff relates to my work-related stuff. This is why I can justify working on open source stuff (because we use the tools at work) or hangout on twitter regularly (because I ask questions elicit feedback on ideas I'm considering with work). I do have egghead.io stuff that I work on, but you could argue that's work-related too :-)

> What tools do you use regularly (E-Reader, Tweetdeck, Medium, Feedkly, Pocket Casts)?

My laptop. Medium. twitter.com (I've tried tweetdeck several times and just haven't gotten into it). I subscribe to several newsletters: [JavaScript Weekly](http://javascriptweekly.com/), [Node Weekly](http://nodeweekly.com/), [ng-newsletter](http://www.ng-newsletter.com/), [React.js Newsletter](http://reactjsnewsletter.com/), [HTML Weekly](http://html5weekly.com/). And I follow each of these on twitter as well.

> Do you allocate some time of your day for consuming information, or you just do it on the fly?

I mostly do it on the fly. Could probably be more productive if I allocated time every few hours or something.

> Do you have a specific routine/process for information consumption?

Not really... Just kinda consume it. I follow people/things that I find tweet things interesting fairly regularly.

Hope that's helpful! Thanks for the question!

**Comment by benoror** [comment]
Thanks for answering!

**Comment by kentcdodds** [comment]
Update on my podcasts:

I try to catch every episode of:

- [JavaScriptAir](http://javascriptair.com)
- [JavaScript Jabber](http://devchat.tv/js-jabber/)
- [Adventures in Angular](http://devchat.tv/adventures-in-angular)
- [Angular Air](http://angular-air.com/)
- [Parent Programming Podcast](https://twitter.com/parentprogpod)
- [React Podcast](http://reactpodcast.com/)
- [FiveJS](https://fivejs.codeschool.com/)

I catch episodes I think look interesting of:

- [Software Engineering Radio](http://www.se-radio.net/)
- [The Changelog](https://changelog.com/) (just started listening)
- [Planet Money](http://www.npr.org/podcasts/510289/planet-money) (non dev, very interesting)
- [Wide Teams](http://www.wideteams.com/) (just started listening)

I just realized that I listen to a lot of podcasts...

**Comment by benoror** [comment]
Great addition Kent, thanks! :clap: 

BTW, how do you find time to listen so many podcasts? Do you listen while working/coding? Or only during your spare time?

Cheers!

**Comment by kentcdodds** [comment]
Funny you should ask :-) 

<a href="https://twitter.com/kentcdodds/status/685103376468545537"><img width="650" alt="screen shot 2016-01-07 at 4 11 05 pm" src="https://cloud.githubusercontent.com/assets/1500684/12185616/50ba4fbe-b559-11e5-8861-2747580f0362.png"></a>

**Comment by kentcdodds** [comment]
Another update on podcasts:

I try to catch every episode of:

- [JavaScriptAir](http://javascriptair.com)
- [3 minutes with Kent](https://www.briefs.fm/3-minutes-with-kent)
- [JavaScript Jabber](http://devchat.tv/js-jabber/)
- [Adventures in Angular](http://devchat.tv/adventures-in-angular)
- [Angular Air](http://angular-air.com/)
- [React Podcast](http://reactpodcast.com/)
- [FiveJS](https://fivejs.codeschool.com/)
- [Codecation Updates](https://www.briefs.fm/codecation-updates)

I catch episodes I think look interesting of:

- [Software Engineering Radio](http://www.se-radio.net/)
- [ShopTalk](http://shoptalkshow.com/)
- [Software Engineering Daily](http://softwareengineeringdaily.com/)
- [The Changelog](https://changelog.com/)
- [Planet Money](http://www.npr.org/podcasts/510289/planet-money) (non dev, very interesting)
- [Wide Teams](http://www.wideteams.com/) (haven't listened to many yet...)
- [Stuff You Should Know](http://www.stuffyoushouldknow.com/) (just started listening)

**Comment by mattferderer** [comment]
Your podcast list looks very similar to mine. I'm therefore suggesting you check out [.Net Rocks](http://www.dotnetrocks.com/) for their Geek Out labeled podcasts where they explain & share the current status of non dev & very interesting topics such as reusable space craft, modern agriculture techniques, space elevators, smart homes, quantum computer.
