### ISSUE TITLE
What do you make in USD?

### ISSUE THREAD

**Issue by f00Dev** [kentcdodds/ama#173]
Hello Kent,

What do you make in the industry, and do you feel that your salary commensurate's with your experience?

Thanks!

**Comment by kentcdodds** [comment]
Hi @f00Dev!
Right now I make $135,000 + equity, benefits, etc. from my fulltime job at PayPal. Some things I read or hear make me feel like I'm not paid enough, others make me feel like I'm paid more than I should be. Ultimately, what I'm paid allows me to take care of my family, live comfortably, and allow my wife to stay at home with the children rather than work. So I'm pretty happy with the arrangement.
Thanks for asking.

**Comment by niallobrien** [comment]
Can you clarify if this is based on working on-site or remote? Thanks in advance.

**Comment by kentcdodds** [comment]
I work full time remote from my home in Utah.
