### ISSUE TITLE
Review a presentation topic

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#175]
Hello Kent!
I was wondering, is it ok to ask someone to review the content of a slides which is to be presented as a talk.
Especially if it involves teaching some stuff.
Thanks,
Anirudh Modi

**Comment by kentcdodds** [comment]
Totally appropriate. I get feedback on stuff I do all the time.

**Comment by kentcdodds** [comment]
To take it a step further. Sometimes I'll practice in front of my computer and record myself and my screen (I use [screenflow](http://www.telestream.net/screenflow/), but you may be able to use QuickTime or some other software). Then I'll send a link to the recording on YouTube to some people to get some feedback.

**Comment by anirudh-modi** [comment]
Thanks for the answer and time 😄 , Would it be possible for you to review my slides? anytime according to your time?

**Comment by kentcdodds** [comment]
Sure! Feel free to post the link and I'll give it a look when I can. When are you presenting?

**Comment by anirudh-modi** [comment]
Thanks alot!! 😄 😄 
The slides are half done, I will finish by tommorow and post the link.
I have not submitted, but If selected I will be presenting on 15/16 sept in INDIA.

It will be my first time, so wanted to know would the content of my slides is correct or not, and also,

**Comment by anirudh-modi** [comment]
http://slides.com/anirudhmodi/prototype-dont-take-them-from-granted#/

Here is few of the point which I have collected on the topic, It is still in draft, but an early feedback can help me alot, to dig more into the topic.

**Comment by anirudh-modi** [comment]
@kentcdodds I am done with the slides, do give me a feedback, whenever you look into it. 😄

**Comment by kentcdodds** [comment]
Here's some feedback
- I like that you start with expectations. "What's this about/not about." This will help people not be disappointed and focus on what you're saying rather than trying to guess what you may or may not talk about.
- [`Object.getPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) is actually part of ES 5.1
- Your colors look nice, but make sure they have good enough [color contrast for a11y](http://colorsafe.co/).
- There are a lot of words on your slides. This makes your slides easy to consume from my standpoint (because I'm not watching you talk), but when you give your talk people will be more consumed by reading the words on your slides than listening to you speak. You could turn your words into a blogpost and put fewer key words on the slides (like basically titles and subtitles... so like, 8 words per slide max). If you need to have notes for yourself that's fine. Put them on notecards or have your phone handy :)
- For the diagram slides, I hope you can use your mouse of have a laser pointer. It's a sizeable diagram and people could easily get lost as you're explaining it.
- It's good that you have different colors for new lines on the diagram :+1:

You end with an explanation for the "why" of prototype in JavaScript, but I think that doing this _first_ would actually be a bit better. It will help keep people interested in what you're saying. For more info, look into [start with why](https://www.startwithwhy.com/) 👍 

Great talk! Good luck on it!

**Comment by anirudh-modi** [comment]
Thank you so much for your valuable time and such a detailed feedback, it would really help me to improve. 😊

Unfortunately, the topic was too basic and not much crowd would have been attracted to it. However, I would improve with your input and try to present it in my office.

**Comment by kentcdodds** [comment]
Oh, sorry I didn't get it to you earlier. I thought you weren't talking until September.

**Comment by anirudh-modi** [comment]
Ya, it is still until september, I submitted the proposal earlier, however, they rejected it, so there was no delay from you side 😄

**Comment by kentcdodds** [comment]
Ah! Keep submitting it! You can do it!

**Comment by anirudh-modi** [comment]
Thanks alot!! 😄
Hope I didn't took much of your time 😃
