### ISSUE TITLE
What are your three desert island Movies & Books?

### ISSUE THREAD

**Issue by willbuck** [kentcdodds/ama#18]
If you could only watch 3 movies the rest of your life, what would they be?

Same question but which 3 books would you read?

Brief explanations of why are great too! Thanks Kent!

**Comment by kentcdodds** [comment]
> If you could only watch 3 movies the rest of your life, what would they be?

Hmmm... Well, to preface this, I don't watch anything more hard core than PG movies (crazy, I know). We can save that for another question if you're interested as to why. So I think I'd probably need to do something funny, another thing that's action, and another one that's feel good/inspiring.

Funny: [Finding Nemo](http://www.imdb.com/video/imdb/vi2687214105/)
Action: Huh... Can't really think of anything right now... But I like [Big Hero 6](http://www.imdb.com/video/imdb/vi3839339545?ref_=ttvi_vi_imdb_5) and that's sort of actionish... Maybe Star Wars?
Feel Good: [Radio](http://www.imdb.com/video/screenplay/vi3232694553/)

> Same question but which 3 books would you read?

Well, [I'm religious](http://www.mormon.org/me/1J5N) and nothing matters more to me than developing and maintaining a relationship with Heavenly Father. So the first one's easy:

1. Standard works: (Includes [The Bibile](https://www.lds.org/scriptures/bible?lang=eng) Old and New Testament, [Book of Mormon](https://www.lds.org/scriptures/bofm?lang=eng), [Doctrine and Covenants](https://www.lds.org/scriptures/dc-testament?lang=eng), and [Pearl of Great Price](https://www.lds.org/scriptures/pgp?lang=eng), as well as [Study Helps](https://www.lds.org/scriptures/study-helps?lang=eng)).

The second and third though... Hmmm...

2. [The Simarillion](https://en.wikipedia.org/wiki/The_Silmarillion) because it takes forever to read and it's hard to understand, so it'd keep me busy for a while. I only got 50 pages into it when I tried years ago. So much stuff...
3. Probably a book that expands on [this blogpost](http://www.pleated-jeans.com/2009/05/04/how-to-get-off-a-deserted-island/) ;-)

Thanks for the question!
