### ISSUE TITLE
JS Air suggestion

### ISSUE THREAD

**Issue by vanthiyathevan** [kentcdodds/ama#186]
I don't know where to ask this, so I'll ask it here.
I really enjoy the discussions on JS Air. Especially the discussions on the `Typed JavaScript with TypeScript and Flow` and `Typed Functional Programming in JavaScript`. One thing I like to suggest is, There seem to be a lot of questions from community and I know the guests can't answer all of those. As some one who doesn't watch the cast live, I would like to know what kind of questions the community was asking.  So why not pick some questions and put them in the site as `Some questions that didn't get answered`. May be even have the guests answer those questions when they get time.

**Comment by kentcdodds** [comment]
Hi @vanthiyathevan!
I'm glad that you enjoy the show! Thanks for the feedback too (by the way, you can submit feedback at [jsair.io/feedback](https://jsair.io/feedback)).

I like your idea, but I don't think that I'll be able to do it myself. I don't know whether you know, but I don't get paid to do the show and I just do it on my spare time. So everything that I do comes at the expense of something else in my personal life. All of the questions are publicly available by searching Twitter for the hashtag [#jsAirQuestion](https://twitter.com/search?f=tweets&vertical=default&q=%23jsAirQuestion&src=typd) and I do encourage the guests to go look over there if we don't have time to get to all of the questions. Hopefully that's helpful because it's all I can really do right now.

Thanks again for the feedback, and I hope you continue to enjoy the show!
