### ISSUE TITLE
What tools and methodologies do you use for (1) bookmarking links and (2) marking links for later processing (like to read, to download, etc)?

### ISSUE THREAD

**Issue by flybayer** [kentcdodds/ama#192]
I believe I've seen elsewhere that if something can be done within a couple minutes, you do it immediately. That could apply to the second part of this question, but I'm more interested in what you do when it'll take longer than a few minutes or isn't possible in your current situation (ex: while browsing on mobile, you find an app you want to download on your computer).

Thanks you for your answer!

**Comment by kentcdodds** [comment]
Hy @flybayer,
Thanks for the question. Yeah, normally I just try to address it immediately if I can. Otherwise I put it into my https://inbox.google.com. That's pretty much where I organize everything. I use reminders pretty heavily, and try to reach inbox 0 which is really hard sometimes, but keeps me on top of things :)

Thanks again for the question!

**Comment by flybayer** [comment]
Thanks Kent. So you also use Google Inbox for bookmarking links or do you use the browser's built in bookmarking feature? Or do you not bookmark links at all and rely on searching Google/Twitter?

**Comment by kentcdodds** [comment]
I don't use the browser's bookmarking feature for that. I'll just create a reminder with the link I need to look at.

**Comment by flybayer** [comment]
Ok, I think I didn't explain my original question well enough 😯 I apologize for that. 

My original question consists of two distinct but related questions:


1. What's your process for bookmarking links for later use/recall such as when you discover a tool or technology you don't currently need but know you will in the near future or read an exceptional article you want to read periodically? The typical things people use browser bookmarking for. I'm especially interested in how you bookmark links from mobile. I currently use Chrome browser bookmarks on desktop, but on mobile, when I find something I want to save, I'll add it to Pocket with a tag 'bookmark-this' which I'll later bookmark on desktop. I'm getting weary of this method plus the lack of tagging capability in Chrome. 

2. What's your process for queuing up links for the future for reading or taking some action on? Such as when you discover a blog post essay you don't have time to read at the moment. Some of these things you may end up bookmarking for later recall because you like it so well. 


You basically answered #2, but I'm still wondering about #1 😄

**Comment by kentcdodds** [comment]
Ah, thanks for the clarification

1. I don't often have things that I want to come back to on a regular basis. But even if I did, I'd probably still use Google Inbox Reminders to do it and have it reoccurring. And if it's just a one-time thing, a Google Inbox Reminder is still the way I do that :)
2. Yeah, still use Google Inbox Reminders :)

I really like Google Inbox Reminders because the things I need to do are really in my face and I make sure I get them done. And if I can't get them done now, I can tell Google Inbox to hide it for a while.

Hope that answers your questions :)
