### ISSUE TITLE
What's your all-time favorite book?

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/ama#2]
In any category. And why?

**Comment by kentcdodds** [comment]
I read the [Book of Mormon](https://en.wikipedia.org/wiki/Book_of_Mormon) every day. I think that makes it my favorite. I also spend plenty of time reading and cross referencing the [Bible](https://en.wikipedia.org/wiki/Bible).

I love these books because the things I learn from them make me a better person when I apply the principles I learn from them. I truly believe what they say and feel like I develop a stronger relationship with my Heavenly Father and Savior Jesus Christ when I learn about them and try to emulate their example.

I'd be happy to answer honest, non-contentious further questions about my faith :-)
