### ISSUE TITLE
How are you part of so many organisations?

### ISSUE THREAD

**Issue by siddharthkp** [kentcdodds/ama#206]
AKA tips for devs fresh into open source

**Comment by kentcdodds** [comment]
Hi @siddharthkp,
Thanks for the interesting question! Hmm... Well, here's how I got into each org:

- angular: I participated a bit in the batarang project
- firebase: I was the first ever "torch bearer" (I invented the term). Basically like a Google Developer Expert but for Firebase. I think they changed the name of it, and did away with the program (because now they're part of Google and can use _real_ GDEs).
- webpack: I help maintain the `json-loader`
- expressjs: I made a contribution to the body-parser at one point or something...
- gonimbly: I took over angular-formly when it was still under the `gonimbly` org.
- gdgutah: I was a co-organizer for a while.
- github-beta: I participated in some program github was trying out. Can't remember what. They reached out to me about it for some reason.
- airpair: I wrote a blog post for them. They asked me to after my talk at ng-conf.
- SLC-JS-Learners: I gave a talk at their meetup and they added me to the org
- formly-js: I created this one as the official home for angular-formly and related projects
- AngularAir: I create this one as the official home for the AngularAir podcast website and related repos
- ReactWeek: I participated in this event (a week long training with Ryan Florence)
- forms-js: I teamed up with several other forms implementations for angular to build a single forms solution that worked across frameworks. Never really happened though.
- AngularClass: They invited me to be a part of the org because ... I'm not sure why actually :) But they're friends of mine.
- commitizen: I contributed a bit to commitizen and contributed a plugin.
- eggheadio-github: I created this one as part of my [How to Contribute to an Open Source Project on GitHub](http://kcd.im/pull-request) course on egghead.io
- javascriptair: I created this org as the official home for the JavaScriptAir podcast website and related repos.
- facebookincubator: I participated in the closed developer preview of create-react-app

Most of these invitations came from me contributing or people inviting me because I'm active in the community. For more on this, you might appreciate [this talk](https://kentcdodds.com/talks/#zero-to-60-in-software-development:-how-to-jumpstart-your-career). Thanks!
