### ISSUE TITLE
What do you use for CSS-IN-JS lately?

### ISSUE THREAD

**Issue by kitze** [kentcdodds/ama#208]
I know you're a huge fan of aphrodite, but I see that you're also dabbling with glamor lately. What are your thoughts on aphrodite vs. glamor vs. styled-components?

**Comment by sapegin** [comment]
And vs. jss too ;-)

**Comment by kitze** [comment]
I saw him tweeting about glamor and styled-components, so that's why I specifically mentioned those 2 libraries.

**Comment by kentcdodds** [comment]
Hi @kitze,

I'm still using aphrodite. I started using [aphrodisiac](https://github.com/cssinjs/aphrodisiac) (jss implementation of a aphrodite-like API), but I didn't really see much benefit personally and I don't like the term `aphrodisiac`...

I haven't given glamor or styled-components a really solid look, so I can't speak to those very well. But they look interesting. I think the biggest thing styled-components has against it is the inability to lint or minify the string (syntax or otherwise). Not something tooling couldn't get around or anything, but as far as I know, that tooling does not yet exist.

Glamor sounds kinda cool. But I really like that my styling library is decoupled from React for some weird reason... :)

**Comment by kitze** [comment]
Cool, thanks!

**Comment by kentcdodds** [comment]
I saw this and thought I'd just post an update that my personal favorite now is [`glamor`](https://github.com/threepointone/glamor) + [`glamorous`](https://github.com/paypal/glamorous) :smile:

**Comment by kitze** [comment]
@kentcdodds oh how the tables have turned 🙈

**Comment by kentcdodds** [comment]
> Glamor sounds kinda cool. But I really like that my styling library is decoupled from React for some weird reason... :)

Yeah, I was totally wrong about this. First off, glamor has nothing to do with react. Secondly, I created glamorous which is _totally_ coupled to React. And I don't have any problem with that :wink:
