### ISSUE TITLE
Semantic-release and human-written change logs

### ISSUE THREAD

**Issue by sapegin** [kentcdodds/ama#212]
Hi Kent!

I wrote [an article](https://medium.com/@sapegin/automate-npm-releases-with-semantic-release-and-human-written-change-logs-2adb1dce487#.c5zn98d73) on how I write handmade changelogs with semantic-release. I used to [dislike the tool](http://blog.sapegin.me/all/egghead) but then I found that it could do exactly what I want ;-)

I would appreciate any feedback.

**Comment by kentcdodds** [comment]
Hi @sapegin,
Thanks for reaching out to me. I actually did see your review of egghead courses a while back and meant to respond but forgot.

> One thing I don’t like about this course: Kent suggests semantic-release to automate releases. I wouldn’t recommend it because it makes project maintainer life harder: it doesn’t allow you to group breaking changes and write human readable change logs. And I think it’s too opinionated for such course.

On grouping breaking changes, that's actually trivial. Create a branch (called `next` for example) and make PRs to that branch. When you're ready to release all the breaking changes, merge that to `master`. It's a tiny bit more work, but arguably a better way to go about it anyway and definitely worth the automation.

On human readable change logs, we'll just have to disagree on that one. I like that the changelog shows what changed and if someone wants to see more details they can click on the link to the PR.

And I guess that's my feedback on your tool. I'm glad that you found something that works for you, but I wouldn't use it because what I said already ;-)

Thanks!
