### ISSUE TITLE
Any tips for making npm-cli tools?

### ISSUE THREAD

**Issue by amandeepmittal** [kentcdodds/ama#217]
Hi Kent,

I recently started pushing modules on npm regisrty for learning purposes and am looking to find a something on how to develop a command line interface tool using NodeJS? I have created few npm modules and published on them the npm registry but they lack a proper CLI interface due to my lack of knowledge of CLI intergration.

Btw, I loved "How to write an Open Source JavaScript course" on egghead.io and still using Travis  CI and Semantics for my side projects.

**Comment by kentcdodds** [comment]
Hey @amandeepmittal!
Thanks for reaching out to me! I'm glad you enjoyed my course :D 

I've made a few CLIs. Probably my simplest recent one is [split-guide](https://github.com/kentcdodds/split-guide). You'll see the CLI code lives [here](https://github.com/kentcdodds/split-guide/blob/fb4b2a2ebc1fb8c3c010c2af1318861b8bb1bb13/src/bin/index.js). And I tell npm to use the transpiled version of that file as the `bin` in the `package.json` [here](https://github.com/kentcdodds/split-guide/blob/fb4b2a2ebc1fb8c3c010c2af1318861b8bb1bb13/package.json#L12-L14) where the `key` in that object is the name of the binary (so what you'd type in the terminal to use the CLI) and the `value` is the path in the package where the binary is located (in my case it's in the `dist` directory which I transpile to with [babel](http://babeljs.io/) [here](https://github.com/kentcdodds/split-guide/blob/fb4b2a2ebc1fb8c3c010c2af1318861b8bb1bb13/package-scripts.js#L13) (I'm using [`p-s`](https://github.com/kentcdodds/p-s) for my scripts).

With that configuration, when `npm` (or [`yarn`](https://yarnpkg.com/)) installs my package, it will create a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) to that file in the `node_modules/.bin` directory (or, if it's globally installed, it'll put it wherever your global packages are loaded into your `$PATH`). For locally installed packages, you can use those binaries with your npm scripts (this behavior is kinda explained [here in the official docs](https://docs.npmjs.com/misc/scripts#path)).

So, for example, because I have setup `split-guide` like that, I can use it in my [`react-jest-workshop`](https://github.com/kentcdodds/react-jest-workshop) [here](https://github.com/kentcdodds/react-jest-workshop/blob/c43eaa13eb0ca203d7ed2b771b85e61ca5e539b0/package.json#L12).

Let's look again at [the actual `bin` file](https://github.com/kentcdodds/split-guide/blob/master/src/bin/index.js) itself now. There are a few things to note:

1. [The first line](https://github.com/kentcdodds/split-guide/blob/fb4b2a2ebc1fb8c3c010c2af1318861b8bb1bb13/src/bin/index.js#L1) has `#!/usr/bin/env node`. This is called a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) which effectively tells the system to run the script with node.
2. Pretty much the rest of the file is configuring `yargs` to accept the arguments I want it to. There are actually countless npm packages to help parse `process.argv

**Comment by kentcdodds** [comment]
Whoops! Sorry, I wasn't finished... Stand by...

**Comment by kentcdodds** [comment]
Alrighty, I updated it! I hope this helps!

**Comment by kentcdodds** [comment]
FYI to people watching the repo, I formalized this answer as a blogpost [here](https://medium.com/@kentcdodds/tips-for-making-a-cli-based-tool-with-node-9903255c2a3b)

**Comment by amandeepmittal** [comment]
@kentcdodds thank you so much for turning it into a blog post. I'll be definitely following with you on twitter after I am done.
