### ISSUE TITLE
What is/are your favorite web development conference(s)?

### ISSUE THREAD

**Issue by arahansen** [kentcdodds/ama#220]
I know you're a big fan of web development conferences. I was wondering what some of your favorite conferences are and what you like about them?

I personally am interested participating in deep discussions with great developers, learning new ways of approaching problems we face as web developers, and learning what's just around the corner for web technology (libraries, browser features, etc).

**Comment by kentcdodds** [comment]
Hey @arahansen,
Soooo..... Hmmm... This is hard... So instead of sorting them, I'll give you my top 6 favorite conferences I've been to (in no particular order) :)

- [The Strange Loop](http://www.thestrangeloop.com/)
- [ng-conf](https://www.ng-conf.org/)
- [Forward 4 Web Summit](https://forwardjs.com/)
- [Fluent Conf](https://conferences.oreilly.com/fluent/fl-ca)
- [React Conf](http://conf.reactjs.org/)
- [React Rally](http://www.reactrally.com/)

What do I like about them... Hmmm... My favorite conferences allow for lots of opportunities to hang out with friends and make new ones. For example, The Strange Loop had the coolest pre-party ever and that was one of my favorite parts of the conference (it's also incredibly diverse and full of a lot of interesting people). ng-conf is similar. Tons of fun and opportunities to let loose with new and old friends.

Another important thing for me at conferences is the quality of the talks. I really enjoy high quality talks. I especially enjoy them if we're all in a single track. React Rally, React Conf, and ng-conf are all this way and I really love it. This way, everyone's having the same experience and it makes things feel more unified.

I hope that's helpful to you!
