### ISSUE TITLE
Library Publishing ... The right tool for the right job

### ISSUE THREAD

**Issue by d3viant0ne** [kentcdodds/ama#221]
I've built the beginnings of an extension library for angular/material2 which adds some components that I know they aren't going to put in that lib. Some for the cool factor and some useful for work, none of which exist in material or are slated for material2.

> If you were going to release something like that, would you bundle a release package with Webpack or Rollup? 

The development time activities and demo app run on Webpack, that's a given. Rollup's umd output and the heavy tree shaking make it an attractive option for the release package to npm. 

I'm really on the fence with this one, I love Webpack and it's certainly capable but I keep going back to using the right tool for the right job. Webpack runs all of my web applications, definitely the best tool for that job, hands down. When publishing a library for public consumption, you want the module as lean as possible & imo readability of the published code matters more so than that of a web application. 

I keep going back to the feeling that when it comes to publishing a lib, Rollup is the right tool.

Before I go through the trouble of combining those technologies, I am curious which way you would go with it.

**Comment by kentcdodds** [comment]
Hey @d3viant0ne!
Sounds like a fun lib! This is a great question. I've struggled with this in the past. Some of my browser libs are pretty small and it seems a shame to include an entire webpack runtime in my UMD build just so I can have more than one module. So I've tried Rollup before and I've got some thoughts on it.

First off I should mention that most of the time, I only use webpack for the UMD build, which I discourage people from using and only really use so people can toy around with the lib via something like jsbin or codepen before using it in a serious project that will be using the CommonJS files (which I transpile with Babel). (Anyone wanting to learn more about how to do this can see [my egghead course](http://kcd.im/write-oss) or my upcoming [Frontend Masters course](http://kcd.im/fem-oss)). So with that assumption in mind, you can consider the resulting bundle size to be almost irrelevant. Anyone using the UMD build quite likely doesn't care a whole lot about perf and is building a toy or MVP. People building serious projects will use the CommonJS files (which have nothing to do with webpack/rollup).

One thing to note is that there could be cases where the UMD build is what your CommonJS users will use as well (for example, if you're using some special loaders to inline some CSS or something). In those cases, performance and size will matter quite a bit and this is definitely something to consider.

Ok, with all that said, here's what I have to say about which to use. Rollup has a bunch of benefits with regards to size and performance. On top of what webpack can do, it can inline modules into a single closure which saves quite a bit on the size of the resulting bundle as well as the actual runtime performance of the library (how much this makes a difference is really subjective). It is definitely missing some features that webpack has (but I'm not aware of any that would matter in the context of your lib) and doesn't have near the community around it that webpack has. So there's that...

I tried out Rollup on [`match-sorter`](https://github.com/kentcdodds/match-sorter). It took a while to figure out how the config worked. `<rant>`Honestly, people say a webpack config is confusing... But I struggled just as much with Rollup so IDK... Lol and people have said webpack's docs were garbage, but even webpack v1's docs were better than Rollup's.`</rant>`

One thing that you'll notice is I have some [custom magic](https://github.com/kentcdodds/match-sorter/blob/605e1594bbf4ff0dd6d0c58cf941ad4c98550f92/src/index.js#L243-L254) to make the UMD work. In particular, this is so the global that's exported is the `matchSorter` function itself rather than `{default: matchSorter}`. This problem is not unique to Rollup. I believe that I could actually get around that by doing what I did recently in [`rtl-css-js`](https://github.com/kentcdodds/rtl-css-js) [here](https://github.com/kentcdodds/rtl-css-js/blob/3105a62495012c23e5dd58038ea8ed197f2de20c/src/webpack-entry.js). (PRs welcome)

So honestly, if you can wrangle your way around the config, don't worry about not having as much of a community, actually need the UMD to be small, and don't have some advanced use-cases that Rollup makes difficult, I would probably go with Rollup. Otherwise, I like webpack and most of the time the added weight isn't much or relevant (because again, I almost always use the CommonJS version of the lib anyway).

I hope this is helpful! Good luck!
