### ISSUE TITLE
Callstack.io Knowledge

### ISSUE THREAD

**Issue by kfurness** [kentcdodds/ama#222]
Hello Kent,

You have recently retweeted a tweet from Mike Grabowski  for Callstack.io that mentioned that they were looking for a developer who is willing to relocate to Poland. I made the assumption that if you reposted it, they must be a pretty good company. I have applied for the position, and before my husband and I continue to consider relocating to Poland, I would love to hear your thoughts on anything you know about Callstack.io.  Am I correct in thinking that if you retweeted their tweet, you would recommend them as a workplace? I will be graduating from a coding camp in the next few weeks, and I would love to be affiliated with a company that has great mentors and developers that I can learn lots from. Any thoughts would be really helpful, and I appreciate you taking the time!

Best,
Kelly Furness

**Comment by kentcdodds** [comment]
Hi @kfurness,
Thanks for reaching out to me!

> I made the assumption that if you reposted it, they must be a pretty good company

I can sort-of remember that tweet. But honestly I don't know much/anything about callstack.io. I trust @1Marc a lot so I was happy to retweet it (maybe he knows more and can help answer questions about it). Often I'll retweet when people are hiring whether I know much about the company just because I figure it can't hurt to let people know about opportunities that they can investigate for themselves. So, sorry that I can't really tell you much about or vouch for callstack.io.

> I will be graduating from a coding camp in the next few weeks

Congratulations! 🎉 🎊

> I would love to be affiliated with a company that has great mentors and developers that I can learn lots from

This sounds like great qualities to look for in your first job. If you tweet out that you're looking for a good company to work for, send me the link and I'll retweet it. I'd love to help :)

Good luck!
