### ISSUE TITLE
Simpler Javascript

### ISSUE THREAD

**Issue by Tahseenm** [kentcdodds/ama#225]
All existing browsers have vanished.
Given a fresh start, you are asked to design javascript again in 10 days. You must pick all features from the current JS (2017). 
Which features, Objects, methods do you keep ? 

The goal is to make JS simple. You can finally get rid of the semicolon.

**Comment by Tahseenm** [comment]
P.S Kyle Simpson won't complain as everyone developer won't remember the past except you

**Comment by kentcdodds** [comment]
Hi @Tahseenm,
Wow! That's a pretty unique and awesome thing to think about! You know, I've actually been thinking about this kind of thing a lot recently as I just attended my first TC39 meeting representing PayPal. It was overwhelming as I realized how difficult the job is! We have to be considerate of use cases that others have and we may not. For example, I'm not really interested in decorators, but other people really like them and feel like they're useful, so I need to consider and try to represent those use cases.

Honestly, I don't know whether I'm qualified to answer this kind of a question. I'm still trying to work out my own opinions with things. I can tell you some of the things that I like and don't like about JavaScript. But removing some features I don't use personally may restrict people from doing the things that make them more productive. Also, I'm still pretty new to all of this so there's a lot of use cases that I've not bumped into.

But if I could ignore that for a moment, here are some of the things I _might_ do (in no significant order):

- Goodbye ASI and semicolons! And the two places where omitting semicolons today causes unexpected behavior will be syntax errors.
- Indentation will be 2 spaces. Anything else is a syntax error.
- We would only have template literals. No need to have three ways to define a string.
- There will only be `var` (following `let` semantics) and `const`
- I would remove `class` and `this`. They can be nice, but if we never had them in the first place, we could accomplish everything we need. I think people would apply more FP principles if we didn't have OO constructs.
- I think I'd even remove prototypical inheritance. It's not something I find myself doing _ever_, I think it causes more confusion than anything else.
- I think that I would have included Observables as the only async primitive. They're pretty confusing, but heck, so are promises. If Observables were the only thing, we'd all learn them really well and they're pretty darn powerful. Despite my inexperience with Observables, I think they can cover all the same use cases as other async styles.
- I'd definitely keep the built-in objects like `Math`, `Number` (which would would not have Floating point issues), `Array`, `Object`, `Intl`, etc.
- I would have started with a module system (both static and dynamic/async). And instead of `import foo from 'foo'` it would read: `from 'foo' import foo` so you could get nice autocomplete as you're typing.
- `Array` would definitely be full-featured from the beginning (`map`, `reduce`, etc.)
- There would be no `use strict`, everything would be `strict` :)
- Perhaps, surprisingly, I would keep `eval`. I've used it for legit use cases before and it's really handy.
- I'm not certain whether I'd add static typing. Maybe optional? I dunno....

I'm sure there are more things that I left out. But in general, I'd like to reduce the amount of area for bikeshedding and reduce the overlap of features.

Much of the stuff mentioned above would probably be a really bad idea to actually do. But, like I said, I'm still pretty new at this and I'm still figuring out use cases and stuff :)

Thanks for the mental exercise :)
