### ISSUE TITLE
How can I Focus on Learning one Skill at a time?

### ISSUE THREAD

**Issue by AhmedAbdulrahman** [kentcdodds/ama#226]
Hi @kentcdodds 

Well, I have a problem of focusing on perhaps too many things at a time. For instance, when I am learning a new _**Frontend or Backend Framework.**_ By the time I have read few tutorials on the Internet, I start to take interest in another language and leave the first one :( and this cycle goes on endlessly.

What I do is that i read the tutorial for a few hours and then switch to some other new topic. **This way I want to learn too many skills in a short period of time.**

How to focus on one skill at a time? How to learn one thing at a time without being diverted and moving on to other project?

Kind Regards,

**Comment by kentcdodds** [comment]
Hey @AhmedAbdulrahman,
Honestly, I'm not sure how to help. I often get distracted as well. What I can say though is that instead of picking a technology to learn about and read tutorials or watch videos about, start with the problem. Come up with a problem you want to solve. Then identify the tools you need to solve the problem. The learning comes from creating the solution. It's also really important that you're motivated by solving the problem. If it's not really important to you, it'll be easier for you to get distracted.

I hope that's helpful! Good luck!
