### ISSUE TITLE
Getting into programming

### ISSUE THREAD

**Issue by cynicaldevil** [kentcdodds/ama#227]
Hi,
I want to know how you got your start in this field. Did you start young, or did you get into it after you landed your first job?
Also, if anyone else's reading this, I would love to hear their stories too, if its alright!

**Comment by RandomlyKnighted** [comment]
Hi @cynicaldevil I knew in high school I wanted to go into something with computers. My senior year I took an Intro to Programming classes just to see what it entailed. of course we were using QBASIC so I really didn't get a feel for what it was like to program in modern langauges. That same year I fixed several teachers computers so I knew I was interested in that as well. I ended up getting a degree in Computer Information Systems so that I could go either route. After graduating from college I worked in the IT Department for a local school system. It was alright, but I really was only using about 2% of what I learned in college. During this time basically all of my free time was spent contributing to open source projects and so I knew that's more of what to do. I have since started a new job as a Web Developer for a local software company and I'm much happier. Feel free to reach out to me if you have any specific questions about my story.

**Comment by kentcdodds** [comment]
Hey @cynicaldevil,
Actually, this was my very first question! You can read all about it here: #1 :)

Let me know if you have any specific questions :)

**Comment by cynicaldevil** [comment]
Thanks @RandomlyKnighted and @kentcdodds for your answers! I really appreciate it! 
@kentcdodds you were working for alianza when you answered the question, but work for PayPal now. Maybe you could elaborate on what happened between then and now?  :)

**Comment by kentcdodds** [comment]
I added another comment to #1. Thanks for asking!
