### ISSUE TITLE
Feedback on ES7 decorators/css-constructor

### ISSUE THREAD

**Issue by siddharthkp** [kentcdodds/ama#231]
Context: https://twitter.com/kentcdodds/status/807990533389832192

Feedback on [css-constructor💄](https://github.com/siddharthkp/css-constructor)

**Comment by kentcdodds** [comment]
Hey @siddharthkp,
Thanks for asking. So some cool things:
1. I like that it's really small
2. Seems to have many of the features necessary for doing CSSinJS which is great
3. Being editable in dev tools is really nice. Aphrodite's `!important` makes that experience frustrating.

Other feedback/thoughts:

Honestly, I have misgivings around classes in general. I'm just not a huge fan of them. I prefer the straightforward nature of functions and closures (and the module pattern). So all the extra fanciness that goes on with classes (like decorators) I just don't really like. It seems pretty indirect to me.

Another thing is, I prefer JS objects for my CSS rather than a CSS string. Using regular JS means that I can share things across components simply using JS modules, I can do normal JavaScript things, linting/typing works great, syntax highlighting, etc.

Specifically on your solution, it appears that you're only applying the styles to the root element, but most of the time I need to style many elements in the component's tree. If there's no way to do that, then that's a definite deal breaker for me.

In any case, I appreciate that everyone has their own preferred way of developing and I'm glad you've developed something to suite your (and others') needs. Good luck to you!

**Comment by siddharthkp** [comment]
Thanks for the feedback! 

1. I've heard this one before, the decorator pattern has pushed some people away despite the syntactical sugar. I am wondering if an alternate syntax without decorators make sense. [it's here](https://github.com/siddharthkp/css-constructor/issues/1)

2. I completely agree. Even though there are ways to [lint](https://github.com/styled-components/stylelint-processor-styled-components) and [highlight](https://github.com/gandm/language-babel), it's extra work to set them up.

3. There is a way :) check out [this example](https://github.com/siddharthkp/css-constructor/blob/master/example/hello.js). It's a very css way of doing it

Thanks again for the feedback! Really helps :)
