### ISSUE TITLE
Redux alternative

### ISSUE THREAD

**Issue by k15a** [kentcdodds/ama#232]
Hey Kent,

I recently saw your [Twitter poll about redux / flux](https://twitter.com/kentcdodds/status/806986998359662592). Can you recommend some redux / flux alternatives without a huge complexity? I have heard about MobX but I don't feel that it is less complex.

**Comment by kentcdodds** [comment]
Hi @k15a,
Honestly, I haven't had much of a chance to build a full app on my own and been in control of stuff like state management. The app I currently work in uses Redux and it feels a little complex sometimes which is why I posted that poll. I've seen MobX, but I'm not convinced it's any simpler.

If I were starting a project today, I would stick with React state for as long as possible before moving to Redux. I'm pretty confident that I could make it pretty far...

**Comment by vitkarpov** [comment]
@k15a hey, I've been thinking about it for myself and made [a little demo](https://github.com/vitkarpov/noscript-react-demo/blob/master/app.js). Check out the interface, which has: router, models (with async requesting from your REST API and batch), actions and pure react layout.

It implements flux architecture. Right now I'm working on making alpha version of the thing.

What exactly you don't like about Redux? For me, I just want to make a solid, but simple framework around React to make Single Page Applications, otherwise you have to gather a bunch of  tools together.
