### ISSUE TITLE
Integration tests on routes that render views

### ISSUE THREAD

**Issue by DavidTamakloe** [kentcdodds/ama#236]
Hi. i'm developing an app with a node.js backend (express.js) and i'm looking to write integration tests for this. i see a lot of blog posts and tutorials testing routes were the backend responds with json data that's pretty straightforward to assert. But i'm not sure what the best approach is when the route responds by rendering a view. Any recommendations for this?

**Comment by kentcdodds** [comment]
Hi @DavidTamakloe,
That's a good question! And it's a tough one to answer. Honestly, I think that most of the time if the response comes back as a success and has basically the right stuff in it then that's all you really need to assert for an integration test. Unit tests can take care of details. Otherwise they can get kinda finicky and you spend a lot of time updating tests when you refactor (something you definitely don't want to do).

All that said, if there's something you KNOW CANNOT break or you will be in big trouble (like a "Checkout" button in an online retail application), then you can go ahead and assert your heart out that the button is there and that things are wired up for it to work (which would require an actual browser to get a real sense of that). At this point you're getting more into E2E tests. I actually gave a talk about the importance of the different types of testing that you might find interesting: [What We Can Learn About Testing From The Wheel - Kent C. Dodds (Ignite Fluent 2016)](https://youtu.be/Da9wfQ0frGA?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf)

If you do want to go down that road, then I'd definitely recommend looking into [Cypress.io](https://www.cypress.io/). It seems like by far the best solution for browser driving E2E testing that I've seen. Really impressive stuff going on there.

Best of luck to you!

**Comment by vitkarpov** [comment]
> But i'm not sure what the best approach is when the route responds by rendering a view.

If you will, I'd consider [jest](https://facebook.github.io/jest/). It's a tool (I'm sure you've heard about it) that allows to get snapshots first and then compare with them. Snapshots actually could be anything: json or html, I suppose that the latter is feasible while testing "routes respond by rendering a view".

Hope this helps, happy testing! ;)

**Comment by kentcdodds** [comment]
I was thinking about suggesting snapshots. But if it's a full page of rendered HTML, you're going to have to update the snapshots anytime you make any change at all and that could lead you to ignoring the results altogether (which would make the test nothing but annoying). [I LOVE Jest](https://medium.com/@kentcdodds/migrating-to-jest-881f75366e7e), but use snapshots with care :)

**Comment by DavidTamakloe** [comment]
Thanks @vitkarpov and @kentcdodds. Very helpful information. i found [this stackoverflow answer](http://stackoverflow.com/questions/29695714/mocha-how-to-test-express-rendered-views) that suggested using [cheerio.js ](https://cheerio.js.org/) very interesting as well (in case anyone else stumbles upon this).

Ultimately i think i'm gonna go with just checking the response status and then use unit tests for the details as @kentcdodds suggested. The prospect of constantly updating tests is slightly discomforting :\

Thanks again for the responses :)
