### ISSUE TITLE
For someone aspiring to join big companies, any tips? ( asking for a friend 😋 )

### ISSUE THREAD

**Issue by thisguychris** [kentcdodds/ama#237]
He is really curious how the facebook / paypal interview works.  Please do share what is allowed to share.

**Comment by vitkarpov** [comment]
I'm in the middle of my training right now, and can say that [Cracking the Coding Interview](https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782850) is a must-read for sure: describes the basic theory, has **a lot** of problems to solve and also some tips about the process and beyond.

Also, take a look at [Helen's speech on React.js conf](https://www.youtube.com/watch?v=N233T0epWTs), it's about Facebook (actually relates to any such IT company).

**Comment by kentcdodds** [comment]
Hi @thisguychris,
Thanks for asking. My experience with Facebook and PayPal interviews was really practical. I didn't have to do anything too wild like reverse a binary tree or anything like that. It was more like: "implement a flatten function" or "how would you architect something like pinterest so that the UI doesn't jump around all over as the pictures load" etc. Really practical stuff. Helen's talk at React conf (as @vitkarpov mentioned) is great.

Honestly, most of what's helped me I've discussed before in my talk ["Zero to 60 in software development: How to jumpstart your career"](https://youtu.be/-qPh6I2hfjw). I hope that's helpful.

Best of luck to you!
