### ISSUE TITLE
What to focus in 2017

### ISSUE THREAD

**Issue by Rolando-Barbella** [kentcdodds/ama#238]
I know is a classic but, what are the most important things you would like to focus this year as an engineer or at least for the first few months as we don't know what's gonna happen with technology. Any library, frame work, tool or even a language?

Thank you ;)

**Comment by kentcdodds** [comment]
Hi @Rolando-Barbella,
Thanks for asking! Hmmm... What do I want to focus on? Honestly, I want to work on my skills as a teacher. I really enjoy teaching and giving workshops, so I want to give more workshops and get more practice. I'm also interested in learning more about ASTs and fundamental JavaScript concepts. I should probably also learn a new language. If I were to, I think I'd choose something like Reason or Rust... Or something like that. I may actually try something that can compile to Web Assembly because I think that would be pretty awesome to learn how to do.

As you can see, I don't really have much of a plan. Maybe I should... 🤔 
Oh, and I definitely plan on doing more with my family this year. Which is why I've taken some time off from conferences :)

**Comment by Rolando-Barbella** [comment]
Hey, thanks for the answer! really helpful 👍  the teaching thing sounds cool and off course finding the balance between work and family also very important!

I heard great things about Reason or Rust, are you not planning to learn Elm? or you already know it?

Thanks again! :o)

**Comment by kentcdodds** [comment]
Mostly there's only so much time I have available and Elm is a little lower on my list of interest. :)
