### ISSUE TITLE
TypeScript personal overview

### ISSUE THREAD

**Issue by Attrash-Islam** [kentcdodds/ama#247]
Hi kent,
I respect your knowledge on the JavaScript community (You're my hero :wink:), and I'd like to know in details your thoughts about TypeScript compared with ES6. Which one you prefer? Do you think that TypeScript is a good path for the JavaScript community? Why you are not using it at all?

Thanks

**Comment by Attrash-Islam** [comment]
TypeScript includes the ES6. Yes, but my purpose is to distinguish TypeScript special type system from other features that already exist in ES6.

Maybe I'm not clear, but the question is: Does TypeScript type-system is better or not for JavaScript community and projects?

I see some great devs embrace the language with all they got, and some other greats like: Eric eliot sticking to ES6, and almost denying type-system advantages specially for js world

**Comment by vitkarpov** [comment]
God, I'm sorry but I'm confused.

From the one hand you have ES6, it's the next ECMAScript standart and has a lot of new features and language constructions. From the other hand you have TypeScript which is NOT part of language or any future standart as far as I know.

It's just an instrument which brings types into JS, such the same goal could solve well-writen jsdoc, but with TypeScript or Flow development experience is more convenient because of compile-time checks.

According to this logic ES6 and TypeScript are parallel stories, aren't they? Where am I wrong?

**Comment by Attrash-Islam** [comment]
You're not wrong at all :)

**Comment by vitkarpov** [comment]
> Does TypeScript type-system is better or not for JavaScript community and projects

Sorry, now I get the question :)

**Comment by Attrash-Islam** [comment]
Absolutely. :)

**Comment by kentcdodds** [comment]
Hi @Attrash-Islam,

I answered this via my podcast: https://www.briefs.fm/3-minutes-with-kent/35

Thanks for the question!

**Comment by Attrash-Islam** [comment]
Will watch it. Thanks
