### ISSUE TITLE
Generators or Async-Await?

### ISSUE THREAD

**Issue by alayek** [kentcdodds/ama#248]
There have been so many styles to write asynchronous code. From callbacks to promises to generators, and now async-await.

Lately, it's been mostly about Generators and Async-Await pattern. I find it easier to use async-await pattern.

For some reason, I didn't like the Generator syntax.

But I am only a novice. And I want more informed input.

In particular, where should I use async-await over generators and vice-versa? Is there any pitfall or trap that I should know about?

I know that at the moment Babel compiles async-await to generators via stage-3 presets. That is, until Node 8 drops.

**Comment by kentcdodds** [comment]
Hey @alayek,
Thanks for the question. It took a while, but after I got a strong hold on Promises I was pretty sold. And things have improved a lot since the early days of promises. When my co-worker added async/await to our codebase, I was skeptical. But after a little while with it, I really love it. I'm not a huge fan of try/catch all over my code, but when you want to forward along error handling to your caller (so you don't care to catch errors) then it's not bad at all. Also, if you don't care about failures, you can avoid try/catch pretty easily with:

```javascript
const result = await getUser().catch(() => {}) // swallow the error
```

Having a solid understanding of promises really helps you when writing async/await code. I'm a fan of async/await for sure. It's also great when writing tests that are asynchronous.

As for generators, I've yet to really use them much beyond teaching. I think eventually I really see their value, but right now I've not really felt like I needed them.

So to answer your question:

> In particular, where should I use async-await over generators and vice-versa? Is there any pitfall or trap that I should know about?

I'd pretty much always use promises/async-await over generators, but that's mostly because I'm not used to generators and haven't yet realized their full potential.
