### ISSUE TITLE
Mocha and Chai

### ISSUE THREAD

**Issue by webbjordy** [kentcdodds/ama#252]
I came across your video on Mocha and Chai on Egghead. I'm just starting off on my coding learning and my role at my company has moved from support to QA.

I've been doing all manual testing so far and I want to start automating. Do you have any more basic videos on Mocha? I love your teaching style. If not, do you know of any good places I an find some?

I'm also interested in any other automated testing video courses or tutorials.

Thank you so much.

**Comment by kentcdodds** [comment]
Hey @webbjordy,
Thanks for reaching out to me! I'm glad to hear that you're working on automating testing! It's more fun and you'll be much more productive!

It's interesting that you would reach out to me right now, because I'm currently working on a [testing workshop](https://github.com/kentcdodds/testing-workshop) where I'll cover [some interesting topics](https://github.com/kentcdodds/testing-workshop/issues/1). It'll be a while before that's really ready. I'm preparing it for some a Frontend Masters workshop I'm giving in April. You may also be interested in [my 5 minute talk](https://youtu.be/Da9wfQ0frGA?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) about the different types of testing.

Based on that outline I linked above, you'll see that I'm planning on using [Jest](http://facebook.github.io/jest) for unit and integration testing. I have some videos about that [here](http://kcd.im/egghead-jest). And you'll notice that I'm planning on using [Cypress](https://www.cypress.io/) for E2E testing. You'll get a lot more bang for your buck doing E2E testing so you may want to start there and automate some of your more important flows. If you can get into the early access program for Cypress, I recommend you give it a look. It uses Mocha and Chai under the hood and it has fantastic documentation. It's a really incredible tool. I don't think I'll ever use Selenium again.

Best of luck to you!
