### ISSUE TITLE
Any tips or advice setting up Webpack 2 to work with an AngularJS app?

### ISSUE THREAD

**Issue by CBedzz** [kentcdodds/ama#256]
Kent, any advice on setting up Webpack 2 to worth in an AngularJS 1.5 or 1.6 (component based) app?  Just wondering if there are any pitfalls or things to look out for (I have read a little about ng-annotate to not screw up $scope dependency injection upon minification).  Also is there a structural reason that I see so many boilerplate starters using gulp instead of NPM?  

Thanks for all your great content and passion for teaching!

**Comment by kentcdodds** [comment]
Hi @CBedzz,
Thanks for reaching out to me :) To be honest, the last time I used Angular was back in Angular 1.3 days. So I haven't used Angular in quite a while and the landscape has changed quite a bit since then. I don't know of many boilerplates available ([I don't use boilerplates I don't create myself](https://www.briefs.fm/3-minutes-with-kent/25)), but I can definitely tell you that you'll want `ng-annotate`.

I tried to find the most recent angular + webpack repo I have and came up with [this one](https://github.com/formly-js/angular-formly-website). There are a few things I'm doing in there that I'd definitely not recommend anymore. Sorry I'm not able to be more helpful. Good luck!

**Comment by CBedzz** [comment]
Thanks for the response.  I appreciate the help.

**Comment by CBedzz** [comment]
Think you might have posted the wrong link.  Instead of a boilerplate, it's your Angular formly repository.

**Comment by kentcdodds** [comment]
Want linking to a boilerplate. Just an example app.
