### ISSUE TITLE
Your first tech presentation?

### ISSUE THREAD

**Issue by CBedzz** [kentcdodds/ama#258]
Just wondering what your first non-school tech presentation was (meetup, work learning group, conference?), the topic, how you got involved in doing it, and anything else you remember about your first experience speaking publicly?

**Comment by kentcdodds** [comment]
Hi @CBedzz!
Thanks for the question. I remember my first talk really well. I heard about this thing called "meet-ups" while I was in school at BYU. I thought it'd be a great way to meet more people who liked programming in JavaScript. So I found [the UtahJS meetup page](https://www.meetup.com/UtahJS-Orem-Meetup) and saw that there was one coming up soon and they still didn't have a speaker. I had been working on a library that I thought was pretty neat and thought I could give a talk about it. It's funny, because I don't think that I'd ever personally seen a meet-up talk before, so I didn't have any idea what I should plan for. I don't know what I was thinking.

Anyway, I reached out to @jergason on the meetup page (I'm "A former member"... not sure what's up there):

<img width="519" alt="screen shot 2017-03-04 at 6 43 34 am" src="https://cloud.githubusercontent.com/assets/1500684/23579214/f4c1bf8c-00a5-11e7-8cf0-7ff2abd02da2.png">

I had about 3 weeks to prepare so I created [an app](http://kentcdodds.github.io/genie/workshop/) and walked through that app for my talk. I can't remember it going terrible, so I guess it went ok! I polished the talk up a little bit and it became my first out-of-state conference talk as well. Find out more about it here: ["Improving UX with GenieJS"](https://kentcdodds.com/talks/#improving-ux-with-geniejs)

Thanks for asking. Always fun to reminisce!
