### ISSUE TITLE
Angular and Webpack (spread one angular Module through the whole app)

### ISSUE THREAD

**Issue by ondrasak** [kentcdodds/ama#26]
I have watched your tutorials about 'Angular and Webpack’ (egghead.io). I like the way how you spread one angular Module through the whole app by 'module.exports' function. But is it good practise? If one part of app dependents on (for example) 'angular-moment' .. In your solution I need to type this dependency to 'app' ngModule even if only one component of the app needs it.

**Comment by kentcdodds** [comment]
This is true. Technically, it doesn't make a difference because angular's `$injector` is a single global context. In my application, I actually have a module for every state of the application and then the `'app'` module depends on all of the "state modules." This allows me to have dependencies closer to where they're being used. I also have a concept of `ngCommon` modules that contain common things throughout a state and the state's children.

My app structure and directory structure are influenced heavily by [this gist](https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346) by @ryanflorence and @mzabriskie. I have to do some pretty interesting things with webpack to get this to work in an angular context... Maybe one day I'll have a blogpost on this or I'll continue to work on the webpack series.

I recently had [a failed refactor](https://twitter.com/kentcdodds/status/627190104637898752) which attempted to create a single angular module per component (directive/service/etc.) in my app. It was going to be awesome because I could sort-of make my Angular 1 stuff like React or Angular 2 where you have to explicitly list your dependencies (a big win for several reasons). Unfortunately, I got to around 500 modules and noticed bootstrapping time took upwards of 5 seconds 😵 Not sure what the problem was, but it was totally not worth it in any case.

Hope this is helpful! I'm sorry I can't be more helpful!

**Comment by benoror** [comment]
FWIW my recent refactor was mainly based on this ideas:

http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/

I basically have several files per module, let's say **home** module:

* **index.js**: Entry point for CommonJS. Load dependencies for the module.
* **home.routes.js**: Route(s)
* **home.controller.js**: Component's controller (ES6 class)
* **home.html**: Template
* **home.css**: Stylesheet

As for directives I still use functions as suggested in the article

**Comment by kentcdodds** [comment]
:+1: thanks @benoror!

**Comment by ondrasak** [comment]
Thanks @kentcdodds @benoror !
