### ISSUE TITLE
Do you use a boilerplate generator for bootstrapping new repos?

### ISSUE THREAD

**Issue by petermbenjamin** [kentcdodds/ama#261]
Hey @kentcdodds ,

Thank you for your time and effort that you give back to the community.
Sorry if this question has been asked already, I did my best to search through GitHub Issues, but didn't find anything relevant to my question.

### My Question
I find that when I'm creating new repos and I tend to need the same repo file structure:
- README with badges, install section, usage section, API section, license section
- LICENSE
- A package.json with deps and npm scripts I use across my node projects.
- A bunch of dotfiles (e.g. `.editorconfig`)

Current, I have a boilerplate repo that I clone to bootstrap new projects, but I'm wondering if you have, use, or know of a better, configurable approach than cloning (maybe a yeoman generator?).

**Comment by kentcdodds** [comment]
Hi! Thanks for the question! You're totally right. Every project has many things in common. If you look at a few of my projects I've made in the last year or so, you'll notice that they all look suspiciously similar. That's because I do actually have a yeoman generator for this stuff. I've mentioned before that I don't use generators that I haven't built myself, so this one is by me and pretty specific to my preferences. I don't plan on making it easy for other people to use, but you can feel free to fork it!

[generator-kcd-oss](https://github.com/kentcdodds/generator-kcd-oss)

Give it a try and then build on top of it or make your own. It's totally worth the effort!
