### ISSUE TITLE
What features of javascript are implemented using syntactic sugar?

### ISSUE THREAD

**Issue by fvictorio** [kentcdodds/ama#262]
Also, is this an implementation decision or does the standard dictates/recommends something in that regard?

Thanks!

**Comment by kentcdodds** [comment]
Hey @fvictorio!
Thanks for the question. It's kind of a hard one to answer. AFAIK, under the hood, when these features are implemented, they don't actually transpile it to existing syntax and _then_ run it, but they actually support the new syntax. This means that they can optimize things based on the semantics of the features.

Because of this, I'm going to assume that you're asking about whether we can implement these things using different syntax or if they're impossible to implement without the browser engine supporting the syntax. Most of ES6 features can be implemented via existing syntax and polyfills. Two exceptions are [Proxies](https://github.com/lukehoban/es6features#proxies) and [Symbols](https://github.com/lukehoban/es6features#symbols).

A good way to know whether we can get close to a feature via transpilation is to pop open the [babel repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=&playground=true) and paste in some code. If it leaves it alone then that means you either need a polyfill for it or it cannot be implemented with different syntax.

I hope that's helpful!

**Comment by fvictorio** [comment]
Thanks for the answer!
