### ISSUE TITLE
Should I speak, teach, or write about topics that are already very explored?

### ISSUE THREAD

**Issue by Emilios1995** [kentcdodds/ama#269]
When I'm about to write a blog post or something, I always check if there's existing similar material, and if there is, I become discouraged.
Should that discourage me? How do you deal with that?

For example you recently did a workshop about testing in JS which ended up helping many people, including me.
But how didn't the existing quantity of material about that topic discourage from doing it?

**Comment by kentcdodds** [comment]
Hey @Emilios1995!
Thanks for the question :) As you indicated, I've produced a ton of content that has already been covered in depth by many other sources. I don't think about it like: "This content already exists, so my addition wont be valuable." I think of it more like: "I want to get really good at this thing, so I'll learn it well enough that I can teach it to other people." At least, that's one of the reasons that I make so much educational material. And it's a wildly successful way for me to learn things and improve my skills.

Another thing to remember is that you can prepare content and deliver it in a different way or reach different people than other existing material out there.

And things are changing so quickly in the world of JavaScript in particular that even content that _I_ have produced in the past is starting to lose relevance so I could reproduce my own content and it could _still_ be valuable.

**One really important note:** It's totally fine to learn from and reference other material when you're preparing your own. And you should **definitely** give credit where it's due. For example, for my testing workshop, I used an app that was developed by Thinkster and I first _asked_ them if it was ok that I use the app, and I then had a whole slide dedicated to crediting them for the original work. I've also taken other people's workshops, forked them and added more content or changed things and delivered those. I always ask the author if that's ok, and there's _always_ a big thank you slide for those and a big note in the repo README indicating the source of the original workshop.

I think it's just a matter of getting over the feeling that you cannot contribute any more just because content exists already. You _can_ contribute more! Good luck!
