### ISSUE TITLE
Being concerned about personal ability

### ISSUE THREAD

**Issue by TheOdd** [kentcdodds/ama#270]
Hi, I just finished listening to the episode of The Changelog that you were on about going into contributing to Open Source projects. It was really insightful and think you did a great job on that. If you're able to and have time, I wanted to ask for your opinion on my current situation when it comes to contributing.

I'm 15 years old right now and have been learning to program for about 4 years now. It's all been very informal and self-taught through various resources online and recently some books, too. I really love coding and making things and I know that it's what I'm going to do for my career. I mostly work in C++ and have e basics down and an understanding of a lot of more advanced concepts in the language as well. I've also messed around a bit with JavaScript, Java, Python, and some others.

Whenever I see projects on GitHub that are supposedly easy for beginners to get into, a lot of the time I don't know how to solve that bug. It's worrying and frankly a bit scary to me that I wouldn't be able to complete something that has a 'beginner' tag on it.

All in all, I wanted to ask if I should be worrying about that kind of thing. I know that I still have a long time ahead of me to learn, but at the same time I feel almost like I've peaked and don't know where to go. There's only so much documentation and formal instructions for beginning in a language and since I can't get a job or really do a huge project, I'm not sure where to go next.

I am going to a summer program in San Francisco for coding which will be amazing. I was fortunate enough to be one of the 15 accepted high schoolers to attend it this year and I recommend you checking it out to see what I mean. I think the URL is joinhorizons.com

Sorry for rambling on, but my final point is just whether or not I should be worried. Things get into my head sometimes and it's nice to get an outside perspective.

Thanks, Owen Hines

**Comment by kentcdodds** [comment]
Hi @TheOdd!
Thanks for reaching out to me and expressing your feelings! First off, know that you're not alone! A LOT of people have trouble with "beginners" issues on GitHub. You need to understand that these "good for beginners" issues are relative. The people putting these labels on these issues often think that they're easy, but only because they're way familiar with the project. So they may actually not be good for beginners at all. This is why I prefer to avoid using labels like "for beginners" or "easy" and prefer to use something like: "starter" which doesn't give any indication that it's easy or that "anyone can do it" kind of thing, but is more of: "out of all the issues, this is best for people just getting started." Definitely doesn't mean that it's easy!

Aside from that, don't get discouraged! As a 15 year old programmer, you seem to have gotten some great experience, but never forget that there's _always_ more for you to learn. You may be expert in the things you've worked on so far, but there's still a _ton_ more that you need to learn to contribute to other things. And that's totally fine! That's one of my favorite parts of programming! It never gets boring (unless of course you work for Elon Musk at a [certain company](https://boringcompany.com/) :wink:).

I think that you would really benefit from hearing my story. I gave a talk about it at ForwardJS last year: [Zero to 60 in Software Development: How to Jumpstart Your Career](https://youtu.be/-qPh6I2hfjw?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf). I talk about how I've learned and progressed in my learning and career. There are a number of other questions here in my AMA that you could search through and maybe get more tips as well.

Good luck on your summer program! Things like that are special! Take advantage of that opportunity!

To answer your ultimate question: No, don't be worried. Just keep building.

Good luck!
