### ISSUE TITLE
Best way to relax before an (onsite) interview?

### ISSUE THREAD

**Issue by Sherman-Chen** [kentcdodds/ama#273]
Hi Kent!

My name is Sherman, and I'm a big fan of all the work you do for the JS and Software community! 👍 

I want to ask what you think is the best way to relax / "not freak yourself out" before an interview (whether onsite or over the phone, etc)? And also how you personally reconcile impostor syndrome, i.e. not feeling good enough for the role you're interviewing for, or even currently working at?  

Crawled through some of your other AMAs, watched your Zero to 60 talk, and like the rest of your content enjoyed and found it immensely useful and encouraging 😃 Definitely agree that we have to always keep learning 😸 

Best,
Sherman

**Comment by kentcdodds** [comment]
Hi @Sherman-Chen!

Thanks for the question. I'm always nervous before I interview. I think one of the scariest parts of the interviewing process is uncertainty. That's why I find the best thing for me has been to learn as much as I can about the interview process. I don't try to steal any interview questions or anything, but getting an idea of the kinds of things that I'll be asked is a really helpful way to reduce the uncertainty with the interview.

Good luck!

**Comment by Sherman-Chen** [comment]
Thanks @kentcdodds !! appreciate the advice as always 😄
