### ISSUE TITLE
why put .opt-in and .opt-out in .gitignore?

### ISSUE THREAD

**Issue by luftywiranda13** [kentcdodds/ama#274]
I still don't get it..

why don't just add `#` to comment them out? maybe you have a strong reason behind it?

**Comment by kentcdodds** [comment]
Hi @luftywiranda13,
For those who don't know, `.opt-in` and `.opt-out` are for [`opt-cli`](https://www.npmjs.com/package/opt-cli) which I use in [my githooks](https://github.com/kentcdodds/generator-kcd-oss/blob/6733cef54dcfd0307dd816e468210ae947c6a80a/generators/app/templates/_package.json#L10). It allows me to share git hooks, and have an easy way for new people to contribute (not run the hooks) and maintainers to enable them to keep things stable. I like to have the git hooks, but I want to lower the barrier to contributing. That's why :)

Thanks for the question!
