### ISSUE TITLE
How do you keep up?

### ISSUE THREAD

**Issue by joelseq** [kentcdodds/ama#277]
With the rapidly growing and changing front-end JS scene, how do you manage to stay ahead of the curve and learn everything? How do front-end masters such as yourself learn all the new tools and techniques that you teach in your workshops since your workshops are very comprehensive and require you to constantly be mastering new tech?

**Comment by joelseq** [comment]
Also I just wanted to add, huge fan of all your OSS work and your tweets! ❤️

**Comment by kentcdodds** [comment]
Hi @joelseq! Thanks for the question!

I talk about it a bit in #17. Also, my talk ["Zero to 60 in software development: How to jumpstart your career"](https://kentcdodds.com/talks/#zero-to-60-in-software-development:-how-to-jumpstart-your-career) gives some insight into how I learn stuff.

To sum up, I put pressure on myself to learn as much as I can about a subject by committing myself to teaching about it. Whether it's a work/meetup/conference talk or workshop, or a podcast, or whatever, by giving myself a commitment to teach/share it, I force myself to learn it really well. I've had a handful of talks that I proposed before I personally knew how to do it. _It's really important to note though that you never propose something that you don't know is possible!_

Also, when I'm making educational material, folks are really friendly and willing to help out so I get a lot of feedback from library authors and other folks because they know that what I'm doing is going to help people use their project (and potentially free up some of their time so they don't have to teach it to as many people themselves!).

Really, I probably don't know as much as you think I do. I just share 99% of the stuff I know 😄 

I hope that's helpful! Best of luck to you!

**Comment by joelseq** [comment]
Thank you so much for all your hard work and your reply! Keep doing what you're doing! 😄
