### ISSUE TITLE
Do you use React Storybook?

### ISSUE THREAD

**Issue by sirJconny** [kentcdodds/ama#278]
Hello Kent!

Just wondering if you use React Storybook to isolate the creation of your components. I know you have been using a lot of codesandbox lately to do prototyping, but why or why not do you use React Storybook?

Thanks!

**Comment by kentcdodds** [comment]
Hi @sirJconny!
Yes, I've used and LOVE React Storybook. I use it on [my personal website](https://github.com/kentcdodds/kentcdodds.com) to make development faster and it's awesome. I tried and failed to convince my coworkers to use it in our work project. So anyway, yeah, I think it's great.

Why I like Codesandbox is because it's so much easier to spin up and share with others. That's pretty much it :) I think this is a case for the right tool for the job. Both tools are awesome. Just a matter of using the tool that makes the most sense for the context.

Good luck!

**Comment by sirJconny** [comment]
Thanks for such a quick response!
