### ISSUE TITLE
To use a CSS framework or to not...

### ISSUE THREAD

**Issue by jonmajorc** [kentcdodds/ama#281]
Hello Kent,

Do you find yourself running to a css framework (Bootstrap, semantic, etc.) out the gate when building a project, or do you use some light weight tools instead and build home grown solutions when a problem occurs? I feel it is easy to grab a "kitchen sink" CSS framework, but seems like the possible better solution is bringing things in when you most need it... 

So what css tools do you always use to help you with development, and why or why not do you use CSS frameworks that are out there?

Thanks! 😃

**Comment by kentcdodds** [comment]
Hi @jonmajorc! Thanks for the question!

Honestly, I don't build a whole ton of apps, so every time it's something different. Really depends though. If I'm serious about the project, then I'll probably add a framework just because design is not really my thing. If I have a designer then I normally wont.

Sorry that's not really a helpful answer! Good luck!
