### ISSUE TITLE
State mutation

### ISSUE THREAD

**Issue by Ronolibert** [kentcdodds/ama#282]
Many people often say to not mutate state (using concat on arrays instead of push, object.assign) because it can cause silent bugs in the future that would be hard to trace. But do you have an example of a situation like this happening?

**Comment by piq9117** [comment]
```
const state = [1,2,3];

// .push mutates the array.
state.push("surprise! I'm a string")

const total = state
  .reduce((acc, num) => acc + num, 0)

// "6surprise! I'm a string"
```
Thats a contrived example but hopefully it cleared up some stuff.. 😄

**Comment by kentcdodds** [comment]
Hi @Ronolibert,

Thanks for the question! I honestly can't think of a specific example right now. But I've definitely fell victim to the problems many times in the past. I remember experiencing this kind of thing with Backbone Models a lot. The biggest thing with mutation is that it's really hard to answer the question: "When did this property change to this value." When you use immutability it's much easier to determine that because you can trace back to where the object was created fairly easily. Immutability also just changes the way you code in a way that makes your code easier to follow. When code's easier to follow, there are fewer bugs :smile:

I hope that's helpful!
