### ISSUE TITLE
What's it like being on a team with Kent?

### ISSUE THREAD

**Issue by ajwhite** [kentcdodds/ama#284]
If I was on your team at work, what would it be like working with you? 

I'm familiar with your presence and involvement on the public facing side, but what about during the other hours of the day with your team and coworkers? (I read #61 where you described your remote work, but slightly different topic)

Some leading questions to point things in the direction that I'm (and surely others!) are curious about:

- What parts of PayPal do you work on, and what is your role within that team?
- What do members on the team come to you for? What's your "go-to" quality?
- Was there excitement when you initially joined the team given your presence in the community? 
- What types of decisions do you make during a typical sprint/cycle?

Pretty self-reflective questions! But I've always been curious what it would be like working people of interest that I follow in the community.

Cheers 😃

**Comment by kentcdodds** [comment]
Hey @ajwhite! Thanks for the question! And thanks for the leading questions. I wasn't sure what to say, but this will help out!

> What parts of PayPal do you work on, and what is your role within that team?

I work on the Peer-to-Peer (P2P) payments team. Specifically I'm the team lead over Cross-border payments team. We're all fullstack. Our backend is node that talks to downstream services to do the actual transactions. Our frontend is React. If you go to [this page](https://www.paypal.com/myaccount/transfer), that's the first page to ever taste the sweet [glamorous](https://github.com/paypal/glamorous) koolaid.

That is, assuming you're seeing a page that looks like this:

<img width="1038" alt="screen shot 2017-07-07 at 3 45 01 pm" src="https://user-images.githubusercontent.com/1500684/27978163-4aa14886-632b-11e7-8dff-e29e1ef5203b.png">

Because not everyone's seeing the new stuff yet :wink:

> What do members on the team come to you for? What's your "go-to" quality?

Well, I literally just barely got a question like this from one of my teammates: "Could you direct me to some documents/code how this mock thing works?"

Really common types of things I get questions for:

1. Testing: Jest, what to test, where to test, how to test, general questions, etc.
2. Build Chain: Webpack related stuff mostly
3. React: Mostly general questions... Though I've fielded a fair amount of glamorous questions recently ;)

Other than that, there are some domain-specific questions I get asked a bit as well.

> Was there excitement when you initially joined the team given your presence in the community?

There was. Honestly, I think it wasn't entirely warranted and that was a tad bit disappointing at first. I don't like churning out code for new features. I like to take my time building the right thing, taking care of tech debt and that sort of thing. So I can sometimes take awhile to get things done.

> What types of decisions do you make during a typical sprint/cycle?

Hmmm... I'm not sure actually. I was going to say I sometimes have to decide between finishing my story or helping my team finish theirs, or working on something else that I think is more important. I normally prioritize helping my team, then work on what's more important (like tech-dept type stuff mostly), then work on my stories :smile:

One other thing that I might add is if you worked with me, you may be surprised at how much time I spend experimenting/learning/trying new things. It may make you frustrated, or you may love it.

Anyway, I hope that's informative and helpful. Cheers!
