### ISSUE TITLE
What is differce between SD v/s SE?

### ISSUE THREAD

**Issue by jsroyal** [kentcdodds/ama#287]
SD -> Software Developer
SE -> Software Engineer
Job profile in IT firm?

**Comment by kentcdodds** [comment]
Hi @jsroyal,

I don't think of them as any different. Some people think that it's insulting to "real" engineers to call ourselves "Software Engineers" because they go to school for years and actually build physical things with what they learn and stuff. But I don't really agree...

At the end of the day, I don't really care either way 🙃
