### ISSUE TITLE
First biggest codebase contribution

### ISSUE THREAD

**Issue by piq9117** [kentcdodds/ama#289]
Hello @kentcdodds! Thanks for the immediate response on twitter. Also, thanks for the videos (egghead & javascriptAir), and blog posts. 

My question is *What was your first biggest OSS codebase contribution?*
I have follow up questions but i think they got answered here https://github.com/kentcdodds/ama/issues/264 & https://github.com/kentcdodds/ama/issues/270

Basically, I was scrolling through the vscode issues and I saw beginner labels, and I got so excited thinking that I may be able to contribute to a gigantic codebase. Started running the project, running the test. Long story short, the project was massive. There's no way I can comprehend it. Now, I'm rethinking my career as a programmer and maybe considering gardening. 😢 

Joking aside, how did you face these challenges when you first encountered them?

Thanks!

**Comment by kentcdodds** [comment]
Hi @piq9117,

Thanks for the questions!

> What was your first biggest OSS codebase contribution?

My first ever contribution was a JavaDoc typo fix in the Play Framework [here](https://github.com/playframework/playframework/pull/616).

But my first substantial OSS contribution after that... 🤔 hmmm... Whelp, if you look at my github history, I think the next biggest OSS contribution was my own library called [genie](https://github.com/kentcdodds/genie). Later I contributed to bigger libraries... There was [this one](https://github.com/dmcquay/node-apac/commit/c53f746277e240dbb2693d70d11ce87f022c01f5) to `node-apac`. But the first OSS contribution I made to a project you've probably heard of was [this one](https://github.com/expressjs/express/pull/2013) to `express`, but it was also pretty minimal.... Hmmm... Still searching...

Ah yes, the next significant contribution to a relatively bigish project was [this one](https://github.com/formly-js/angular-formly/pull/17) to `angular-formly`. Actually, after a while I started contributing more and more to that project until eventually I was given ownership over it and I ran it quite successfully for two years or so. It became pretty popular. Actually, it wasn't until recently that [`glamorous` overtook it in downloads](http://npmcharts.com/compare/angular-formly,glamorous). Still getting quite a few. But I'm no longer maintaining it (nobody is). It's still helping a lot of people build forms with Angular 1.

I did eventually start landing [commits in Angular 1](https://github.com/angular/angular.js/commits/master?author=kentcdodds). But I wasn't like, rewriting the compiler or anything. In fact, most of them are docs/test changes. The only code change I made was [this one](https://github.com/angular/angular.js/commit/79577c5d316c7bf0204d7d1747ddc5b15bfe2955) (it was a single line and a few tests).

So anyway, I guess what I'm saying is that while I feel pretty confident that I could eventually figure out my way through most big repositories written in JavaScript, it's taken me a TON of time getting used to things. Don't let issues labeled "good for beginners" throw you off. I really don't like those labels. It makes it sound like: "This issue is good for a new developer" but that's not at all what it means. What it really means is: "This issue is among the easiest of all the issues we have" which is quite different.

If gardening makes you happier, then go for it, but if you enjoy coding, don't think that experiencing difficulty contributing to a large complex codebase is an indication that you're in the wrong industry. I'm sure you're just fine! :smile:

Good luck!

**Comment by piq9117** [comment]
Thank you!
