### ISSUE TITLE
What's your typical build configuration for javascript projects look like?

### ISSUE THREAD

**Issue by adammlr** [kentcdodds/ama#29]
JS/ESLint, grunt/gulp, WebPack, uglify/minify, string replacement, deployment process, etc...

**Comment by kentcdodds** [comment]
That's a big question. I'll give you a simple answer, and then you can ask me to expound if you like. I use webpack for all of my projects. With that I use the eslint-loader, babel-loader, (ng-annotate-loader for angular projects), and a bunch of other loaders. I use the built-in Uglify plugin and various other plugins for deployment. Webpack is pretty much magical.

I have no need for grunt/gulp in any of my projects anymore. Webpack + npm scripts does it all for me.

I use Karma as my test runner. I use mocha as my framework, and chai.expect for my assertions.

If I'm deploying an app, I use SnapCI for that (see [this](https://medium.com/continuous-delivery/continuous-delivery-3a4a55baa58a)) and deploy to AWS with CloudFlare (for my work project). If it's a library, I'm moving from snap back to TravisCI again because of [a conversation I had today](https://youtu.be/g6y3DnhkjrI) with @boennemann about [semantic-release](https://github.com/semantic-release/semantic-release). For those I deploy to gh-pages. But I've tried out [surge](https://surge.sh/) and it's pretty slick.

I use protractor for e2e tests on my app at work (it's an angular app).

I'm in the process of creating an egghead.io series on how to write an open source library which will touch on all of these things and more (see [this](https://twitter.com/kentcdodds/status/633867162696847365)).

**Comment by kentcdodds** [comment]
I can't reiterate enough how simple and powerful Webpack has made my build processes. It's a beast to configure in the first place, but once you've figured out how to do it, it's incredibly powerful. I highly recommend it for apps and libraries.

**Comment by adammlr** [comment]
Do you happen to know of an angular project somewhere in github that has all of this configuration (minus deployment) set up for a good starting point? :-)

**Comment by kentcdodds** [comment]
Well... For my libraries, I'm currently using something I made called [kcd-common-tools](https://github.com/kentcdodds/kcd-common-tools) which is a totally half-baked WIP tool that sort-of uses this. I use this for several of my libraries including [api-check](https://github.com/kentcdodds/api-check) and [angular-formly](https://github.com/formly-js/angular-formly).

You might look back a few tags on those libraries to see what they looked like before I added kcd-common-tools. That might give you a good idea of an example setup.
