### ISSUE TITLE
What was your reasons for making this AMA? How was it so far? 

### ISSUE THREAD

**Issue by morajabi** [kentcdodds/ama#292]

**Comment by kentcdodds** [comment]
Hi @morajabi,

I made this AMA because I receive a LOT of questions by email/twitter/etc. It's hard for me to justify [the time](http://kcd.im/no-time) to write a good solid reply. But if I know that it will be read by and potentially help more people, then that time is more easily justified. Additionally, often the questions I get from people are the same ones I've already answered here, so it's easier to answer with a link than writing it out over again. It's worked out quite nicely.

**Comment by morajabi** [comment]
Wouldn't you prefer a simple reddit-like web app for AMAs. And everyone has his own page to answer? (I'm asking if it is a good thing to build). Look at here https://github.com/sindresorhus/amas there's too many wanting something like this IMO.

**Comment by kentcdodds** [comment]
I actually prefer GitHub to a special app because everyone already has accounts on GitHub (among other reasons).

**Comment by morajabi** [comment]
That can be solved with login with Github. If you had time I want to know the among other reasons.
