### ISSUE TITLE
Are companies interested in hiring an experienced 16 year old?

### ISSUE THREAD

**Issue by morajabi** [kentcdodds/ama#296]
Hi Kent!

I’m a 16.7 yo boy and worked on some pretty big JS projects in my startups. I focused on JS about 3 years ago and before that I was a freelancer for another 3 years. I’m not writing a resume, so I just wanted to say I’m not a newbie that lives in his dreams without exp! 

But now I’m going to apply for software engineer or js developer positions. I'm wondering are companies interested in hiring talented and curious young boy? I am a bit scared because I don’t have any experience in applying for jobs.

I need someone’s words that has experience in hiring. Thanks.

**Comment by kentcdodds** [comment]
Hi @morajabi!

> I'm wondering are companies interested in hiring talented and curious young boy? I am a bit scared because I don’t have any experience in applying for jobs.

Seems to me that you actually do have a fair amount of experience:

> I focused on JS about 3 years ago and before that I was a freelancer for another 3 years.

I think that some companies may be slightly concerned, and depending on where you live I believe there are legal concerns with hiring a minor. However, I've worked with minors at companies before and they were really valuable to the company. Nice thing about the tech industry is that generally you're valued by merit rather than education/age. Unfortunately there is a fair amount of bias and prejudice in our industry that we're working on removing, but I think you should be able to make it alright.

Good luck to you!

**Comment by morajabi** [comment]
Thanks for the points. I appreciate your words.

**Comment by vitkarpov** [comment]
@morajabi Oh, boy! I wish I worked on some pretty big JS projects when I was the same age, I'd be way further in my career right now.  You're a very lucky young man, good luck!

**Comment by morajabi** [comment]
@vitkarpov Thanks man, I think we are good where we are, maybe a lot of things good or bad would happen if we did something else at some point but we can hopefully do better for future *some points*. I'm sure *better* is not just more of something we think is good.
