### ISSUE TITLE
Gay Marriage

### ISSUE THREAD

**Issue by joshuapaling** [kentcdodds/ama#298]
Hi,

I noticed you've responded to [this question](https://github.com/kentcdodds/ama/issues/218) and said that you're "LGBTQ+ inclusive, friendly and accepting". I'm curious to know where you stand when your religion (which I gather values morality very highly, but tends to hold quite a traditional / conservative perspective) conflicts with the moral standards within your circle of the tech community (which tends to be morally very liberal / progressive).

For example, if a free vote were held, would you vote in favour of, or against, legal gay marriage?

If in favour, how do you reconcile that with the Mormon church's stance, which I gather is against gay marriage? Would many Mormons be in favour of it?

If against, do you worry about how holding that view will be perceived within the tech community? How would you reconcile an "against" vote with being "LGBTQ+ inclusive, friendly and accepting"?

Thanks!

**Comment by joshuapaling** [comment]
I've picked gay marriage as an example, but if you happen to have other areas where well intentioned, conservative religious morals conflict with well intentioned, progressive morals from tech circles, I'd be interested to hear how you internally resolve the two.

**Comment by kentcdodds** [comment]
Hey @joshuapaling,

Thank you for the questions!

> For example, if a free vote were held, would you vote in favour of, or against, legal gay marriage?

I would vote in favor. On this issue in particular, I don't think that the government should be involved at all. So anything to reduce regulation is good for me.

> If in favour, how do you reconcile that with the Mormon church's stance, which I gather is against gay marriage?

Here's [the official stance of The Church of Jesus Christ of Latter-Day Saints on Same-Sex Marriage](https://www.lds.org/topics/same-sex-marriage). I agree with every word in it. Voting in favor of legalizing gay marriage is not in opposition to the teachings of my church. The LDS church, repeatedly teaches that we should love and respect all individuals, including those who hold differing beliefs and convictions.

> Would many Mormons be in favour of it?

I'm not certain I can answer this. I know that a fear some church members have is that something like this would be a "slippery slope" leading to the government regulating that our churches and temples must be open to performing same-sex marriages. This is not something I personally expect to happen.

> I'd be interested to hear how you internally resolve the two.

In answer to your more general question of how to reconcile conflicts between the teachings of my church and my personal beliefs... The LDS church has a well defined method for us (all of us) gaining an understanding God's will.

In the event of a conflict, I would seek inspiration from Heavenly Father. Personal revelation is something that our church teaches and encourages. I receive revelation from our Heavenly Father because He loves me and wants me to be happy. I make most of my decisions based on inspiration from God.

There have definitely been times where I personally struggled with counsel from church leaders. When I've hit my knees and opened the scriptures to understand God's will. And there have been some situations where I've been required to continue in faith because I don't quite "get it" yet. This hasn't happened very often, and most of them are quite personal, but I can share an example of a situation where faith without complete understanding has been beneficial to members of the church:

God has given us a code of health we call ["The Word of Wisdom"](https://www.lds.org/topics/word-of-wisdom). It was a revelation received way back in 1833 and counseled against smoking. At the time, that was confusing because it wasn't yet known the serious health issues with regards to smoking/ingesting tobacco. In fact, over a hundred years later, [doctors were still recommending cigarettes](https://www.youtube.com/watch?v=D-y_N4u0uRQ) ([see also](https://www.buzzfeed.com/copyranter/healthy-cigarette-ads?utm_term=.ngmZbE7ly#.tpGWrYbOX)).

I'm not entirely certain doctors actually believed that cigarettes were good for you, but to the rest of the world it would have been easy to just start smoking like everyone else. But because the Lord had revealed long before of the dangers of a habit like smoking, members of the church who followed that counsel avoided the addiction and life threatening habit.

Anyway, I hope that gives you an idea of how I feel about the counsel my church gives. I should emphasise again that The Church of Jesus Christ of Latter-Day Saints constantly teaches what our Savior taught when He was on the earth. And that is unconditional love and respect. I try to follow the Savior's example in everything that I do.

Thanks for the question!
