### ISSUE TITLE
wondering

### ISSUE THREAD

**Issue by safweb89** [kentcdodds/ama#302]
nothing for free bro ?

**Comment by vitkarpov** [comment]
I'm just wondering what's the question about and what will be the answer :) Leave it here to subscribe

**Comment by kentcdodds** [comment]
Hey @safweb89! :wave:

Thanks for the question. Anything of value in this world comes at the cost of _something_. Trade-offs and that kind of thing you know :wink:

So if I give you a sandwich, you got the sandwich for free, but the cost was whatever it took me to get the sandwich. In fact, the cost includes you accepting the sandwich. That may have distracted you from doing something else, so there's another cost!!!!!! AHHH!!!!

There are costs all over the place. I recently read a book called ["The RIchest Man in Babylon"](https://en.wikipedia.org/wiki/The_Richest_Man_in_Babylon_(book)). It is a short book and very fascinating. One of the things mentioned in that book is the idea that value does not escape from the world. So if I pay a bunch of people to build me a house, the value of the world is increased because that money I paid goes to the people who helped to build the house _and_ the house now exists, so there's more value in the world than before. So the idea that "work" can increase the value of the world is a powerful one. Another thing that the book talks about is the value of making "work" your friend. It's a very insightful book. I suggest you read it.

Anyway, I'm not sure whether that's what you were looking for, but there you have it anyway :smile:
