### ISSUE TITLE
How to migrate CSS modules to CSS in JS? How to encapsulate / share CSS in JS styles between different applications?  

### ISSUE THREAD

**Issue by anaibol** [kentcdodds/ama#307]
Hi Kent!

I have some questions regarding CSS in JS solutions and I know you built Glamorous that seems to be one of the more matures solutions.

- How do you migrate and old application with SCSS and CSS modules to CSS in JS? It's all manal work like redoing all the styles in the new format?

- How do you do for sharing components in different applications (different styling techniques) with CSS in JS styles?

Anxious to read your thoughts! And thanks in advance!

**Comment by kentcdodds** [comment]
Hi @anaibol!

Thanks for the question.

> How do you migrate and old application with SCSS and CSS modules to CSS in JS? It's all manal work like redoing all the styles in the new format?

One of the things I'm really happy about glamorous is how well [it works with existing CSS solutions](https://glamorous.rocks/advanced#working-with-existing-css). If you see in that example you can actually pass any class name to a glamorous component factory and start getting some of the benefits instantly without actually moving your styles into your JS. When you're ready to start migrating it to JS, then you can use an editor plugin to make that easier, see ["Related Projects" in the glamorous repo README](https://github.com/paypal/glamorous#related-projects).

> How do you do for sharing components in different applications (different styling techniques) with CSS in JS styles?

Actually, I think this is one of the best parts of CSS-in-JS. With regular CSS you have to tell people to include your component's CSS file in addition to importing the component wherever it's used. With CSS-in-JS, you just have people include the component and it magically works. You don't really have to concern yourself with how the different applications style themselves because it doesn't change anything for you. Just tell people to import and use your component and the styles come with it.

Good luck!
