### ISSUE TITLE
Should we put so much effort into unit tests if we need to frequently change them as requirements change anyway?

### ISSUE THREAD

**Issue by starandtina** [kentcdodds/ama#308]
Hey Kent,

In recent projects, we’re always driving front-end standardization concepts going forward and maintain a high-quality team for speedy delivery, especially for Unit Tests. The code coverage for latest brand new projects have surpassed 90%, so with these proper tests in place, we can refactor code like crazy and have enough confidence that we don't break anything. At the same time, we could add new features and tweak existing code bases with the same confidence.

At the same time, we also had encountered some kind of situations I need your inputs here. For some urgent projects, we always need to refactor it according to the requirements or design changes, every time we also need to refactor the unit tests ensuring it covers the latest updates.

Team members always ask me one question: If we need to re-write all the unit tests next sprint (or next next sprint), why we need to put more than half of time on writing unit tests? If I don’t do that so I could spare more time on feature development then it could make our boss and customers happier.

Do you have any experiences with this kind of case? How do you handle it? Looking forwarding to your response.

Thanks,
Khalil

**Comment by kentcdodds** [comment]
Hi @starandtina!

This is a great question! I love [this quote](https://twitter.com/rauchg/status/807626710350839808) from @rauchg

> Write tests. Not too many. Mostly integration.

There's the concept of [the testing pyramid](https://martinfowler.com/bliki/TestPyramid.html) that encourages you write mostly unit tests. I actually disagree and suggest that it's better to write more integration tests than unit tests.

When you write a unit test, it's easier to find yourself testing implementation details. One way to know you're doing this is you wind up mocking a bunch of dependencies. Testing implementation details 1) is not giving you the confidence you think you're getting, 2) makes you have a false sense of security (so it's even worse than having no tests at all), and 3) means you have to change your tests when you refactor.

On the other hand, when you write integration tests, you're more concerned with the output of several units put together. It's harder to test implementation details in this case even if you wanted to ([pit of success](https://youtu.be/3-4KsXPO2Q4?t=6m31s) applies here). The talk ["Mocks & stubs"](https://www.youtube.com/watch?v=EaxDl5NPuCA) by @kenbot has some really interesting ideas that I mostly agree with. Definitely recommended watching there! (Note, he's not talking about unit vs integration tests, in fact if I recall correctly he asserts that distinction is pretty irrelevant and I agree with him there as well).

The problem is that it's often easier to write unit tests. They're generally faster and take less work to set up. But a well-written integration test is much more robust against refactorings. Like everything, writing good integration tests takes practice! I have some suggestions in [my testing course on Frontend Masters](http://kcd.im/fm-testing) (see [the _practice_ run](https://youtu.be/DdqiXcYDv-8?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) for free).

On the subject of code coverage, 90% is awesome (for all the reasons you mentioned). However, consider [this tweet](https://twitter.com/KentBeck/status/812703192437981184) from @KentBeck:

> Being proud of 100% test coverage is like being proud of reading every word in the newspaper. Some are more important than others.

I think a sweet spot is somewhere around 75% test coverage and a solid amount of type coverage (via Flow or TypeScript). You'll also find that integration testing is well suited for increasing your code coverage quickly.

There are definitely some places you'll want unit tests (complicated functions that are filled with business requirements you don't want to break for example). It can often be difficult to cover all cases using integration tests.

I should also mention that for my libraries, most of them are small and I always enforce 100% code coverage with them. That's easy to do and I suggest anyone writing a small to medium sized library strive for that.

I hope this is helpful to you! Best of luck on your team!
