### ISSUE TITLE
How to get started writing React lib?

### ISSUE THREAD

**Issue by felipecocco** [kentcdodds/ama#310]
There is a small CSS library on Github that I absolutely adore (https://github.com/kumailht/gridforms), and it was useful in a few projects. Mostly as an exercise, I want to see if I can make a small form component library with it as an inspiration.

I have no idea where to start, though. Create-react-app has spoiled me since I've rarely have had to worry about anything but my application's code. I'm confident I could build the components, but a lot less confident about everything else that would be involved in making it into an actual library that could at some point be available on npm. Any tips/hints/resources are greatly appreciated!

**Comment by kentcdodds** [comment]
Hey @felipecocco!

create-react-app has spoiled me as well! I barely remember how to configure webpack anymore! Honestly, I think that you'd appreciate looking at my most recent React open source library for inspiration on how to do things: [downshift](https://github.com/paypal/downshift). You'll notice that I'm using rollup. That's because rollup fits with libraries a bit better than webpack does (webpack's more for applications than it is for libraries).

Good luck!
