### ISSUE TITLE
Machine Learning/AI and the future of development jobs

### ISSUE THREAD

**Issue by shaneu** [kentcdodds/ama#321]
Hi Kent! I'm working on becoming a frontend developer, and I feel I am making great progress, and enjoying it greatly. Something on my radar though is Machine Learning, and its implications for us as developers. The research I have done has suggested it will almost entirely replace the jobs we perform, as who better to program a computer than a computer. Do you have any thoughts on this? I've begun studying machine learning on the side, figure it can't hurt, but do you think it's as dire as I've heard? Thanks -Shane

**Comment by arthurchipdean** [comment]
Here is a good answer to your question:
"In my humble opinion, this is a gross misrepresentation of the impact of AI on organizations and structures. While it's fair to say AI is helping organizations automate basic tasks of repeated nature, they are far (read decades) from reaching a level of maturity where AI (and Robots) can replace humans in complete. The above-mentioned survey confirms much the same. Per the survey, only 12% organizations believe they'll replace humans due to AI and robots. In fact, a significant 68% confirmed their intent to hire new people to manage increased complexity arising out of use of AI. Hence my assertion that use of AI points to the need for newer skills, hence newer types of jobs and not the proposed lesser jobs."
Source: https://www.linkedin.com/pulse/busting-myths-artificial-intelligence-sanchit-vir-gogia

**Comment by kentcdodds** [comment]
Hi @shaneu,
Thanks for the question!

I'm inclined to agree with what @arthurchipdean shared. I believe that when the plow was invented a lot of people lost work, but it's more of work displacement rather than replacement. So people had to develop other skills but still found something useful to do.

I hope that the future looks like Star Trek. Much of human function is replaced by computers, but it allows us to make use of our time to pursue our other interests, spend more time with family, experience new things, etc. There will definitely be room for folks to contribute to society in many ways and I'm excited to see that.

I do plan to be coding for my whole life whether computers are better at it or not 😜
