### ISSUE TITLE
What unit tests do you start out with?

### ISSUE THREAD

**Issue by Caryyon** [kentcdodds/ama#323]
I'm starting a really big new project at work and I'm interested in what unit tests I should aim to be writing right off the bat. 

If you could give some examples of your first unit tests when starting a new project that would be great?

Thanks!

**Comment by kentcdodds** [comment]
Hi @Caryyon!

Thanks for the question! Congrats on starting a big new project at work! That's not something many folks get to do very often!

As for where to start with unit tests... I recently wrote a newsletter about that you might be interested in: ["Write tests. Not too many. Mostly integration."](https://tinyletter.com/kentcdodds/letters/write-tests-not-too-many-mostly-integration) I think this is solid advice, especially for a new project. As you're building it, things will probably change at a rapid pace. With project volatility like that, you'll find yourself having to delete and refactor code at an alarming rate. If you focus your time on unit tests, you'll find yourself having to delete and refactor your tests a lot as well. This will slow you down.

Alternatively, if you focus on integration tests, you'll get more coverage faster, have to write fewer tests, and need to update them less frequently. This comes at the cost of the tests being slightly more brittle (they could break more easily depending on how good you are at avoiding testing implementation details) and being a bit more difficult to write. But I think you'll find that you'll be more successful increasing your confidence in shipping your app if you focus on integration tests rather than unit tests.

As for where to start, remember that tests are all about confidence. So think about where you need confidence in your app and start there. For example, the checkout process of an ecommerce app is way more important than the settings page.

Good luck! (And you might consider [subscribing to my newsletter](http://kcd.im/news) for more stuff like this :wink:)
