### ISSUE TITLE
What workflow/process do you use for making videos?

### ISSUE THREAD

**Issue by bradydowling** [kentcdodds/ama#344]
I made several tutorials and videos a few years ago and I have several topics I want to cover so I want to get back into it now.

Before, when I was making videos, I never felt like I had a good workflow. I wondered if I was spending too much time in certain areas like researching or recording and not enough time in other areas like practicing. Of course, each person will have a process that works for them but what is your process like?

Do you make a script or bullet points to hit? Do you do a dryrun of the video before even hitting record? How much time do you spend editing?

Do you master a topic first, then make videos for it? Do you use the video making process as a means of learning something? Do you learn something because you want to make videos for it or the other way around?

**Comment by kentcdodds** [comment]
Hi @bradydowling! I'll get to this when I can, but until then you might find this interesting: https://github.com/kentcdodds/ama/issues/341

**Comment by kentcdodds** [comment]
Hey @bradydowling!

So I have two things for you that might help:

1. [The Egghead.io Instructor Guide](https://instructor.egghead.io/guide/)
2. [The Egghead.io course about making Egghead.io screencasts](https://egghead.io/courses/record-badass-screencasts-for-egghead-io)

I pretty much follow the workflow that John suggests in that course. To answer your questions specifically...

> Do you make a script or bullet points to hit?

I've done that before but find that the end result feels less natural. So I now do what John suggests. Hit record, and if I don't like what I say, back up and start again from the last good part of the screencast. Don't hit the stop button until it's all recorded.

> Do you do a dryrun of the video before even hitting record?

Sometimes, but not normally.

> How much time do you spend editing?

It really depends on how many mistakes I make. But I'd say it takes me about an hour to edit for a 5 minute screencast.

> Do you master a topic first, then make videos for it?

I try to have a good enough understanding of a topic that I know I'm not misleading anyone. For example, JavaScript syntax or JavaScript APIs are pretty easy to learn and make a video about without having much experience using them in production. But I wouldn't make a course about Apollo until I had an opportunity to use the tool in an app.

> Do you use the video making process as a means of learning something?

Yes. Absolutely. During the process of preparing a course, I'm always learning new things. It's my big secret. What everyone's seeing is a part of my learning process. But don't worry, I try to only teach things when I'm pretty sure there's not a better way to do it.

> Do you learn something because you want to make videos for it or the other way around?

I generally only make educational material out of stuff that I've used to build things. I generally build things using tech I want to learn. So I generally learn something because I want to, and then make a course out of it :)

I hope that's helpful!
