### ISSUE TITLE
TypeScript or Flow

### ISSUE THREAD

**Issue by v1adko** [kentcdodds/ama#356]
I wonder what's your personal favorite and why, which one you like using better?

I saw you mention in several answers and talks that static type-checking is a great way to minimize errors, but you don't seem to choose one over the other and always mention them as a pair.

**Comment by kentcdodds** [comment]
Hi @v1adko!

So I prefer Flow. Not from a philosophical "I understand type systems and like Flow's better" standpoint (because honestly I don't understand type systems very well), but mostly from a tooling standpoint. I don't like that adopting TypeScript means I have to drop ESLint and Babel (yes, I know that there are weird things you can do to make them play nice but I don't like doing those things. Yes I know babel 7 "has support" for TypeScript, but [it doesn't really](https://twitter.com/jaredpalmer/status/953076867527036929)... and I don't expect it to be well maintained anyway...). 

The reason I mention them both is because I don't want all the TypeScript folks yelling at me that I left out their favorite tool (because I've seen TS fanboys do that 😦). But I use and recommend Flow. :)
