### ISSUE TITLE
What did you take away from your 2-year Mormon Mission?

### ISSUE THREAD

**Issue by sw-yx** [kentcdodds/ama#358]
In relation to [this](https://twitter.com/kentcdodds/status/956582453434515456) - You served in the Missouri Independence Mission for 2 years and I figure that must have been formative in some sort of way. (I am not religious but was raised in a religious household). Just wondering if you could shed some light for others who haven't had the chance to do something like this?

**Comment by kentcdodds** [comment]
Hey @sw-yx! Thanks for the question!

So anyone who has served a 2 year mission can tell you that the experience that cannot be related in words. It was an experience unlike any other. For those unfamiliar with the (sometimes unexpected) requirements and lifestyle of an LDS missionary, let me give you a few facts of the experience:

- Members of the LDS church are encouraged (not required) to go on a mission in their late teens (18 and 19).
- Missionaries are responsible to pay their way. They are not paid.
- Missionaries don't choose where they go, but normally serve in a single geographical area (some large, some small) called a "Mission" for the entirety of their mission. The decision of where to serve is up to the [Quorum of the Twelve Apostles](https://www.lds.org/church/leaders/quorum-of-the-twelve-apostles?lang=eng) (directly, they do not delegate this responsiblity).
- Many missionaries serve in a country speaking a language they've never learned before. The first few **weeks** are dedicated 100% to learning and study of both the gospel and the language of their mission if it's a language they don't already know.
- Missionaries are always accompanied by a companion everywhere they go (except like... obviously they shower alone and stuff...).
- Missionaries don't choose their companion. They can be with their companion for one transfer (6 weeks) or many. The decision is up to the Mission President.
- There is a very set leadership structure to the mission. I served as a trainer (of a new missionary), district leader (leader of ~4 companionships in a single city), and a zone leader (leader of 2-3 districts in a single city). There's also the assistants to the president (leader of the whole mission assisting the president in any capacity). My friend and now fellow coder @danseethaler was one of my assistants for a few months.
- Missionary life is very focused on service and teaching the gospel. You can find the daily schedule in the missionary manual: [Preach My Gospel](https://www.lds.org/manual/preach-my-gospel-a-guide-to-missionary-service/introduction-how-can-i-best-use-preach-my-gospel?lang=eng#figure1_title1)

It was honestly the best 2 years I had experienced so far in my life (I have since been married and had children, so I can't say it was the best 2 years of my life anymore). It changed and stretched me in ways that I could never have anticipated or planned for.

Just for fun, here's a video of when I got my mission call to the Missouri Independence Mission: https://www.youtube.com/watch?v=MCv2Oh9jRug

So what did I take away from my mission? I think the most important thing for me that I took away was learning how to develop and deepen my relationship with Jesus Christ and my Heavenly Father. Nothing is more important than that. I also learned how to avoid prejudice and became aware of my privilege. I developed an attitude of gratitude and learned of our moral obligation to serve those around us, especially those with whom we can lend our privilege. I saw first-hand how the gospel of Jesus Christ can change people's lives for the better. I gained a new level of accountability and work ethic which I don't think I could have gained otherwise.

It was an amazing time of my life. Thanks for asking the question because it gave me a chance to relive some of it.

If you're curious, when I got home from my mission I made this montage of a bunch of my photos that you might enjoy: https://www.youtube.com/watch?v=XGkzzb5EMg4

Thanks again! Feel free to ask any follow-up questions you have :)

**Comment by sw-yx** [comment]
That video was precious :) so glad that it was recorded and also I love that you read through the ENTIRE letter! haha. Thank you for sharing, I can never live it but I can appreciate how it is a very special thing.

**Comment by kentcdodds** [comment]
Thanks for appreciating it 😀
