### ISSUE TITLE
The industry has too many Junior devs and not enough Senior devs. How can we fix this?

### ISSUE THREAD

**Issue by sw-yx** [kentcdodds/ama#359]
Not expecting you to have answers of course but I thought it might be a worthy question you might have some good thoughts on.

Just an Idea: I have thought that the pay for jr devs (say 50-100k in coastal US) vs the pay for senior devs (200-500k?) is so, so wide that you could essentially set up some sort of mentorship system where the companies that wanted a senior dev that isn't available just hires a junior dev, but pays say 30-50% more to get part of a senior dev's time to review and coach the junior dev. This would in the long run fix the massive experience imbalance in the industry (every company understandably mainly wants to hire senior devs, and doesnt want to spend the resources to train up junior devs). Of course, I'm not a senior dev so I don't have an appreciation for the constant value that experience brings.

**Comment by cuong-nguyen** [comment]
You are asking someone who humbly considers himself still a junior developer :)

**Comment by kentcdodds** [comment]
Haha, I'm not a big fan of titles, but I can appreciate the terminology as a way to communicate experience level :)

I'll get back to this as soon as I'm able :)

**Comment by sapegin** [comment]
Mentoring junior developers is already a part of senior developers job, I’m not sure why do you want to pay them more.

**Comment by tsiq-swyx** [comment]
dont focus on my proposed solution. its just one proposal. focus on the main question: *The industry has too many Junior devs and not enough Senior devs. How can we fix this?*

Here are the answers i've gotten so far:

- junior devs need to work harder (e.g. "If we're interested in extracting potential from an individual,  in my experience, that comes more from discipline and ambition than anything else.")
- of course Senior devs are in demand, wouldn't you want that too?
- "I would argue that most companies arent willing to pay the premium for a strong representation of senior individuals in their workforce, so the idea of under-representation is really subjective to the company you're at."
- Mentoring junior developers is already a part of senior developers job ☝️ 

None of these answer the question. A lot of people are fine with the world as it is. im just looking for simple ideas to make things a little bit better.

**Comment by trafnar** [comment]
What led you to believe that the industry has "too many" junior devs?

**Comment by sw-yx** [comment]
https://news.ycombinator.com/item?id=16367997 here's an illustrative example discussion :)

**Comment by kentcdodds** [comment]
Hey folks!

> The industry has too many Junior devs and not enough Senior devs.

I would change this phrasing to be more like:

> Companies don't know what to do with Junior devs and are not taking advantage of the value that they can provide.

Here's the thing: my last team at PayPal was composed mostly of developers who we hired straight out of a boot camp (HackReactor). They're all rockstars. Not all new devs turn out to be rock stars, but we trust our hiring process and recognize the value of having newer developers on the team. It forces us to simplify our processes and codebases and justify the decisions we make. Also, these Juniors are actually providing a great deal of value. They're not just sitting around doing nothing. What they do is actually useful and helpful to the company _and_ it means that the senior developers can focus on more senior problems. Every company has junior level problems. Would you prefer that your senior level developers spend their time solving those junior level problems? It'll draw their attention from the senior level problems they could be solving.

Many argue that juniors will pull seniors away from the work they're doing. As if to say that juniors need 100% supervision for the entirety of their employment. Which may be true if the company is bad at investing in the training and mentorship of their engineers (if this is the case, get out fast).

Now, to some of the specific things you brought up. First off I don't know very many people making more than $150k per year. At least not in Utah. I know some companies like Netflix pay very high performers upwards of $300k per year, but that's in California and it's pretty rare. So the pay gap is pretty wide, but it's not quite as wide as you suggested I think.

In general I like your idea of mentorship, but I don't think it needs to be formalized financially like that. I think that companies just need to improve their hiring process so they are more confident that the junior they're hiring has the potential to become a great senior engineer (most do), and they need to improve their mentoring and training culture so the juniors can be trained up (which also helps the seniors because teaching is the best way to [solidify learning](https://blog.kentcdodds.com/solidifying-what-you-learn-6650258c84be).

Another important argument I get against hiring juniors is that they're time at the company is often very short. This is unfortunately often the case. But it's not just because they're juniors. It's because companies aren't recognizing the value improvement of a Junior. Often, juniors see a huge spike in value contribution in the first 4-6 months of their first job, but they don't see that spike in their salary, which make the other companies offers very compelling. For example, my first company I started at $65k, four months later another company came to me offering $100k. I let my first company know and they just couldn't bring themselves to give me 70% raise because I was the new kid they just hired. They missed out big time just because they didn't stop to consider the reason that the other company was offering me so much more. It was because Junior's ability to provide value has hockey-stick growth in the first few months of employment. So companies need to recognize this and make salaries/other rewards reflect that (not wait until they come to give their 2 weeks notice or until the year review).

Anyway, I hope all this is helpful. Good luck!

**Comment by tsiq-swyx** [comment]
thanks very much for the thoughts Kent! I am doing my best to follow the consume-build-teach loop you laid out. I hope to create a supportive hiring and mentoring culture in future when I am in a position to do so.

**Comment by DeadZen** [comment]
The industry also has too many Senior developers who in reality are simply old Junior's... 
Peeking into the nature of computing, requires solving problems of incremental complexity, while comparing and contrasting philosophies and methodologies. Solving the same problem with the same tools over and over again expands the mind very little. Breaking everything down to it's essential components then building them back up in a variety of ways with a variety of technologies results in more comprehensive assimilation of fundamentals, like OS and Networks.  
You can have ten years of experience and simply have experienced the same thing ten times.. 
Push the limits of efficiency/concurrency/stability and you will learn the nature of those concepts.
