### ISSUE TITLE
Cypress test framework - thoughts ??

### ISSUE THREAD

**Issue by vjrngn** [kentcdodds/ama#360]
Hey kcd. I'd love to get your opinions on the Cypress test framework.

**Comment by kentcdodds** [comment]
Hi @vjrngn!

I totally love it and prefer it for all tests I want to run in an actual browser. I like jest because it's fast and has amazing features. But Cypress is a great E2E testing solution. I'm even considering using it to drive my development workflow. Specifically, using it rather than my browser to build an app. This is something I've yet to try, but hope to soon.

I hope that helps. Good luck!
