### ISSUE TITLE
Mocha, Chai, Sinon vs Jest

### ISSUE THREAD

**Issue by stramel** [kentcdodds/ama#370]
So I took a quick look at Jest and read through some of the documentation.  It feels a lot like Mocha, Chai, with enhanced Sinon. What am I missing?

**Comment by kentcdodds** [comment]
Hi @stramel!

Until you actually start using it you don't quite notice, but here are a few things you'll start to notice as you start using it:

1. You have to install and wire-up fewer dependencies and configure a LOT less to get all that stuff (even code coverage + babel)
2. The watch mode is absolutely amazing
3. If you have multiple test suites with different configurations, the `projects` feature from Jest is AMAZING!
4. The fact it runs in parallel makes a HUGE difference with a large suite of tests
5. The fact that the watch mode can run only the tests impacted by the files you've changed since the last commit is awesome.
6. The fact that jest can track which tests to run based on the files changes is an amazing feature, especially if you have a large test suite and want to run those tests as part of a pre-commit git hook.

I hope that's helpful. Good luck!

You may find more info helpful in this question about [ava vs jest](https://github.com/kentcdodds/ama/issues/184).
