### ISSUE TITLE
Maintaining a healthy work life balance

### ISSUE THREAD

**Issue by mcrowder65** [kentcdodds/ama#372]
Hey Kent,

I just graduated from BYU April '17 and I've been working for Walmart Labs since June '17.  I love to work and it is starting to pay off nicely opportunity wise, (just got promoted)... Just wondering if you have some good tips for maintaining a good work life balance, especially when you have a wife... We don't have kids yet, but I know you have some, and I can't imagine having kids right now with how much I want to work!

**Comment by kentcdodds** [comment]
Hi @mcrowder65! Congrats to you!

> I can't imagine having kids right now with how much I want to work!

This is the big fallacy of our time. Kids are a LOT of work and the WILL take you away from the things you're enjoying right now, but they are SO much more enjoyable than whatever you're enjoying right now (lots of the time). You really don't know until you have them. So I don't really have too much trouble maintaining work/life balance because as much as I love my job, I love my family more and so I don't have any trouble wanting to work more than I spend time with my family.

I wish the same could be said of everyone, but I think that a family is an investment and if you don't invest enough intentional time and love into it, you wont enjoy them as much.

Anyway, that's my perspective. I hope it's helpful. Good luck!
