### ISSUE TITLE
How much props is too much?

### ISSUE THREAD

**Issue by ritchieanesco** [kentcdodds/ama#375]
Hey Kent!

Your advanced courses on Egghead are great and its great to see you respond to people like myself from your busy schedule. I was wondering if you have some guidelines as to when there maybe too much happening in a component and should be broken down?

**Comment by kentcdodds** [comment]
Hi @ritchieanesco!

Think of components like functions (because hey! That's what they are!) and apply the same rule to the number of props that you normally would to functions. The more arguments a function has the more likely it is that the function is doing too much and you may want to break some things out. This is actually where things like [render props](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce) and [state reducers](https://blog.kentcdodds.com/b40316cfac57) come in really handy to help you give control over the UI and state to users of the component so you don't have to provide so many props to configure how those things work.

Good luck!
