### ISSUE TITLE
How to Test Things on Android Webview Browser?

### ISSUE THREAD

**Issue by alayek** [kentcdodds/ama#377]
As the title says.

When people find a link to your site on their FB or Twitter or Messenger app, the link usually opens in an embedded web-view; unless user know how to change settings to open it in their mobile browser (chrome, safari etc.).

How does one test for web-view support? What are the best practices? Is it as simple as adding user agent in chrome dev tool and do a mobile debugging?

Different apps customize their in-app browsers differently.

How much of an app's functionality would work inside the in-app browser? What about form submit, file uploads etc.?

I found some photo upload functionality in a classified ad posting site, that works in Twitter's in-app browser, but broken in the in-app browser of FB / Messenger. 

I searched, but couldn't find much resources on this.

**Comment by kentcdodds** [comment]
Hi @alayek!

That's interesting! I've never done anything like that before! I honestly probably wouldn't dedicate any resources to it unless I were aware of specific issues we had in our app (as you have) which we expect to crop up again. It'll take a fair amount of work, but what I would probably do is write a simple application that could simulate the in-app browser from FB / Messenger. Then I'd use some sort of native driver test tool to reproduce the bug and write a test to make sure it never happens again.

I honestly have no idea what tools are available for this though because I don't don't much with mobile. Good luck!

**Comment by alayek** [comment]
Thanks @kentcdodds 🙇
