### ISSUE TITLE
Hiring Process

### ISSUE THREAD

**Issue by joelkinzel** [kentcdodds/ama#398]
Hi Kent,

In #359 while talking about junior developers you said...

> ...but we trust our hiring process...

I was wondering if you could shed a little light on that process. I'm curious about the different steps of the process, what/who from the company would be involved, what the candidate is asked to do, and what information the interviewers are looking to get from each step? We're in the process of looking for/hiring junior developers and I'm looking for fresh ideas to ensure our hiring process is the best i can be for those without much experience.

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by detrohutt** [comment]
Answer starts at [2:05](https://youtu.be/y23g8L8UtoQ?t=2m5s).

#### PayPal hiring procress

1. You apply for a job
1. Several engineers look at your resume and try to match it to a job description for the positions they're currently hiring for
1. If you're a match for something, there's a 30min-1hr phone screen with an engineer to get to know you better, do some code challenges, etc. (sometime there's a take home code challenge but Kent isn't a fan of that)
1. If you pass the phone screen there's an on-site interview (travel expenses paid). 4-part interview with a lunch. Each interview is 45 minutes. 2 engineers interview you in the morning, lunch with a manager, and 2 interviews in the afternoon. These are technical but practical interviews. You'll be asked to do things like create a small GUI interface rather than about algorithms, etc. Kent likes to ask about 5-year plans to see if the position can help the prospective employee meet their career goals.
