### ISSUE TITLE
AST: Preserve formatting in arrays

### ISSUE THREAD

**Issue by innovation-stack** [kentcdodds/ama#400]
Hello Kent,
Can you help me understand how to preserve array formatting while converting AST back to source code.
I was experimenting in http://astexplorer.net/.

### SOURCE CODE:

```
module.exports = function () {
    var obj = {
        data: [ // Note the array formatting. Each element on different row
            'abc',
            'xyz'
        ]
    };
    return obj;
};
```

### PLUGIN:
```
export default function (babel) {
  const { types: t } = babel;
  
  return {
    name: "ast-transform", // not required
    visitor: {
      'ArrayExpression': function (path) {
        if (path.parent.key && path.parent.key.value === 'tenants') {
          const elements = path.node.elements.map(e=> e.value);

          // Add 'test' only if it does not exists
          if (elements.indexOf('test') === -1) {
            elements.push('test');
            var newElements = elements.map(e => {
              return t.stringLiteral(e);
            });
            path.replaceWith(
              t.arrayExpression(newElements)
            );
          }
        }
      }
    }
  };
}
```

### RESULT:
```
module.exports = function () {
  var obj = {
  	'tenants': ["abc", "def", "test"]
  }
  return obj;
};

```

**Comment by kentcdodds** [comment]
Hi @innovation-stack,

You _might_ be able to preserve formatting by using a custom printer called [recast](https://github.com/benjamn/recast). You can use it with babel and tell babel to use recast's printer. [I actually tried this](https://github.com/kentcdodds/babel-with-recast) about 2 years ago and experienced some issues. I'm pretty sure that it's working now though, so if you want you can play around with that. It wont be perfect for the nodes that you create because they have no location information. What I would recommend is running prettier on the code after the transformation is finished. Good luck!
