### ISSUE TITLE
Browser (chrome) extensions?

### ISSUE THREAD

**Issue by amandaporto** [kentcdodds/ama#409]
Hey! Wondering what your must haves or nice to have browser extensions are. Saw your video on React Dev Tools where you briefly showed them and was curious :)

**Comment by kentcdodds** [comment]
Hi @amandaporto!

Here's a screenshot from my extensions page :)

<img width="1252" alt="screen shot 2018-06-26 at 9 47 02 am" src="https://user-images.githubusercontent.com/1500684/41923912-f23eab2c-7925-11e8-8643-dc2a6539e1bf.png">

<img width="1242" alt="screen shot 2018-06-26 at 9 47 13 am" src="https://user-images.githubusercontent.com/1500684/41923916-f5945344-7925-11e8-94b3-a38dc293b7a5.png">

If anyone reading has time to comment with links to all of these I'm sure many folks would appreciate it :)

**Comment by detrohutt** [comment]
### Kent's Browser Extensions

* [Refined Github]()
* [Refined Github]()
* [Refined Github]()

**Comment by detrohutt** [comment]
### Kent's Chrome Browser Extensions

Name/Link | Description
-|-
[Refined Github](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf?hl=en) | Simplifies the GitHub interface and adds useful features
[1Password extension (desktop app required)](https://chrome.google.com/webstore/detail/1password-extension-deskt/aomjjhallfgjeglblehebfpbcfeobpgk?hl=en) | Extends the 1Password app on your Mac or Windows PC, so you can fill and save passwords in your browser.
[Accessibility Developer Tools](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en) | (Deprecated.) Accessibility audit and element properties.
[AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?hl=en) | The most popular Chrome extension, with over 40 million users! Blocks ads all over the web.
[appear.in screen sharing](https://chrome.google.com/webstore/detail/appearin-screen-sharing/bodncoafpihbhpfljcaofnebjkaiaiga?hl=en) | Share the screen from your computer in a video conversation, to show presentations, photos and documents.
[Application Launcher for Drive (by Google)]() |
[async render toolbox](https://chrome.google.com/webstore/detail/async-render-toolbox/fbchcodfbfjeededacomngobhnndcgol?hl=en) | Open source tools to debug your async render apps. Click on the icon to see the lag radar, ⌥+R to show/hide
[Chrome Do Not Disturb](https://chrome.google.com/webstore/detail/chrome-do-not-disturb/kidgbjjjkhkickaakajjpgdkcfnidphn?hl=en) | Hit the snooze button on your Chrome desktop notifications!
[Codecov Extension](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf?hl=en) | Coverage reports overlay in Github and Bitbucket.
[Contributors on Github](https://chrome.google.com/webstore/detail/contributors-on-github/cjbacdldhllelehomkmlniifaojgaeph?hl=en) | Show Contributor Stats on Github
[Emoji Assistant](https://chrome.google.com/webstore/detail/emoji-assistant/jmngpddmfdhocaiaaacfpgknpiaahpab?hl=en) | A chrome extension to autosuggest emojis while writing on the web.
[Github +1s](https://chrome.google.com/webstore/detail/github-%2B1s/lddfkkebajnpiicnpfamebilmhamkeme?hl=en) | Shows you the counts and avatars of those noisy '+1' comments and hides the original comments.
[GitHub Repository Size](https://chrome.google.com/webstore/detail/github-repository-size/apnjnioapinblneaedefcnopcjepgkci?hl=en) | Automatically adds repository size to GitHub's repository summary
[Google Docs Offline]() |
[JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) | Validate and view JSON documents
[Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en) | Lighthouse is an open-source, automated tool for improving the performance, quality, and correctness of your web apps. 
[LiveReload](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) | Provides Chrome browser integration for the official LiveReload apps (Mac & Windows) and third-parties like guard-livereload and yeoman.
[OctoLinker](https://chrome.google.com/webstore/detail/octolinker/jlmafbaeoofdegohdhinkhilhclaklkp?hl=en) | OctoLinker is a browser extension for Chrome, Firefox and Opera which allows you to navigate through code on GitHub more…
[Palettab](https://chrome.google.com/webstore/detail/palettab/bidckpnndigbjhmojikkhmejkfkpgoih?hl=en) | Bringing awesome colors and fonts to the new tab page! A little bit of something fresh every time you hit that new tab button.
[Password Alert](https://chrome.google.com/webstore/detail/password-alert/noondiphcddnnabmjcihcjfbhfklnnep?hl=en) | Password Alert helps protect against phishing attacks.
[React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) | Adds React debugging tools to the Chrome Developer Tools.
[Redux Dev Tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) | Redux DevTools for debugging application's state changes.
[Refined Twitter](https://chrome.google.com/webstore/detail/refined-twitter/nlfgmdembofgodcemomfeimamihoknip?hl=en) | Simplifies the Twitter interface and adds useful features
[Snoopie](https://chrome.google.com/webstore/detail/snoopie/ickbbjgidjpmiggaclheacnffnpghpbn?hl=en) | Snoopie lets you know when you're being recorded by popular tracking services.
[Stylish - Custom themes for any website](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) | Customize any website to your color scheme in 1 click, thousands of user styles with beautiful themes, skins & free backgrounds.
[Tab Size on GitHub](https://chrome.google.com/webstore/detail/tab-size-on-github/ofjbgncegkdemndciafljngjbdpfmbkn?hl=en) | Make tab indented code more readable by forcing the tab size to 4 instead of 8
[Tabb](https://chrome.google.com/webstore/detail/tabb/lckpgdmcdbbcbcopmenpielppdipkpef?hl=en) | Take control of your tabs. Search through tabs, bookmarks, and history to jump between pages without clicking at hundreds of tabs.
[Twitter for GitHub](https://chrome.google.com/webstore/detail/twitter-for-github/joalalcafnlmimkfkihjbdgmphgedojc?hl=en) | Twitter handles for GitHub
[uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) | Finally, an efficient blocker. Easy on CPU and memory.
[unpkg Link](https://chrome.google.com/webstore/detail/unpkg-link/edafhclpiklopbghoeoefdajoadokdcb?hl=en) | Adds a link to unpkg.com for packages on npmjs.org
[Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en) | Speed up, slow down, advance and rewind any HTML5 video with quick shortcuts.

**Comment by kentcdodds** [comment]
Wow @detrohutt! That's quality work right there! Thanks :)

**Comment by detrohutt** [comment]
@kentcdodds Thanks! Any reason you have both AdBlock and uBlock Origin? Just curious.

**Comment by kentcdodds** [comment]
Haha, I got AdBlock first and didn't remove it when I added uBlock Origin. I probably don't need both... I'll disable AdBlock and see what happens :)
