### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [kentcdodds/ama#41]

**Comment by kentcdodds** [comment]
Thanks for the question! I actually talked about this a bit with my fellow boy scout leaders yesterday. In scouts, we use the "EDGE" method for teaching new skills:

- **E**xplain/Educate
- **D**emonstrate
- **G**uide
- **E**nable

So this covers the three [Types of Learning Styles](http://www.learningrx.com/types-of-learning-styles-faq.htm): Auditory Learners (Explain), Visual Learners (Demonstrate), and Kinesthetic Learners (Guide).

But it's that third one, *Enable*, that I think is the most critical and is required regardless of the kind of learner you are. Enabling basically requires the teacher to give the student the things they need to do it on their own. I firmly believe that the only way to master a skill is to do it yourself.

Personally, I think I'm more of a visual learner (maybe a bit kinesthetic as well). So I don't like reading blog tutorials or books (I rarely do). But I also don't like going through hours of video tutorials or courses either. So personally, [egghead.io](https://egghead.io) has been the most effective platform for learning for me (and I'm not just saying that because [I author there](https://egghead.io/instructors/kentcdodds)).

At the end of the day, the most effective learning method for me (and I believe everyone else) is to just do it yourself. So, build something. Hit walls, break through them, break stuff, stumble, cry. These are all things that I think we all need to do to enable us to solidify what we're trying to learn.

I hope that answers your question!

**Comment by kentcdodds** [comment]
I want to add something to this. I personally feel that the pinnacle of learning is teaching. So put yourself in a situation where you have to teach something (training at work, meetup talk, conference talk, etc.) and you'll learn a great deal.

So the process for learning is:

Inform yourself (book, video, tutorial blogpost, whatever works for you)  -->  Build something  --> Teach it

Do that and you'll be amazed at what you can learn.
