### ISSUE TITLE
Just an idea for - DOM snapshot SSR

### ISSUE THREAD

**Issue by bishwenduk029** [kentcdodds/ama#412]
Hi Kent,

Thanks a ton for the free course on react-testing-library at frontendmasters. It was of great help and a very good learning experience. I am using this library extensively in my project and can't think of using anything else but this. 

While working through the test cases, I was just thinking, since we are rendering a DOM version of the component, why not send this rendered DOM as SSR from test server to a browser to get an actual visualization of the component. As this would help in better visual regression identification and a sense of confidence for the code in concern.

Also screenshots of these renders can be saved for concerned people in product management to review. Just an idea do you think it is something which is feasible? and can prove useful. 

This concept can combine best of both world
1.) DOM snapshot comparison by JEST for speedy test runs.
2.) a sense of confidence gained by developer and team with visual verification. (as instead of looking at DOM string they look at actual render in browser).

Regards,
Bishwendu.

**Comment by detrohutt** [comment]
Hey @bishwenduk029  thanks for the suggestion. As the [Guidelines on the README](https://github.com/kentcdodds/ama#guidelines) state, feature requests should be opened at the relevant issue tracker (in this case, [react-testing-library](https://github.com/kentcdodds/react-testing-library/issues/new/choose))

For what it's worth, my opinion is this is not something @kentcdodds would want in `react-testing-library` because he wrote it to be a **lightweight** alternative to enzyme. I'm sure he'll correct me if I'm wrong. ;)

If you're interested in screenshots of your tests, I personally think those are better-suited to end-to-end tests, in which case [cypress.io has you covered](https://docs.cypress.io/guides/guides/screenshots-and-videos.html#) and even offers video capture of the whole test run.

**Comment by kentcdodds** [comment]
Thanks @detrohutt! Also, you might appreciate this: https://www.youtube.com/watch?v=wRrqtI3zVx4&list=PLV5CVI1eNcJi8sor_aQ2AzOeQ3On3suOr

**Comment by bishwenduk029** [comment]
Thanks @detrohutt & @kentcdodds, the video was very informative. I apologize for giving the wrong impression from my question, of asking for a new feature in react-testing-library, I was just thinking of a side project and wanted to know if the idea was worth pursuing. 

I myself love the library just the way it is.
