### ISSUE TITLE
Using react-testing-library for integration testing

### ISSUE THREAD

**Issue by joshmun** [kentcdodds/ama#419]
Hey Kent,

First, really appreciate all the support and work you do for the community! 

Question: I'm using react-testing-library to click through a react component form. I fill out all of the information and hit submit. I'm writing an integration test that expects after filling out the form and submitting, I will be redirected to a summary page reflecting the changes I made on the form. Currently, react-testing-library can get me up to hitting submit, but I'm completely lost on setting up my expectations to check if "Submit" returned me the correct page with requested changes.

Wondering if you could shed any light on this, or if what I am attempting here is outside the scope of what react-testing-library was designed for?

P.S. (really digging react-testing-library, really hoping to switch over from Enzyme if I can figure this out :D) 

Thanks!
Josh

**Comment by joshmun** [comment]
An alternative way to ask this: instead of being returned a summary page, is there a way to evaluate that the "Submit" button sent the correct data from the form?
Thanks!
Josh

**Comment by detrohutt** [comment]
Hey @joshmun integration tests are definitely within the scope of `react-testing-library`. If you're using `react-router` then [this example](https://github.com/kentcdodds/react-testing-library/blob/master/examples/__tests__/react-router.js) should prove useful.

Otherwise, with regards to your alternative question, have a look at [the fireEvent method](https://github.com/kentcdodds/react-testing-library#fireeventnode-htmlelement-event-event) for an example of using a function spy. This specific example uses the `jest` testing framework and doesn't specifically check what arguments the function was called with. However, any testing framework that provides spy functionality should offer a method for that in its API, but that falls outside of the scope of what's built-in to `react-testing-library`.
