### ISSUE TITLE
Using your "The Beginner's Guide to React" as a foundation for a workshop I'm holding

### ISSUE THREAD

**Issue by JReinhold** [kentcdodds/ama#423]
Hi Kent!

I've been asked to hold an introductory workshop to React, for fellow developers who wants to learn about React.

The default thing to do would be to come up with my own material, and just go from there. But I really think that your courses and materials are really great, so I think it would make more sense to just use your ["The Beginner's Guide to React"](https://egghead.io/courses/the-beginner-s-guide-to-react) as a foundation, and then change it a bit to fit my time schedule, audience type, etc.

So, my questions are:

- How would you feel about this? Would you rather that I didn't use your content? I would of course mention you, and that most of the content was created by you.
- Is there anything you would change about the course on Egghead, to make it more suitable to a live workshop, instead of an online course?
- Any other tips/things I should know about the course, and using it in a workshop? (I've already tried to dig around for your answers around workshops in general, but feel free to add anything if you like 🙂)

Thanks!

**Comment by kentcdodds** [comment]
[Here is the workshop version of the material](https://github.com/kentcdodds/learn-react). I have yet to actually give this material in a workshop setting, but I'm pretty confident that it's solid and I will be giving it as a workshop in a few months.

> How would you feel about this?

If you're making money on my material then I'll want to talk about compensation. Send me an email if that's the case. If this is just something for your co-workers or a group of friends or something that's totally fine. Just make sure you credit me for the material.

> Is there anything you would change?

The only thing I would change is `ref` now has a more official API with `React.createRef` and my egghead course doesn't use that (because it was released before createRef came out). The workshop material linked above has `React.createRef`.

Nothing to add about workshopping :) Good luck!

**Comment by JReinhold** [comment]
Thanks for the quick answer! I'll reach you if money is involved. 👍
