### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by oyin-k** [kentcdodds/ama#426]
Hello Kent.
I was going through the Learn-React material on codesanbox and i saw this: 

`function Message( { message } ) { 
   return <div>{message}</div>
}`

I've been trying to figure how this destructuring pattern works. I used the babel playground and this was the transpiled version:

i typed in this: 

`function Message({message}) {
  return {message};
}`

and babel gave me this: 

`function Message(_ref) {
 var message = _ref.message;
  return { message: message };
}`

Ive read about destructuring and i have not still wrapped my head around how this should work.

thanks for the kind response.

**Comment by nathanhannig** [comment]
The syntax Babel spits out is a little cryptic for human eyes. But destructuring is nothing special, it just makes it so you can type less to reference a variable inside of an object.

But what you typed into Babel is a little different than compared to what Kent had typed. In your example, you are returning an object. In Kent's example, he is returning JSX. The {} mean different things between your examples.

Think of his code as the following without destructuring.

```
function Message(props) { 
  const message = props.message
  return <div>{message}</div> 
}
```

**Comment by detrohutt** [comment]
@oyin-k The answer provided by @nathanhannig is correct. To summarize, the `{message}` in `<div>{message}</div>` is not destructuring. It's a feature of JSX called interpolation where the braces let the compiler know that anything inside of them is javascript (which can contain more JSX), and not raw text to be displayed on the page or html-like code.

I'm closing this issue since it's not necessary for Kent to answer this directly because he stays [quite busy](https://blog.kentcdodds.com/hi-thanks-for-reaching-out-to-me-d970e7e6632). If you need more clarification feel free to add more comments. :)

**Comment by oyin-k** [comment]
Thanks guys.

I get it now
