### ISSUE TITLE
A new render props pattern I was trying. Could you take a look at the demo and give some advice? 

### ISSUE THREAD

**Issue by FateRiddle** [kentcdodds/ama#428]
I love your advanced React pattern course on egghead, that's the best advanced course out there imo. Thank you for sharing it with the rest of the world.

Render props is mainly for state/methods reusage. But sometimes you want to reuse the UI along with the state/methods. I wrote 2 demos present my idea, which is similar to compond components, but with more flexibility.

### 1. [codesandbox demo](https://codesandbox.io/s/7o2y6yq0n6)
I wrote a render-prop pattern Pop component, for the common button + modal use case.
<Pop> not only provide state/method `on` and `toggle`, but also the state-wrapped UI like Modal and Button. So then you can write a Modal without explicitly managing states:
```js
<Pop>
        {({ Button, Modal }) => (
          <React.Fragment>
            <Button>Click me!</Button>
            <Modal onOK={() => alert("everything is OK")}>
              <p>Some contents...</p>
              <p>Some contents...</p>
              <p>Some contents...</p>
            </Modal>
          </React.Fragment>
        )}
      </Pop>
```

### 2.  [codesandbox CRUD demo](https://codesandbox.io/s/8xwoqv0zv9)
I expand on this idea and build a more complicated case, where you pop a form and submit values.
Then you can do 
```js
<PopForm>
              {({ Button, Modal }) => (
                <React.Fragment>
                  <Button type="primary">+</Button>
                  <Modal title="Create Info" submit={actions.createItem}>
                    <MyForm formData={formData} />
                  </Modal>
                </React.Fragment>
              )}
            </PopForm>
```

What I'm not sure of is 
1. the way I wrote the render-prop component: I define component inside component so that they can get access to state directly. (you can actual do that for compond components, but I see you define compond one as static, and pass state using context, so ... like why? )

2. whether there are any performance concerns. 
3. I tried to build PopForm upon Pop but failed, as I inevitably define component inside render function

Could you give some feedback as what do you think of this pattern( render-props for not only state reuse but also state wired UI), is it viable and how to improve it?
Thank you!

**Comment by FateRiddle** [comment]
@sapegin Yeah I think we are onto the same pattern. May I see how do you write you FormController component? And what do you mean by " separate layout", can you elaborate on that a bit? Thanks.

**Comment by sapegin** [comment]
I mean that I define all whitespace and the actual layout of a form separately from the “controller” and can have several different layouts of the same form.

And the controller looks like this:

```jsx
class FormController extends React.Component<Props, State> {
  state = {
    showPhotoUpload: false
  };

  handleShowPhotoUpload = () => {
    this.setState({showPhotoUpload: true});
  };

  isImageUploadOpen() {
    return (
      (this.props.showUploadPhotoButtonOnly || this.state.showPhotoUpload)
    );
  }

  isImageGalleryOpen() {
    return this.props.uploadedImages.length > 0;
  }

  render() {
    return this.props.children({
      PhotoUploader:
        this.isImageUploadOpen() &&
        (() => (
          <WARPhotoUploader
            onUpload={this.props.handlePhotoUpload}
          />
        )),
      PhotoGallery:
        this.isImageGalleryOpen() &&
        (() => (
          <WARPhotoGallery
            images={this.props.uploadedImages}
            onDelete={this.props.deletePhotoClick}
          />
        )),
      CommentField: () => (
        <ReviewFormCommentField />
      ),
      SubmitButton: () => (
        <Button
          type="submit"
          fullWidth
          disabled={this.props.isSubmitting}
        >
          <Lnrs key="Submit">Submit</Lnrs>
        </Button>
      ),
      UploadButton:
        !this.isImageUploadOpen() &&
        (() => (
          <Button
            variation="alternate"
            onClick={this.handleShowPhotoUpload}
            fullWidth
          >
            <Icon iconId="camera" />
            <Lnrs key="AddPhoto">Add Photo</Lnrs>
          </Button>
        )),
      SkipModerationCheckbox:
        this.props.adminBypassingOfModerationIsEnabled &&
        ReviewFormSkipModerationCheckbox
    });
  }
}
```

**Comment by FateRiddle** [comment]
@sapegin You're defining component inside render function, and I believe that will cause problems, as explained [here](https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method), that for each render the previous subtree will be unmounted completely. It happened on my 2nd demo, whenever I type in the Popped form, everything will rerender. Not sure about you case, but if this is true, you might do
```js
MyUploadButton =
        !this.isImageUploadOpen() &&
        (() => (
          <Button
            variation="alternate"
            onClick={this.handleShowPhotoUpload}
            fullWidth
          >
            <Icon iconId="camera" />
            Add Photo
          </Button>
        )),

// then in render() 
UploadButton: this.MyUploadButton,
```

**Comment by detrohutt** [comment]
@FateRiddle It's unlikely Kent is going to have time to look over all this code, so I'll do my best to answer your questions.

#### Thoughts about the pattern

I attended Kent's Advanced React Patterns online workshop where he taught this material live. He mentioned multiple times that he likes the render prop pattern because it allows separation of concerns between UI and "business logic". Your pattern is "unseparating" those concerns, thereby losing the most important benefits of the original pattern in my opinion. As soon as you start putting UI code into your render prop component, all the code becomes harder to comprehend because you've added the mental overhead of deciding what's UI code and what's logic code.

> But sometimes you want to reuse the UI along with the state/methods.

What Kent recommended in the workshop was using the render props pattern to create a base component and then creating separate components (probably in separate files) for each different use-case of those methods/state. For instance you can have separate components for mobile and desktop, both using the same base component for state/methods.

In more complex use cases, you can build a component up in layers, adding more specific UI code each time you extend the component, and then use the most generic "level" of that component that fits the current use case as your new "base" component.

#### Specific questions

1. First I don't think Kent even uses compound components all that often, since you can accomplish the same thing with more flexible patterns (see [this tweet](https://twitter.com/kentcdodds/status/984204410283810816)). But during the workshop he mentioned that you don't *have* to make them static, he just likes to because it makes the usage more explicit. Context is the simplest way to pass the state while keeping the separation of concerns.

2. Performance concerns are going to vary by project. Unless you're doing something very expensive when creating/rendering your components, React isn't normally going to be your bottleneck. Profiling is the best way to determine if there are performance concerns. Use profiling to determine where your actual bottlenecks are and then only optimize those things which are having a noticeable impact on performance.

3. I'm not sure I totally understand what you were attempting to accomplish here, but I think if you follow my previous advice, this won't be an issue.

#### Asides:

1. I noticed you moved your context creation into a file called `context.js`. There's not much point in doing this IMO since you have to import that context wherever you're going to use it and it only takes one line (the same as importing) to create the context, so you may as well just create the context inline where it's being used. If you need to reuse it in multiple places, you can just export it where you're creating it, which will also make it easier to find the data that's provided with that context, since there's one less level of indirection.

2. I noticed you used an array index as your `key` prop. The React docs recommend [not doing that](https://reactjs.org/docs/lists-and-keys.html#keys) in most cases. I'd recommend reading [this blog post](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318) which is linked to in that same docs section.

**Comment by FateRiddle** [comment]
To be honest I think I don't agree with you on some points, like saying this pattern hard to comprehend.  But mostly I'm grateful for your review. Thank you. 
>What Kent recommended in the workshop was using the render props pattern to create a base component and then creating separate components (probably in separate files) for each different use-case of those methods/state. For instance you can have separate components for mobile and desktop, both using the same base component for state/methods.

I've got no idea how to create specific components base on the render props component.
Like in demo 1, if Pop is a render props that only encapsulate states, then to use it, you probably do
```js
<Pop>
        {({ toggle, on }) => (
            <button onClick={toggle}>Click me!</button>
            <Modal  visible={on} >
                  hello world
            </Modal>
        )}
      </Pop>
```
How do you make a higher level of encapsulation?

**Comment by detrohutt** [comment]
> saying this pattern hard to comprehend

I just said it was hard-**er** to comprehend because you now have two concerns (UI and logic) mixed together which definitely increases the complexity by some degree compared to having them totally separated. I'm not saying people couldn't understand this pattern, just that the way Kent uses it is easier to understand.

> How do you make a higher level of encapsulation?

Just put `export default` in front of the code from your last message and save the file as `HelloPop.js`. ;)

**Comment by FateRiddle** [comment]
Hi, @detrohutt @sapegin I've finally reached @kentcdodds on egghead. Here's what he thought about this pattern:
>Oh yes, it does work if you change the API to a render prop. It's great 👍 I've never found a use case for that myself. When doing a render prop API, they have everything they need to render whatever they like and I don't like imposing those components in them. So I've never done it myself, though I've seen other libraries adopt this pattern. I have no real problem with it and I think it could be useful for common use cases for your Component 👍
