### ISSUE TITLE
internalSetState method question

### ISSUE THREAD

**Issue by bratsos** [kentcdodds/ama#464]
Hello! I just watched Kent's (awesome) video [Simply React practice run
](https://www.youtube.com/watch?v=woA9h3oqCLw) when he talks about a pattern that allows you to expose a way to manage your reusable component's state from another react component.

[Link](https://codesandbox.io/s/1qo7rylm14)
Relevant code example:

```
class Accordion extends React.Component {
  static defaultProps = {
    stateReducer: (state, changes) => changes,
    onStateChange: () => {},
  }
  state = {openIndexes: [0]}
  getState(state = this.state) {
    return {
      openIndexes:
        this.props.openIndexes === undefined
          ? state.openIndexes
          : this.props.openIndexes,
    }
  }
  internalSetState(changes, callback = () => {}) {
    let allChanges
    this.setState(
      state => {
        const actualState = this.getState(state)
        const changesObject =
          typeof changes === 'function' ? changes(actualState) : changes
        allChanges = this.props.stateReducer(actualState, changesObject)
        return allChanges
      },
      () => {
        this.props.onStateChange(allChanges)
        callback()
      },
    )
  }
  handleItemClick = index => {
    this.internalSetState(state => {
      const closing = state.openIndexes.includes(index)
      return {
        type: closing ? 'closing' : 'opening',
        openIndexes: closing
          ? state.openIndexes.filter(i => i !== index)
          : [...state.openIndexes, index],
      }
    })
  }
  render() {
    return this.props.children({
      openIndexes: this.getState().openIndexes,
      handleItemClick: this.handleItemClick,
    })
  }
}
```

My question is, how's that different from just passing the `this.setState` method as an argument to your `this.props.children` function? That way, anyone that uses your component's render prop would be able to update components local state according to their needs. What are the benefits of implementing an internalSetState method like that?

Thanks for your time and your awesome videos/posts!

**Comment by kentcdodds** [comment]
Hi @bratsos!

It's different because there's less for the user to know/do. There's something to be said for flexibility, but there's something to be said for constraints as well. "Tie your hands to free your mind."

Now, if you want ultimate flexibility with this kind of API, you may consider [@reach/component-component](https://ui.reach.tech/component-component) which I think is pretty awesome.

In downshift, we actually do expose [setState](https://github.com/paypal/downshift/blob/444e76eeb6e1697bca55cfb3273af7bce52d31e2/src/downshift.js#L481) (it's undocumented because it's a little too powerful and generally should not be needed). It's all a balance of flexibility and ease of use/simplicity.

I hope that helps. Good luck!
