### ISSUE TITLE
How did you pick your next company/project?

### ISSUE THREAD

**Issue by arahansen** [kentcdodds/ama#47]
So first of all, congrats on landing the role at PayPal!

My question for you is: how did you eventually figure out that PayPal was the next step for you? What was your research process in finding a company that you want to work for that is building a product that you want to build?

What's really important to me in my full-time position is working on a project that I find particularly interesting; A project that I will be intrinsically motivated to put forth the best I can because it's a product that I really really want to see succeed. 

Where do you look for the companies that might be building such a product?

**Comment by manekinekko** [comment]
+1

**Comment by kentcdodds** [comment]
Hi @arahansen! Thanks for the congratulations and the question!

Here are my criteria for a job:

- Pay that satisfies my family's needs (I'm married and have three kids and a mortgage)
- Solid product/company I can get behind (wont work on something I'm morally opposed to) and get excited about
- Good work environment where I feel comfortable and safe
- Autonomy to do the work that I (and my team mates) feel is best (as opposed to management dictating and micromanaging)
- Ability to use leading edge technology (rather than 10 year old dinosaur tech which some people just call "battle tested" ......)
- Ability to work with the web and JavaScript (though I'm open to stuff like [Elm](http://elm-lang.org/)).
- Work with intelligent people I can learn from who have different experiences from me

And for me at this time in my life, I'm also really interested in working with React, but that will change eventually.

So, for PayPal:

- Pay - solid
- Product/company - Cool, diverse company reinventing themselves. Building something that people use to send money to their families to keep them clothed and fed. Solid
- Work Environment - I'm working from home. I feel totally comfortable and safe
- Autonomy - If what @jamischarles and @xjamundx have told me is true, and based on conversations with our director, PayPal's got this too.
- Leading edge tech - They're using React and Redux in many areas and migrating from Backbone to that in many others.
- JavaScript and the web - yup!
- Intelligent people - @jamischarles and @xjamundx - solid

As for looking for companies... I didn't actually look for this one. This all started [on Twitter](https://twitter.com/kentcdodds/status/651124199537283072):

![screen shot 2015-11-30 at 9 27 37 am](https://cloud.githubusercontent.com/assets/1500684/11477310/a7b16998-9744-11e5-9156-d03781b239ec.png)

@jamischarles followed-up with a DM... Totally calling my bluff :-)

![screen shot 2015-11-30 at 9 29 17 am](https://cloud.githubusercontent.com/assets/1500684/11477385/f94ccdf6-9744-11e5-83be-cee1cccd8c37.png)

One thing led to another, I built a thing for them (which I don't think I should really show you, but if you're curious enough you might be able to find it), I flew out there and interviewed, I got an offer, I accepted, and I start in the next few weeks! I'm super stoked :-)

Thanks for the question!

**Comment by kentcdodds** [comment]
I should note also that being involved on GitHub and Twitter has served me extremely well on the getting noticed an interview offers front. I highly recommend that if you've been resistant to being involved in Twitter, that you get over it :-) And if you're looking for ways to be involved in GitHub, check out my series on [egghead.io](https://egghead.io/series/how-to-write-an-open-source-javascript-library) (another one coming eventually which talks about how to contribute to existing projects).

Cheers!
