### ISSUE TITLE
Your opinion on MobX?

### ISSUE THREAD

**Issue by jbstewart** [kentcdodds/ama#471]
I heard you speak at OpenWest and really enjoyed your presentation. One thing that I liked about your presentation was how you suggested a migration of state solutions from simple to complex, beginning with using setState() and ending with Redux. I've been a professional software developer for 31 years, and build for native desktop, as well as native mobile (and a little web), so learning APIs is no problem for me, but I find Redux (and Flux) to be (perhaps) needlessly complex - at least for applications at my scale. And to be honest, it sort of seems like an over-application of functional programming. I've nothing against FP - but you've got to use the right tool for the job, and sometimes OO is the right tool. I've read a little about MobX. I'm starting a new side project, and need to know what state-management tool to try first, and I wondered if you had any experience with it?

**Comment by kentcdodds** [comment]
Hi @jbstewart!

I've never used MobX, but the reason is because it relies heavily on mutation and that's just not something that I can get behind. As an AngularJS user, I was constantly trying to track down where/why some value was getting set causing a render bug or some other issue. It was a bit of a nightmare that I don't wish to repeat. This is the same reason that I have no interest in Vue. I much prefer the explicitness of `setState`. Much easier to follow/know what's going on. `dispatch` from redux is a bit better, except it's indirect and I spent a fair amount of time following code paths through several files with redux, which is why I try to steer clear of redux.

One other solution that has caught my eye is https://github.com/aweary/react-copy-write. That looks interesting. Another one that looks interesting is https://github.com/pedronauck/reworm

Lots of opportunities for solutions here. Just make sure you keep your state as close to where it's needed as possible. Most state in an app does not need to be globally accessible :)
