### ISSUE TITLE
Tips/tricks on how to start writing my 'own' library: the 2018 edition

### ISSUE THREAD

**Issue by MichaelDeBoey** [kentcdodds/ama#473]
Hi Kent!

Just a 'small' question for you.

At our company we're using a library, which is fully written in CommonJS.

Since it's a pure frontend library, I think it would be better that it's written in ES6 (that's what I'm reading all over the internet anyways).

So as a contribution back to the community (and to learn something too of course), I'd like to make them a PR with the conversion to ES6.

That's why I'd like to ask you if you have some thoughts on this and maybe know some good places on how to start writing my "own" library **these days**.

Do I still need to export it in CommonJS or is ES6 a better choice?
If so, do I just run `babel` on it or do I run it through `webpack`/`rollup`?

Thank you very much for all your time you're putting into answering this for me!

Kind regards,

Michaël

**Comment by kentcdodds** [comment]
Hi @MichaelDeBoey!

I don't really care how you author your libraries, but I strongly recommend that you expose a transpiled version of the library that works in the environments you want to support without a bunch of work on the user's part (browsers/webpack/etc.). Otherwise, you'll find adoption more tricky.

For me, I use `rollup` with my `kcd-scripts` project: https://github.com/kentcdodds/kcd-scripts

You may also consider using https://github.com/developit/microbundle

I hope that's helpful!
