### ISSUE TITLE
Thoughts on your "boulevard of broken dreams" video?

### ISSUE THREAD

**Issue by ehhthing** [kentcdodds/ama#474]
Hi Kent! 

I found you through [this](https://youtu.be/IiDQwQQsrL8) video you uploaded nearly 12 years ago. This video has since become a meme on the internet. However, when people search for "boulevard of broken dreams", they often get the same video uploaded by a different person. I am sure you are aware of this, yet you choose not to copyright strike the video.

I was wondering why you choose this, what you think about the original video and what it represents.

Larry.

**Comment by kentcdodds** [comment]
Yeah, someone mentioned this too me a while back: https://github.com/kentcdodds/ama/issues/290

I haven't taken any action against the thief because I honestly don't really care. I'm mostly flattered that 13-year-old me created something that's getting so much attention. It is frustrating that I'm not getting the credit for that, but I don't have the time to raise a stink about it anyway. On top of that, if I did and the video was taken down, what good would that cause? People wouldn't be able to find the video as easily (all links would be broken). I just want to let people continue to enjoy it.

What do I think the video represents? It represents a 13-year-old kid who decided he wanted to dork around on the computer so he could upload videos to the internet (Google Video at the time actually). Don't look into it too deeply. If you are curious to learn more about teenage Kent, you can watch this: https://www.youtube.com/watch?v=KTjNhpUWe_s

Thanks for watching :)
