### ISSUE TITLE
What is your advice about learning javascript roadmap 

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [kentcdodds/ama#484]
Hi @kentcdodds  
I hope you are having a good time.

I am a javascript developer for 4 years durning those year I have been working 60h/week only on javascript project . 
I feel like I know basic and intermediate things and keep looking over internet but there are no more free think or at least paid one , or I am not looking on right places.
I just really want to learn more and more but still fell like I know most of them.
Some suggesting would be great I really like you job and what you have done so far.

Kind Regards

**Comment by kentcdodds** [comment]
Hi @EsmeraldiBejolli,

The best way to learn is to teach. I talk about this a bit in my talk [Zero to 60 in Software: How to jumpstart your career](https://www.youtube.com/watch?v=-qPh6I2hfjw).

The thing is that it takes a lot of effort to prepare educational materials, especially for advanced topics which is why you're finding there's less free material available for the topics you are trying to learn. So what I recommend is you do the leg-work to prepare the materials that you wish existed. You'll learn a lot in the process. Good luck!
