### ISSUE TITLE
Scripture Study

### ISSUE THREAD

**Issue by alexanderson1993** [kentcdodds/ama#485]
Hey Kent! 👋

In your latest newsletter, you said you started your day with scripture study. What are you studying right now? How do you do your scripture study? What value do you get out of it? Do you study with your family/wife, and how does that go?

Alex

**Comment by kentcdodds** [comment]
Hey @alexanderson1993!

So at the time I was somewhere in [Alma](https://www.lds.org/scriptures/bofm/alma?lang=eng) but I've since started over because of the prophet's recent challenge to read the whole Book of Mormon cover to cover before the end of the year. I love doing fast readings of the Book of Mormon. It gives a perspective that you don't get going a chapter per day or whatever. I just finished [Mosiah 8](https://www.lds.org/scriptures/bofm/mosiah/8) today. I'm actually listening to the scriptures this time around (there's no way I'd have time to read the whole thing otherwise because I'm pretty slow reader) and it's going great.

> What value do you get out of it?

There are countless gems in the stories and principles that I learn from the scriptures. Every time I read the scriptures I pick up on things that apply better to my life today than the last time I read that particular scripture. Recently I read [Jacob 2:8-9](https://www.lds.org/scriptures/bofm/jacob/2.8-9?lang=eng#p8) and it reminded me that if I keep the commandments and strive to be the best I can be, the Lord will bless me with even more knowledge. And in [Mosiah 2:22-24](https://www.lds.org/scriptures/bofm/mosiah/2.22-24?lang=eng#p22) I was reminded that the Lord blesses us for doing the things He's asked us to do and we have every reason to be grateful to Him for that. And then later in [verse 41](https://www.lds.org/scriptures/bofm/mosiah/2.41?lang=eng#p41) I'm reminded of the blessed and happy state of those that keep the commandments of God. This is consistent with my life experience.

> Do you study with your family/wife, and how does that go?

Yes, our kids are pretty young and can't read yet so it's a bit of a challenge. Right now we just read one verse together where I'll say a short phrase and they'll repeat what I said. At this point the habit is more important to develop than actually getting deep insights from what we're reading. We'll get to that as they grow older. We do other things to give them the insights they need.

Thanks!
