### ISSUE TITLE
Story points estimate when the libraries/frameworks evolves which reduces complexity

### ISSUE THREAD

**Issue by ahmedam55** [kentcdodds/ama#498]
I've read a lot about Agile and worked at several companies that applies Agile, and read a lot on MountainGoat.com. 

The issue is, I've always had this question in mind: ok, I know the story points are the combination of complexity, amount of work to be done, risk, and uncertainty. But the question is, for example if we considered developing a large form using jQuery, that is extremely complex, because of the variables/data to DOM mapping and keeping them in sync with amount of different scenarios.

Now, imagine that we migrated to React or Angular which manages the DOM itself, then the complexity then is a lot less. Do I still estimate it with the same old complexity, so the velocity can be computed correctly or estimate it with the less complexity and if so, how would the velocity be computed?

The other question is, imagine I'm already using React and it's not that complex to do this task using it, but it's complex to do it using jQuery or vanilla JS. What determines the level of complexity?

I really hope you can help me, given that you already helped me be a better developer and human in general with your enormous contribution to the community.

Can't thank you enough.

**Comment by jlengstorf** [comment]
I landed here from a DM link, so forgive me popping in with advice. 😄 

To make sure I'm understanding this correctly, let me repeat it back:

1. You have a project that was historically very complex (a jQuery form where everything is manually managed)
2. Because this is historically complex, it would have velocity benchmarks based off of previous estimates and story points
	- For example, working on this form has historically meant X story points, and our velocity is Y
3. By switching to a new framework, you're significantly reducing complexity
4. This leads to a lower required estimate
5. This means your velocity is increased (more done in less time) but — due to the lower estimate — could actually result in the appearance of _decreased_ velocity

Am I getting this right?

Assuming I've understood correctly, I'd recommend not stressing about this too much. The risk of artificially inflating complexity to not affect a velocity calculation is probably not a good idea because it makes those numbers meaningless (e.g. you're making things up now, so the measures no longer matter).

Beyond that, measurements like "velocity" are proxy metrics for actually getting work done. Focusing too much on the proxy metric distracts from the actual goal, so my advice would be to not overthink it. If you've found a solution that makes you significantly more effective, document that for your team, keep it in your pocket for your next review, and then continue getting things done. Be clear with your team that the changes mean that whatever piece of the codebase is now vastly simplified, so previous measurements won't match up.

I hope that helps. Good luck!

**Comment by ahmedam55** [comment]
The issue is, dealing with managers or scrum masters who are very fixated on the number of story points being achieved and hold that as the metrics of whether you're doing your job or not. Unfortunately I've faced that at more than one company, which why I'm asking. Any suggestions?

**Comment by jlengstorf** [comment]
In all honesty, if that's the case, they're doing a broken version of agile, so you have to break your reporting in a way that makes them happy (e.g. inflate complexity estimates to match the old codebase) even if it makes the measures meaningless. If they aren't interested in objective measures of progress, you just have to learn how to achieve whatever their subjective measures are. /shrug

I realize that's not a super helpful answer, but once you run into "I do it like this because it's _my_ way," your options are pretty limited.

**Comment by ahmedam55** [comment]
That's extremely helpful! Thank you so much for that 😊

**Comment by ahmedam55** [comment]
I know you hate me now (I'm so sorry for my several questions). 

Regarding the reference story. Say, if we have the reference story as a page that have three fields and a submit button. Now, that kind of represents or works well as a reference story for front-end developer, what about backend developers or even dev ops. How do they estimate the story points of their stories accordingly. Should the team then create different reference stories for each discipline or there is a standard way of solving this issue?

**Comment by jlengstorf** [comment]
I've never seen a standard way of solving that, sorry.

**Comment by ahmedam55** [comment]
Thank you again for your helpful answers and of course your precious time.
