### ISSUE TITLE
limits to preferences

### ISSUE THREAD

**Issue by mvolkmann** [kentcdodds/ama#50]
You have written about how various frameworks are better suited to the way some people think. You have also written about how coding styles can be preferences, somewhat implying that developers should be free to code in their preferred style. How do you balance those viewpoints with what is best for a project, team, or company?

Many companies want to standardize on frameworks and coding styles because they feel it cuts down on time to come up to speed on a project and makes it easier to move developers between projects.

Do you advocate that each developer should code in whatever style they like? Should each file follow one coding style? Should all files in a project follow the same coding style? Are you okay with each web app in a company being developed using a different framework?

**Comment by kentcdodds** [comment]
Hi @mvolkmann!

Thanks for the question. It's a really good one.

I've recently been on a kick of trying to determine the objectivity vs subjectivity of things we do in software development. Identifying what is objectively better and what is subjective totally changes the conversation for stuff (like [semicolons](https://medium.com/@kentcdodds/semicolons-in-javascript-a-preference-dd8fc8b80895) for example). It makes it easier to know what's important to fight for and what doesn't actually really matter (turns out, most things are subjective and don't actually matter).

So, me identifying what is purely preference and what is actually objectively better doesn't mean that I'm suggesting people do whatever they want in any file/project/etc. I'm a huge believer in tools like [ESLint](http://eslint.org/) for keeping a standard for a codebase. I definitely feel a single codebase should share standard patterns, style (for the most part), etc.

From a company standpoint, I think that there's value in keeping technology similar throughout projects. This is one of the benefits of going all in on the web. Stuff like [Ionic](http://ionicframework.com/), [React Native](https://facebook.github.io/react-native/), [Native Script](https://www.nativescript.org/), and [Appcelerator](http://www.appcelerator.com/) do for mobile and [electron](http://electron.atom.io/) does for desktop.

At the same time, I think that it's valuable to allow your employees to experiment with different technologies. For example, I became a better Angular developer when I toyed around with React.

I hope this answers your question! Thanks for asking!
