### ISSUE TITLE
FOMO

### ISSUE THREAD

**Issue by ColadaFF** [kentcdodds/ama#51]
Do you have "Fear of missing out" in dev, like you wanna know anything new on you current dev world?
And if you don't, how do you handle that?

**Comment by kentcdodds** [comment]
Hi @ColadaFF! Thanks for the question.

My goodness **yes!** There is so much to learn in the world. I don't know how I could possibly even keep track of it all let alone learn it.

It's interesting, I used to work at [Domo](http://www.domo.com/) and I had lunch with some of my former co-workers @aaronfrost and @iammerrick and I mentioned that I sometimes wonder if I made the wrong decision in leaving Domo. If you're not familiar with Domo, they're a business management platform that has [more upside](https://www.instagram.com/p/-wUM95TJkP/) than any other unicorn out there (like AirBnB, Uber, Slack, Pinterest, SpaceX, Dropbox, and Snapchat) based on [CB Insight's recent Billion Dollar Bracket](http://siliconslopes.com/blog/2015/10/29/who-would-you-invest-in-domo-reaches-top-8-in-cb-insights-billion-dollar-bracket/).

Domo was an amazing place to work, mostly because of the people I worked with. But I left so I could experience new things and take on more responsibility (I felt like it was hard to do that being so new and surrounded by so many other amazing developers). But all of that said, I wonder if I could have made a big impact at Domo and built the next big thing with some of my best friends. So do I have FOMO for Domo? Yes I do!

But, at the same time, I've had some solid experiences and I have really learned and grown a lot over the last year and a half. It's been awesome. As @iammerrick said: "You'll never know." It's true...

I'm actually now leaving my current company Alianza for PayPal. There's a bunch of fear of missing out there. Before my PayPal offer, I got an offer from Facebook but turned it down because I don't want to move my family out to California. A **ton** of fear of missing out there too. I even was asked to interview for the Angular team but turned it down for the same reason. I'm seriously missing out on so much!! It's crazy! And I'm terrified!

Sorry, back to technology stuff. So there are several things that I'd like to learn more about and spend more time with. Couldn't name them all, but stuff like Elm, ClojureScript, Om, Angular 2, React, Cycle.js, RxJS, TypeScript, ASTs, Babel Plugins, ESLint Plugins, Webpack, browserify, D3, Canvas, and more importantly, raw JavaScript and DOM APIs. I don't know any of this stuff as much as I'd like to.

We are all stewards of our own time, so we do the best with what we have. The lack of time is the reason that I left [Angular Air](http://angularair.com/) so I could have time to start [JavaScript Air](http://javascriptair.com/). I just don't have time to do both.

So... I totally have FOMO. But I just deal with it. Accept it. One step at a time...

Thanks for the question.

**Comment by vasanthk** [comment]
@kentcdodds Great answer. Thanks for the insights :)
