### ISSUE TITLE
How do you Lint your TypeScript code?

### ISSUE THREAD

**Issue by shahzaibkhalid** [kentcdodds/ama#525]
Hi, Kent.

As you recently stated that you've been moving towards TypeScript and using ESLint to lint your code. I've a couple of questions.

- Why you decided not to use TSLint?
- Are you using `typescript-eslint-parser` and `eslint-plugin-typescript`?
- I am a huge fan of `eslint-plugin-import`, `eslint-plugin-jsx-a11y` and `eslint-plugin-react` and I uses them in almost all of my projects. Do you use them or any variant?
- Can you post your ESLint configurations?
- Why do you think TypeScript is better then Flow? (When you tweeted: Migrating from Flow to TypeScript seems like Breath of Fresh Air. 😅)

Thanks so much, Kent!

**Comment by kentcdodds** [comment]
Hi @shahzaibkhalid!

> - Why you decided not to use TSLint?
> - Are you using typescript-eslint-parser and eslint-plugin-typescript?

I answered these questions in my livestream today:

https://www.youtube.com/watch?v=Pl2heYVwQ-Q&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

> I am a huge fan of eslint-plugin-import, eslint-plugin-jsx-a11y and eslint-plugin-react and I uses them in almost all of my projects. Do you use them or any variant?

Yes, I use all of those.

> Can you post your ESLint configurations?

I need to update them for TypeScript, but here's what I have today: https://github.com/kentcdodds/eslint-config-kentcdodds

> Why do you think TypeScript is better then Flow? (When you tweeted: Migrating from Flow to TypeScript seems like Breath of Fresh Air. 😅)

I'll write a blog post about this.

Cheers! 🥛🍺

**Comment by mucsi96** [comment]
@kentcdodds Thanks for you podcast on linting TypeScript using eslint! 💯 

It's quite sad the currently we have two separate tools for linting JavaScript code. eslint and tslint. I am really waiting that these two tools merge together. What do you think about this?

Other thing is I am not sure I understand correctly, but do you think that with using eslint instead of tslint you loose all advantages of TypeScript during linting as all type information is basically lost. Not sure how tslint is working and how it is collecting the type information from all the source code just to lint a single file. 

For example in tslint there is a rule called [`no-floating-promises`](https://palantir.github.io/tslint/rules/no-floating-promises/), It's very useful as it's able to prevent a bug of not using await for an async function. It uses type information to detect it and it's not possible to implement in eslint. I am sure there are many other useful plugins which are able to make use of the type information.

Cheers and keep up the great work! 👍

**Comment by kentcdodds** [comment]
Hi @mucsi96,

Actually this rule is built-into eslint: https://eslint.org/docs/rules/require-await

I'm sure there are some things I could do with the type information, but I'm pretty sure that pluggable-babel-eslint (and eventually babel-eslint) will provide that type information to eslint plugins so it would be just as capable.

> Maybe it worth to use both eslint and tslint for different rules until there are not merged.

I wouldn't recommend that. Tooling overload 😬

**Comment by kentcdodds** [comment]
> Is pluggable-babel-eslint doing a complete type analysis of the whole code-base?

No it's not. I can see how this could be useful. Maybe one day I'll warm up to TSLint, but for now ESLint is where my current stuff resides and I'm going to stick with it.

**Comment by mucsi96** [comment]
I completely agree with you. I also prefer using eslint. It's much more popular, has more rules and plugins and better maintained. Just there some very nice things which can be checks based on type information on whole code-base. More capable linting is always better I think. I hope in the future we can have this information in eslint as well and based on that we can create even better and more sophisticated rules.

**Comment by mucsi96** [comment]
Sorry for still writing here. I thought maybe you are still interested 🙄 . I just found a very nice react typescript [cheat-sheet](https://github.com/sw-yx/react-typescript-cheatsheet). They use both eslint and tslint in [parallel](https://github.com/sw-yx/react-typescript-cheatsheet#eslint--tslint).
