### ISSUE TITLE
Why are there so many good developers and business people in Utah? 

### ISSUE THREAD

**Issue by wesbos** [kentcdodds/ama#55]
I'm always amazed at how productive developers and how successful businesses are from Utah. I know the Mormon work ethic is pretty engrained in the state. What are your thoughts on why?

**Comment by kentcdodds** [comment]
That's an excellent question. I often find that people are surprised when they hear that Utah is booming so much in the tech world (particularly JavaScript) or if they already know they often ask this question. We call this area [Silicon Slopes](http://siliconslopes.com/). It really is a gem for software companies and developers. We have a ton of successful companies (not the least of which is my former employer [Domo](https://www.domo.com/) which has [more upside](https://www.instagram.com/p/-wUM95TJkP/) than any other unicorn out there (like AirBnB, Uber, Slack, Pinterest, SpaceX, Dropbox, and Snapchat) based on [CB Insight's recent Billion Dollar Bracket](http://siliconslopes.com/blog/2015/10/29/who-would-you-invest-in-domo-reaches-top-8-in-cb-insights-billion-dollar-bracket/). Crazy cool right?

Anyway, before I get to your question I should probably start out with the fact that I am [Mormon](https://www.mormon.org/) ([Merry Christmas!](https://www.mormon.org/christmas)) and I'm pretty typical. I grew up in Idaho in a huge family. All of my family are active members of the church, many of us went on [missions](https://en.wikipedia.org/wiki/Mission_(LDS_Church)), all of us attended [BYU](https://byu.edu/), I met my wife there, we were married in [the temple](http://temples.lds.org/), we now have three kids and stayed here in Utah. So yeah, pretty much your stereotypical Mormon guy.

To answer your question, perhaps the Mormon work ethic has something to do with it, but I think that there are probably a few more factors that make this area so awesome for software companies and developers. I think that part of it has to do with the fact that lots of people prefer to stay around here in Utah because it's a nice place to live. So we've hit it pretty big with a few tech companies founded by people who wanted to stay in Utah.

A few that come to mind for me... [Word Perfect](https://en.wikipedia.org/wiki/WordPerfect) ([Alan Ashton](https://en.wikipedia.org/wiki/Alan_Ashton_(executive)) was my [bishop](https://en.wikipedia.org/wiki/Bishop_(Latter_Day_Saints)) and he's totally awesome), [Omniture](https://en.wikipedia.org/wiki/Omniture) (founded by [Josh James](https://en.wikipedia.org/wiki/Josh_James) who's running wild with [Domo](https://en.wikipedia.org/wiki/Domo_(company)) now), [Workfront](https://en.wikipedia.org/wiki/Workfront) (formerly AtTask), [Inside Sales](http://www.insidesales.com/), [Instructure](https://www.instructure.com/), [Plural Sight](https://www.pluralsight.com), and [a bunch more](http://siliconslopes.com/companies/).

If I had to state a reason, I think that it mostly just started out as a few people who wanted to build something awesome, but didn't want to leave Utah to do it. So they just did it here in Utah and the community grew to support the demand. And I'm super pleased! I just turned down a few solid opportunities in the bay area because I don't want to leave Utah (more on that [here](https://github.com/kentcdodds/ama/issues/47)).

Thanks for the question! I hope that my answer was insightful :-)

**Comment by kentcdodds** [comment]
I should note that with all of that said, we're really nothing compared to the bay area. But this area has the added benefit of not costing an arm and a leg to live here :-)

**Comment by ryanflorence** [comment]
Lots of talent (from developers to CEOs to VCs) stick around because of family/cultural ties, creating a lovely tech scene with plenty of jobs.

Somehow I made it out though :cry:

**Comment by kentcdodds** [comment]
Basically @ryanflorence summed up in 30 words what took me about 400 words... Thanks for the TL;DR Ryan :-)

**Comment by wesbos** [comment]
👌 Great response - very interesting. Thanks for sharing - I'll have to come visit Utah some day and have some of this Soda you are so crazy about!

**Comment by kentcdodds** [comment]
I'll take you out to lunch any time :-)
