### ISSUE TITLE
What do you think about ES2015?

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/ama#6]
Previously known as ES6. Have you used it?

**Comment by kentcdodds** [comment]
I have a hard time calling it ES2015 to be honest. I'll probably be on board with ES2016, but ES6 is ES6 to me :-)

I started working in primarily ES6 around February 2015. Now it's all I code in pretty much. Looking at [this list](https://github.com/lukehoban/es6features) of features, I'm a huge fan of:

- arrows
- enhanced object literals
- template strings
- destructuring
- default + rest + spread
- let + const
- unicode
- modules
- module loaders
- promises
- math + number + string + array + object APIs

Haven't used/experienced:

- iterators + for..of
- generators (Excited to see my potential use-cases here)
- map + set + weakmap + weakset
- proxies
- symbols
- subclassable built-ins
- tail calls (I'm sure I'll love this)
- reflect api

Indifferent to

- binary and octal literals

Not a huge fan of:

- classes (I think I'm a functional programmer)

---

When I moved my work project over to webpack, it was really easy to add in 6to5 (now [Babel](http://babeljs.io/), which is [pronouced "babble"](https://twitter.com/babeljs/status/567383101249056768)) to my project and from there it has totally infultrated my code and my active open source projects.

I actually gave [a talk](https://github.com/kentcdodds/talks#es6) on ES6 at [a local meetup](https://github.com/kentcdodds/es6-workshop) using [a fork](https://github.com/kentcdodds/es6-workshop) of @aaronfrost's and @rauschma's [es6 workshop](https://github.com/aaronfrost/es6-workshop) (tests migrated from jest to mocha because performance...). 

A few weeks later I gave [a talk](https://github.com/kentcdodds/talks#es6-webpack-karma-and-code-coverage) at [another local meetup](http://www.meetup.com/UtahJS/events/222630472/) about getting code coverage for tests in projects using ES6, Webpack, and Karma.

I'm also giving a day training at [Midwest JS](http://midwestjs.com/) this year about ES6 which I'm totally stoked for :-)

So yeah, I've used it, and I love what it provides. I'm really looking forward to ES2016 :D
