### ISSUE TITLE
Self-expiring react component

### ISSUE THREAD

**Issue by karlasamantha** [kentcdodds/ama#613]
What would be the best approach for a self-expiring react component? Meaning after a certain date, the component would unmount itself from the DOM. 
Thanks a lot!

**Comment by kentcdodds** [comment]
Hi @karlasamantha! This was a great question for the livestream today: https://www.youtube.com/watch?v=b55ctBtjBcE&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

I hope that helps!

https://codesandbox.io/s/wyz60jr218

**Comment by weyert** [comment]
I really enjoyed this video. I was just wondering how would you use react-testing-library to test this useExpiration hook?

**Comment by elertan** [comment]
Hi @kentcdodds , I would like to ask why you decided to make the component return null instead of removing the component from the render tree itself (from it's parent component)? This seems like a potential performance issue when used in combination with some sort of list view (e.g. a messaging app), where the components still exist in the render tree without any purpose. I understand that it's a minor thing, and that it most likely wasn't the thing you we're trying to show your audience. Just curious!﻿

**Comment by kentcdodds** [comment]
Hey friends! I just finished the livestream to do this :) https://codesandbox.io/s/yj7r3y103v

https://www.youtube.com/watch?v=PKUDcLGn-80&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&index=2&t=0s

**Comment by maxtsh** [comment]
Hello kent, thanks for this really useful ideas. I needed a little bit further help with this implementation so I was wondering if you could help to implement a start point for the timeout, for example, we are fetching data from a server then if something happens we want to show a timeout popup error message to users that expires a little later. thanks.

**Comment by AnthonyCatalfo** [comment]
Please unsubscribe me

**Comment by kentcdodds** [comment]
We can't do that @AnthonyCatalfo... You have to. There should be a link at the bottom of this email or you can come to the issue page and click "unsubscribe"

**Comment by kentcdodds** [comment]
@maxtsh, could you open a new issue with more details?
