### ISSUE TITLE
Your code already supports two users, don't bother with the third

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#667]
I want to write a blog post about this.

**Comment by Jero786** [comment]
Hi @kentcdodds, I'm just want to ask you about if what I'm use to do it's about the third user not. The escenario is the following:

In order to deliver my code in TDD way, I'm use to create the first first before I create my components. So, for example, If I want to create a `ListComponent` will do the following

1) Create a Unit test: 
```
it('should exist', () => {
    const {container} = render(<HeroList />)

    expect(container.firstChild.classList.contains('mv-hero-list')).toBe(true)
  })
```

2) Then I create my component:

```

function HeroList({children}) {
	return (
            <ul className="mv-hero-list"></ul>
	);
}
``` 

3) Then I want to allow that my component support a children nodes, so create a UT for support that first:

```
 it('should be able to receive children', () => {
		render(<HeroList><ul>SOME CHILDREN HERE</ul></HeroList>).getByText(/SOME CHILDREN HERE/);
  })
```
4) Then change the component to pass green the test:
```
function HeroList({children}) {
	return (
  <ul className="mv-hero-list">{children}</ul>
	);
}
```
 
## Question: 

Do you think, checking first for the class list if exist before to create a component, it's a kind of third user?, if so, how to avoid third person but still doing TDD when I create my component? Also I use to adding class checking when I extend a new part of my component, for instance: if I would like add Footer section in our `<HeroList>` component example, I will check to exist first the class `mv-hero-list__footer` and then I will create a sub div section in the list.

**Comment by kentcdodds** [comment]
https://kentcdodds.com/blog/avoid-the-test-user
