### ISSUE TITLE
How to use useMemo to optimize context consumers

### ISSUE THREAD

**Issue by terrencewwong** [kentcdodds/ama#673]
Hello!

I read your blog article recently on [Application State Management with React](https://kentcdodds.com/blog/application-state-management-with-react)

There was something in the article I didn't understand. What is the call to `React.useMemo` doing in the `CountProvider`?

```
function CountProvider(props) {
  const [count, setCount] = React.useState(0)
  const value = React.useMemo(() => [count, setCount], [count])
  return <CountContext.Provider value={value} {...props} />
}
```

I assumed this would be for preventing rerenders of context consumers, i.e. components that use the custom `useCount` hook. But I checked out the [codesandbox for the article](https://codesandbox.io/s/4qzj73lozx?fontsize=14&hidenavigation=1&module=%2Fsrc%2F03-context.js&moduleview=1) and noticed that both `CountDisplay` and `Counter` always rerender when the `count` changes. Is `useMemo` required for a different case that's not yet present in the example?

**NOTE**
Here's the original PR that started this discussion (cc @giossa94): https://github.com/kentcdodds/kentcdodds.com/pull/142

**Comment by felipeleusin** [comment]
The dependency of useMemo here means that it will always return a new version when count changes and trigger a rerender.

Both `CountDisplay` and `Counter` depend on the value of count so they should be rerendered.

The useMemo here means that if for some reason the `CountProvider` gets rerendered but the count doesn't change, it doesn't (might) trigger a rerender of the children (because the provider keeps the same value memoized by the render).

Another thing to keep in mind is that useMemo doesn't guarantee that it won't recalculate its values.

**Comment by giossa94** [comment]
Yes, that makes sense @felipeleusin. 
@terrencewwong I think we were missing something on the original discussion: even if the reference of `setCount` remains the same across renders of `CountProvider`, the reference of the array `[count, setCount]` will change on every render, and hence consumers will re-render. So the purpose of that `useMemo` is to memoize the array and avoid re-renders if `count` doesn't change. If we were passing only `setCount` as the provided value, there would be no need to memoize it.

**Comment by terrencewwong** [comment]
@felipeleusin @giossa94 thanks for your responses, I made an example in codesandbox and I see it now! I think the concept is actually quite tricky so I think I might write more about this later. Here's th codesandbox I created: https://codesandbox.io/s/xj5p774ywz

> If we were passing only setCount as the provided value, there would be no need to memoize it.

I thought this would be true! But I made a specific hook called just, `useSetCount()` expecting that I would _not_ need o call `useMemo` and in the end it didn't turn out to be true. I'm not actually sure why that is.

**Comment by felipeleusin** [comment]
I'm not sure and it's early here but if you want to solve this with a hook you need to create a second context that only has the setCount as its value. Since this doesn't change, the components using it don't need to rerender.

That being said, this is most likely a premature optmization.

You would end up with some code like:

```
const CountContext = React.createContext();
const SetCountContext = React.createContext();

const Provider = () => {
    const [count, setCount] = React.useState(0);

   return (<SetCountContext.Provider value={setCount}><CountContext.Provider value={[count, setCount]}>{children}</CountContext.Provider></SetCountContext.Provider>)
}
```

**Comment by patrykkarny** [comment]
Hi guys! I was about to ask the same question, correct me if I'm wrong but I don't see the reason for using `useMemo` in this example, any change to the state will always return the new value and as described in the docs `setCount` is a guarantee to be the same across re-renders (https://reactjs.org/docs/hooks-reference.html#usestate). In case of performance issues, I think it is better to use `useMemo` on the component level while using the context as described here https://github.com/facebook/react/issues/15156#issuecomment-474590693

**Comment by terrencewwong** [comment]
@patrykkarny , I'm working on a blog post about this topic actually. I'll share it with you as soon as I'm done! It's a bit tricky to see why `useMemo` is useful. In the meantime you can check out the codesandbox that I created https://codesandbox.io/s/xj5p774ywz.

Without `useMemo`, the component `MemoizedIncrement` would be rerendered when you press the toggle button.

**Comment by kentcdodds** [comment]
Glad to hear you're making a blog post about it @terrencewwong! I was going to do that today, but now I can write about something else 👍 😄

**Comment by patrykkarny** [comment]
hey @terrencewwong, thank you for the codesandbox examples, the topic is quite tricky and interesting, I can't wait to read your blog post about that :D in the meantime I played a little with the examples and it is true that without `useMemo` in the provider, `useCount` will return the new reference every time you click the toggle button. I think as soon as you don't have any performance issues it is fine and it is how the normal react flow works. But if you decide to block unnecessary renders you can do it at the component level:
1. uncomment the line with `const value = [count, setCount]` and comment out the one with the useMemo inside the Provider
2. replace the `MemoizedIncrement` component with this one:

```js
const MemoizedIncrement = () => {
  const [_, setCount] = useCount()

  return React.useMemo(() => {
    console.log('    MemoizedIncrement')

    return (
      <div>
        <button onClick={() => setCount(c => c + 1)}>+1 (memoized)</button>
      </div>
    )
  }, [setCount])
}
```

**Comment by sami616** [comment]
Look forward to a blog post explaining why useMemo is required here.

I use a little helper function to help create a store and contexts documented [here](https://medium.com/@samuelresua/global-state-machine-with-react-context-afd0d5475592) and would be interested to find out if useMemo could help optimize. ✌️

**Comment by JustAboutJeff** [comment]
Thanks to @kentcdodds for directing me here! The sandbox from @terrencewwong was useful in validating what I was curious about. Specifically, I was curious if we revise the example from the blog post to remove the call to `useMemo` and instead rely on object identity from the return value of `useState`. Like so:

**original**
```
function CountProvider(props) {
  const [count, setCount] = React.useState(0)
  const value = React.useMemo(() => [count, setCount], [count])
  return <CountContext.Provider value={value} {...props} />
}
```

**revised**
```
function CountProvider(props) {
  const state = React.useState(0)
  return <CountContext.Provider value={state} {...props} />
}
```

Unfortunately, based on what I'm seeing from the sandbox this will not work. Even if state does not change across renders for `CountProvider` the wrapping array returned from `useState` here will not maintain object identity, even though it's members (`count` and `setCount`) will. This key bit of nuance isn't described in the React docs as they use destructuring in every example!

**Comment by alejandronanez** [comment]
Hey y'all!

I've been reading your examples and comments (thanks for sharing what you're learned) but I'm still a bit confused about this.

In this [Codesandbox](https://codesandbox.io/s/wk7p1jm23w), my App component has a `toggle` state, I also have a component that doesn't rely on context and a couple of other components that does.
The thing is that whenever I update App's state, everything gets rerendered.

```jsx
// App.js
import { CountProvider, useCount } from "./count-context";

function DisplayCount() {
  console.log('Rendering DisplayCount');
  const { count } = useCount();

  return <div>DisplayCount: {count}</div>;
}

function NoContextComponent() {
  console.log('Rendering: NoContextComponent');
  return <div>I do not have a context</div>;
}

function IncreaseCount() {
  const { increment } = useCount();

  return (
    <div>
      <button onClick={() => increment()}>Incremenet Count</button>
    </div>
  );
}

function App() {
  const [toggle, setToggle] = React.useState(false);

  return (
    <div className="App">
      <h1>Context + UseMemo</h1>
      <NoContextComponent />
      <IncreaseCount />
      <DisplayCount />
      <button onClick={() => setToggle(!toggle)}>
        Toggle {toggle ? 'Off' : 'On'}
      </button>
    </div>
  );
}
```

```jsx
// count-context.js
const CountContext = React.createContext();

const CountProvider = props => {
  const [count, setCount] = React.useState(0);
  const value = React.useMemo(() => {
    return { count, setCount };
  }, [count]);

  return <CountContext.Provider value={value} {...props} />;
};

function useCount() {
  const context = React.useContext(CountContext);

  if (!context) {
    throw new Error("useCount must be used within a CountProvider");
  }

  const { count, setCount } = context;
  const increment = () => setCount(c => c + 1);

  return {
    count,
    increment
  };
}

export { CountProvider, useCount };
```

## React Profiler Results

When the `Toggle` button is clicked:

<details>
<summary>React's profiler - Toggle button clicked.</summary>
<br />
This happens when I click  the `Toggle` button, everything gets rendered, except the `CountProvider` which I think it's expected
<h3> First click - Toggle button</h3>
  <img src="https://user-images.githubusercontent.com/464978/57028179-04efbc80-6c04-11e9-8bd1-15c6bd6ae91f.png" />
<h3> Second click - Toggle button</h3>
<img src="https://user-images.githubusercontent.com/464978/57028200-133dd880-6c04-11e9-9aad-c0c295eff1d4.png" />
</details>

When the `Increment` button is clicked:

<details>
<summary>React's profiler - Increment button clicked.</summary>
<br />
This happens when I click  the `Increment Count` button, this is what I would expect since `DisplayCount` is a children of `App`, so `App` should not be affected (rerendered)
<h3> First click - Increment Count</h3>
  <img src="https://user-images.githubusercontent.com/464978/57028450-bf7fbf00-6c04-11e9-9b8f-47415f831212.png" />
<h3> Second click - Increment Count</h3>
<img src="https://user-images.githubusercontent.com/464978/57028467-c9092700-6c04-11e9-88e9-3fb1bdd934aa.png" />
</details>

**Comment by giossa94** [comment]
Hi @alejandronanez !

>  The thing is that whenever I update App's state, everything gets rerendered.

I think this is expected behavior, since you're calling `useState` from your `App`component, and React will re-render it on every `toggle` update. To solve this you can wrap you're `button` into a `Button` component which holds the `toggle` state, and that makes sense because none of the other children of `App` care about the `toggle` value. This follows @kentcdodds' recommendation of [keeping state as close to where it's needed as possible](https://kentcdodds.com/blog/application-state-management-with-react).

I hope this helps.
