### ISSUE TITLE
Javascript bundlers, how to choose one?

### ISSUE THREAD

**Issue by saranshkataria** [kentcdodds/ama#68]
I was going through javascript bundlers and have read through gulp, grunt, webpack and I was planning to use webpack. Then I came across jspm. Can you suggest a central resource for reading all this information since it is a lot for a newbie at all these things?

**Comment by kentcdodds** [comment]
Hi @saranshkataria,
Thanks for the question. I have no experience with JSPM. I can tell you that it doesn't have near the community as browserify or webpack. It's also kind of hard to compare because Webpack and Browserify are capable of so much more than JSPM is by itself.

You should know that I'm bias toward Webpack. I prefer it personally. Here are some resources you may be interested in comparing Webpack and Browserify:

- [Browserify vs Webpack](http://kcd.im/ZCg58) - If you need a cabin, why start with a mere pile of logs?
- [webpack for browserify users](http://kcd.im/LNRxv)
- [browserify for webpack users](http://kcd.im/lc8h3)
- [Webpack vs Browserify : By The Numbers](http://kcd.im/MDe0C)

Here's [some videos](http://kcd.im/IhkIO) (some by me) for learning webpack.

Good luck! There's a lot to learn!
