### ISSUE TITLE
Motivation of ESLint

### ISSUE THREAD

**Issue by martinoppitz** [kentcdodds/ama#70]
Good morning Kent,
I have a question about eslint. Which makes it particularly? Currently we use  jshint, but I like  new approaches. ;)

Thanks for your answer.

Best regards Martin

**Comment by kentcdodds** [comment]
Hi @martinoppitz! Thanks for the question.
I made the move to ESLint when JSHint didn't support the ES6 features I was using. I expect it does now, but I wont ever go back because of all the things I gained by switching to ESLint. To name a few, here are some of the features I love about ESLint that JSHint doesn't have:

- Many many many more rules
- Ability to make custom rules
- Provide additional options for rules to configure them exactly how I like
- The [`--fix`](http://eslint.org/docs/user-guide/command-line-interface#fix) flag (I think JSCS has something like this)
- [Sharable configs](http://eslint.org/docs/developer-guide/shareable-configs) (I have [one](http://npm.im/eslint-config-kentcdodds))

Thanks for the question!
