### ISSUE TITLE
Faith

### ISSUE THREAD

**Issue by CodefulDom** [kentcdodds/ama#721]
In a career field that demands more of your time to improve and hone your skills, how do you make time for your faith which has been something you voiced as important?

**Comment by kentcdodds** [comment]
Hi @CodefulDom!

This is a great question. I talk a lot about my productivity (and what I do with my time) in [this blog post](https://kentcdodds.com/blog/how-i-am-so-productive)). In the blog post I talk about how my productivity is really an illusion because I make a lot of the learning a part of my job. So I don't spend more than 40 hours a week doing anything job related (normally). With that backdrop, I still have a lot of time to dedicate to developing the more important aspect of my life: my faith and family relationships.

So it's not that I have to make time for faith, but more like "I only have 40 hours in a week to dedicate to work" and I force my work to fit within that time. And I consider learning and "honing my skills" to be work that fits in that time as well.

So I'd say that, just like with tithing, I take the resources I have available to me and allocate the Lord's portion first. Then I allocate what's remaining to the other commitments that I have. I've found that doing things this way results in always having sufficient for my needs.

I hope that's helpful!
