### ISSUE TITLE
Shoul tests depend on render count times

### ISSUE THREAD

**Issue by iamandrewluca** [kentcdodds/ama#723]
Shoul tests depend on render count times?

> This breaks a lot of the tests, and I'm not certain why. Many of the redux-form tests focus on how many times stuff gets rerendered
> https://github.com/erikras/redux-form/pull/4431

Thanks!

**Comment by kentcdodds** [comment]
Nope. I've been meaning to write a blog post titled "Rendering is Not an API" but the gist is that your component should be able to be rendered multiple times with the same props and not have any observable change. This is what "idempotent" is all about and components need to be idempotent, otherwise you will have bugs.

I hope that helps!
