### ISSUE TITLE
How to test a Multi Page Form with RTL

### ISSUE THREAD

**Issue by ritchieanesco** [kentcdodds/ama#725]
Hi Kent,

So i've been following the RTL way of testing and finding it great! We currently have a 9 page form and have been writing tests similarly to how they've have been written in the Testing Javascript course.

However, we are now finding that one of our test cases have become gigantic as this single test asserts that the user fills each page in the correct sequence.. i.e. user fills page 1, then page 2, etc.

Can you please recommend a way we can break this up?

Thanks again for all the work you do for the community.
Ritchie

**Comment by kentcdodds** [comment]
Hi @ritchieanesco!

I answered this via a DevTips with Kent video in two parts which you can watch here: https://www.youtube.com/watch?v=9xaJ78qEJCM&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u and here: https://www.youtube.com/watch?v=I0dYO2JMUmQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

I'm really happy with how things turned out actually and you can check out the final result here: https://github.com/kentcdodds/multi-page-testing-demo

I'd recommend that you have one test for the "happy" path here, but then for any edge cases/validation/etc. you test each page in isolation from one another. This is for test speed and simplicity. Good luck!

**Comment by ritchieanesco** [comment]
Thanks so much for coding this live!! Its great to see how you problem solve stuff.

Just a quick question in your demo, you are only using one field per page. Would you still implement this test the same way if you had 10 or more fields per page?

**Comment by kentcdodds** [comment]
Yes

**Comment by vitorcamachoo** [comment]
@kentcdodds 
Since you're testing all the flow, validations on the main component "Form", do you still have to test each form step component ? In some way we're repeating all field validations for each Step which in my opinion is not a good ideia, but in other way, if we do all the tests on the main component, the steps won't have any test. Whats the best practise in this case?

**Comment by vitorcamachoo** [comment]
@kentcdodds many thanks!
