### ISSUE TITLE
React Boston

### ISSUE THREAD

**Issue by JimmayVV** [kentcdodds/ama#727]
How many conferences do you plan to attend in a given year? I see React Boston only has a few confirmed speakers at the moment, and would be beyond thrilled if somehow you ended up on the list of speakers there :)

Thanks for all the work you've put in for the JS community!!

**Comment by kentcdodds** [comment]
Hi @JimmayVV,

I really appreciate that you want me to come out! I don't typically plan it out, but it takes a LOT to get me to travel because it makes such a big impact on my family. I try to keep trips down to two or three a year. I'm afraid it's unlikely I'll be coming out to Boston this year.

Maybe I'll be able to travel more when my kids are a bit older. Thanks!
