### ISSUE TITLE
What Slide Deck Tool Are You Using These Days?

### ISSUE THREAD

**Issue by edm00se** [kentcdodds/ama#739]
I've seen a couple public repos of yours lately, such as [application-state-management-talk](https://github.com/kentcdodds/application-state-management-talk) and [managing-open-source](https://github.com/kentcdodds/managing-open-source) in which your project structure looks like:

```sh
.
├── .prettierrc
└── slides
    ├── 00.md
    ├── 01.md
    ...
```

Being able to segregate slides by markdown file seems nice, what tool are you using for your slide decks these days?

**Comment by kentcdodds** [comment]
Hi @edm00se :)

I'm literally just using my code editor. Like this: https://www.youtube.com/watch?v=VIRcX2X7EUk&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf

I do this in part because I'm lazy, but also because I feel really comfortable in a text editor and can type code and highlight things really easily in the editor.

**Comment by edm00se** [comment]
😆 That's perfect. Since mostly developers look at your slides, that makes it pretty easy. Thanks!
