### ISSUE TITLE
Is time slicing happening out of the box in concurrent mode?

### ISSUE THREAD

**Issue by sschottler** [kentcdodds/ama#766]
Is time slicing happening out of the box? Seems I have to opt-in to prevent UI thread blocking with either `startTransition` or `useDeferredValue`. Am I missing something?

https://codesandbox.io/s/headless-grass-5ihil

My understanding of your [how to enable concurrent mode](https://kentcdodds.com/blog/how-to-enable-react-concurrent-mode) post is that time slicing happens out of the box just by enabling concurrent mode:

```javascript
ReactDOM.createRoot(rootElement).render(<App />);
```
> If you have some user interaction in your app that you know is slow, try that out and if it's less janky, that's time slicing at work

**Comment by kentcdodds** [comment]
Hi @sschottler,

I assumed that time slicing would just apply all the time, but it turns out that for updates triggered by input event handlers are synchronous and time slicing does not apply. I'm having an active conversation with Andrew Clark about this right now that you may find interesting: https://twitter.com/kentcdodds/status/1205694187653349379

Thanks for asking! Experimental tech is interesting to dive into!

**Comment by sschottler** [comment]
Interesting. Thanks for the response!
