### ISSUE TITLE
If you could do it all over again, what would you do instead of software?

### ISSUE THREAD

**Issue by joshmanders** [kentcdodds/ama#77]
The world goes back, life is different, computers don't excel like they did in our world, but they exist, and it's a highly specified career, not something most get into.

What would you be doing today, if it weren't for software?

**Comment by kentcdodds** [comment]
Hi @joshmanders! Thanks for the question!

This is a hard question (as are your others #75 and #76, which I'll eventually get to). I honestly don't know what else I enjoy doing other than spending time with my family and spending time coding. I've definitely thought about what I'd do if I lived back in the 60s or so.

I'd probably be involved in Business and/or Accounting. Not because I enjoy it necessarily, but because I think that I could be successful doing those things.

Either that or I'd be one of the few people in the highly specified career :-) I just don't know what I'd do without software!

Thanks for the tough question. It makes me shudder just thinking about going to work in a suit every day...

**Comment by joshmanders** [comment]
Indeed are tough questions. Thanks for taking the time to answer them.
