### ISSUE TITLE
What did you do at work today?

### ISSUE THREAD

**Issue by jwhitfieldseed** [kentcdodds/ama#78]
(or your last working day)?

**Comment by kentcdodds** [comment]
Hey @jwhitfieldseed,
Thanks for the question!

So the day's coming to a close. I spent the bulk of it digging through my `node_modules` directory trying to figure out how a `req` object ([express](http://expressjs.com/)) got a particular property set on it. As cool as the middleware model is, it's a challenge to keep things simple because you never quite know where a certain property gets added to the request object. The trouble I was having was because turns out we used to use a module for something and we now actually call into a third party service, so all the `console.log`s weren't going to actually run. (－‸ლ)

This is one of the challenges with moving from a small company to a large company. At my last job, I wrote or adopted all the abstractions, so I understood how everything worked. I've only been here 3 weeks. Gives me a great deal of insight into the difference between familiar and simple :-)

I also have been spending some time working on setting up a framework for testing our React stuff with [AVA](https://npmjs.org/package/ava). That's awesome. I love testing. AVA is a super slick test runner with a lot of up side. :+1: @sindresorhus, @jamestalmage, and others :-)

Also spent time addressing emails, cordinating efforts with stuff, twitter, and answering questions :-)

Thanks!
