### ISSUE TITLE
How do you balance your life?

### ISSUE THREAD

**Issue by benpetersen** [kentcdodds/ama#82]
How do you balance your life?

There is a constant pressure to work on side projects, keep the house together (cooking, cleaning, or projects at home), and talking about your day. It seems that if things don't fall right into place, it's nearly impossible to be done by 10pm. So, how do you juggle all life throws at you?

**Comment by kentcdodds** [comment]
Hey @benpetersen,
Thanks for the question. Sorry it's taken me so long to answer. I think you'll get many of the answers from my recent answer to #83. But to answer you more specifically...

Yes, there's definitely constant pressure to work on side projects. Especially when I have a building pile of issues on my OSS projects to address. It's crazy. And I've definitely felt overwhelmed at times. But you just have to come to terms with the fact that you don't really owe anyone anything. From there, anything that you do is a service to the community, even if it doesn't solve the use cases of everyone.

I have a wonderful wife who helps me keep the house together. We work hard to make sure that the kids are taken care of and the house is relatively clean. We don't nail it every day, but it gets worked out one way or another eventually.

Over all of this, the most important thing to remember is that you need to do the first things first. I spend a lot of time with my family because relationships (with them in particular) are the most important part of my life. Then they give me time to do the side stuff.

I hope this helps a little :-)
