### ISSUE TITLE
When did you start coding an why?

### ISSUE THREAD

**Issue by kplund** [kentcdodds/ama#85]
More people should learn to code.
In 1-2 sentences, when did you start coding and why?

Thanks!

Karl Philip Lund

PS. I´m writing a blog post about the topic at www.webagility.com

**Comment by kentcdodds** [comment]
Hi @kplund!
Thanks for the question! Here's my answer

I really started coding in September 2011 because I wanted to automate some monkey work I was doing at an internship. I was totally hooked when I discovered and started using JavaScript a year later.

Good luck on your blogpost! Let me know when you publish it :D
