### ISSUE TITLE
Angular2 Classes

### ISSUE THREAD

**Issue by jimthedev** [kentcdodds/ama#9]
Given Angular2's examples being heavily focused on classes and composition, do you have any reservations? Will you use classes or will you write your own prototypes? What is your impression of annotations?

**Comment by kentcdodds** [comment]
As illustrated [here](https://github.com/kentcdodds/ama/issues/6#issuecomment-118698270) I'm not a huge fan of classes. The reason is that I don't like inheritance from an architecture standpoint. I'm concerned that we're going to wind up in a situation that's already perforating many classical languages in that we get 7 layers deep into inheritance and suddenly we're in a huge maintenance nightmare. I prefer to be functional.

That said, I know when I'm licked. Unless there's a reasonable alternative, I'm fairly confident that I'll cave and use classes for my components in Angular 2. We just need to enforce good coding standards for ourselves.

I hope there's some tool developed that can determine how many levels deep you are inheriting and warns if you inherit beyond a threshold. Then I'll make that a pre-commit git hook (using [ghooks](http://npm.im/ghooks)) that disallows inheriting beyond 3 levels and requires a special comment beyond 2 levels that says: `// I, {coder's name}, being of sound mind and judgement, promise that this was the best way to accomplish my task and that I will pay the technical debt associated with this architectual nightmare`... Just kidding, that's way too extreme :-) But it was fun to write.

As for annotations, I'm a fan. I think there are a lot of benefits to declaratively describing your class (static analysis for tooling, all the benefits of declarative code in general, etc.).

Thanks for the question :-)

**Comment by jimthedev** [comment]
Nice. I also have preferred functional over classical up until now and am skeptical but open to seeing if this improves development. That tool you described sounds awesome and seems like it would be a good addition to an eventual tool like jscs for typescript/es6. I am a huge fan of the shift towards composition so hopefully that helps avoid the 7 levels you described, but we shall see. Thanks for answering.
