### ISSUE TITLE
How did you learn Vim? 

### ISSUE THREAD

**Issue by lukeschunk** [kentcdodds/ama#90]

**Comment by kentcdodds** [comment]
Hi @lukeschunk! Thanks for the question.

I think you mean: "How are you learning Vim?" I'm far from expert at Vim. Still very much a newbie. I tried learning several times before and it never really stuck. Now I'm frustrated every time I try to use a text input that only has insert mode (like the textbox for this GitHub comment).

I'm also frustrated because I don't have time to configure my editor to fix the small things that bug me about it here and there. But I just love being able to navigate around a file so quickly with just the keyboard.

So to answer your question more directly... I used [janus](https://github.com/carlhuda/janus) for a while, then got a new computer and rebuilt [my vim config](https://github.com/kentcdodds/dotfiles) myself. I think this worked out well because I was exposed to some of the cool plugins out there, but now I know how everything works (because I've built it myself).

Pretty much everything else is just persistence. Good luck!

**Comment by alexbooker** [comment]
I follow you both on Twitter and so I saw this question mentioned.

I just wanted to jot down a couple of my own tips, I hope that's OK :blush: 

- It's easy to dismiss [Vim Tutor](http://vim.wikia.com/wiki/Tutorial) but it's actually an _awesome_ resource for people who are new to Vim.
- Until your Vim muscle memory develops, use a [Vim cheat sheet](http://vim.rtorr.com/).
- Here's a neat little game called [Vim Adventures](http://vim-adventures.com/). It's quite a fun way to learn the Vim key-bindings.
- Instead of trying to learn all of Vim at once, I recommend installing a Vim plugin for your favourite editor (e.g. [vim-mode](https://github.com/atom/vim-mode) for Atom). 

I'm no Vim expert but if you have any questions, feel free to ping me :smile:!

**Comment by kentcdodds** [comment]
Thanks for chiming in with the resources @alexbooker!

**Comment by lukeschunk** [comment]
Thanks both of you :crystal_ball:
