### ISSUE TITLE
Angular2 vs React : Which you prefer to?

### ISSUE THREAD

**Issue by nvcken** [kentcdodds/ama#92]
I saw your contribution on both.
Which you prefer to?
- Their ecosystem, community
- use at your job/ work ?
- or spare time ?

How you manage your time on them so that you can comprehend one by one ? and also follow their release change log ?

Thanks a lot

**Comment by kentcdodds** [comment]
Hi @nvcken! Thanks for the question!

I've answered [this question](https://github.com/kentcdodds/ama/issues?utf8=%E2%9C%93&q=is%3Aissue+angular+react) a few times in previous questions, but here's some basic answers to your specific questions:

1. Yep, I've contributed to both now :-)
2. I prefer React
3. I find the Angular ecosystem and community more tight-knit and the React community more dispersed and diverse. I think both are great. I'm a big fan of the lego-style building blocks of React. I know it causes some people JS fatigue, but I like having the choice.
4. When I started at PayPal, I stopped using Angular and started using React at work.
5. On my spare time I sharpen the skills that I want to focus on, so I have done very little angular since I changed jobs two months ago.
6. I have a hard time managing time. I don't have enough of it. That's why I don't do any Angular anymore.
7. I try to follow the changelog of React. I no longer use Angular so I don't do much to follow the changelog. Though I still listen to two Angular-specific podcasts (#17)

You're welcome! :D
