### ISSUE TITLE
Why Doesn't My Fork Update?

### ISSUE THREAD

**Issue by geirman** [kentcdodds/ama#93]
Hey Kent,

I don't believe the answers to my questions are covered in your egghead.io tutorial, so I thought I'd ask you directly.

In short, under your tutelage, I was able to iterate on [this PR](https://github.com/facebook/react-native/pull/6423) fairly painlessly. I was amazed that I was able to make changes on my generically named "patch-1" branch directly to the [facebook/react-native](https://github.com/facebook/react-native) repository with a simple `git push`. I'm already working on my second PR, but am confused on a couple things I hope you won't mind helping me understand.

1. Why isn't my branch [geirman/react-native](https://github.com/geirman/react-native) updated? Latest commit is b22d6a6  on Oct 31, 2015. 
2. Shouldn't my PR be listed under my [PRs tab](https://github.com/geirman/react-native/pulls)?
3. When I do a `git fetch upstream` in my local version of the repo, then do a `git log`, the latest entry is the b22d6a6 one on Oct 31, 2015. My expectation is that it would pull down the latest files directly from the upstream remote (which is facebook/react-native), which I have to go into something called "detached HEAD" mode with the `git checkout upstream/master` command to see.
4. How do I update my fork [geirman/react-native](https://github.com/geirman/react-native) so that it's up to date with [facebook/react-native](https://github.com/facebook/react-native), assuming that's what I want to do?

Thanks in advance! 

Chris

**Comment by kentcdodds** [comment]
Hi @geirman! Thanks for the question(s) :D

## 1

Your fork wont update automatically. This is why [I suggest](https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository?series=how-to-contribute-to-an-open-source-project-on-github) that you set your fork's `master` branch to `--set-upstream-to` the original repository.

Then you have to manually update it yourself. Do this by checking out your `master` branch and running `$ git pull` then you can `$ git push origin master` to update your fork's master.

However, I generally don't care that my fork's `master` is actually up to date. It's just my local branches are rebased on master. So my general workflow is:

```
$ git checkout master
$ git pull
$ git checkout -b pr/my-branch
```

The `pr/` bit is just a convention I've started following, you can name your branch whatever you want.

If you need to update a branch with the current state of upstream's `master`, this is what I generally do (assuming you have your branch currently checked out):

```
$ git fetch upstream
$ git rebase upstream/master
```

This will replay all of your commits on top of `upstream/master`, effectively updating your branch to the current state of the original repository, and then redoing all the commits you've done since the last time it was updated. This is probably what you want.

You'll need to note that `rebase` is a destructive operation, so you'll want to make sure you know what's going on before pushing because you'll have to force push.

I pretty much cover all of this [in this lesson](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github).

## 2

Your fork is basically an entirely different repository from the original repository. It has its own metadata (issues, prs, etc.). You can have people submit PRs to your fork! So any PRs you make to the original repo will be in the original repo's metadata.

## 3

`$ git fetch upstream` doesn't pull down any commits, it simply gets data about what's in the upstream remote repository. To pull down commits you'll have to do `$ git pull`. But, like I mentioned, I generally don't need to do this and doing the workflow I mentioned earlier will do this for you (doing a `rebase upstream/branch-name` will pull the commits down for the rebase).

## 4

Hopefully I answered this question in my other answers :-)

I hope this helps! Thanks for the questions!
