### ISSUE TITLE
when did you start learning vim?

### ISSUE THREAD

**Issue by deezahyn** [kentcdodds/ama#99]
you seem very comfortable now! :+1:

**Comment by kentcdodds** [comment]
Thanks for the question @deezahyn!
I started learning vim around.... August 2015. I'm still a newbie. There are a lot of issues with my config that make it really annoying to use. But I have a hard time using anything else now. Having modes is just really handy and I've developed a lot of muscle memory with vim. Maybe I'll move to something else one day.

**Comment by deezahyn** [comment]
@kentcdodds Can I ask a followup question?  How long did it take you for you to match or overtake your previous editor speed?

**Comment by kentcdodds** [comment]
> Can I ask a followup question?

Always!

> How long did it take you for you to match or overtake your previous editor speed?

Hmmm... My previous editor was Webstorm. Actually, I'm pretty sure that I'm still slower with vim than I was with Webstorm. I was pretty fast using Webstorm.

I'm still not 100% sold on vim, but I feel a bit locked in because I've just gotten so used to it and it's nice that it's so lightweight. Though to be honest, it's not as fast as I thought it would be. People keep telling me to try out neovim and maybe I will someday... `¯\_(ツ)_/¯`

**Comment by deezahyn** [comment]
thanks!

**Comment by shadoath** [comment]
@kentcdodds Didi you ever get into Neovim?
In relation to #531 I see you have stopped with Vim. Do you think an IDE overturns the simplicity of Vim and having to have all the plugins?

**Comment by siva87** [comment]
@kentcdodds I'm using Webstorm with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim) plugin (developed by Jetbrains as well).
You would get best of both worlds. ;)
